import { firebaseConfig } from '../firebase-config.js';
import { makeDataAdapterV2 } from './data-adapter-v2.js';

const FIREBASE_VERSION = '10.14.1';
const SHARED_DOC = ['appData', 'shared'];
const NOTES_DOC = ['appData', 'notes'];
const SLOTS = { '1': '10:00–12:00', '2': '14:00–16:00', '3': '3-й слот / резерв' };
const $ = (s, root = document) => root.querySelector(s);
const $$ = (s, root = document) => [...root.querySelectorAll(s)];
const uid = () => crypto.randomUUID?.() || `${Date.now()}-${Math.random()}`;
const money = n => new Intl.NumberFormat('ru-RU').format(Math.round(Number(n) || 0)) + ' ₽';
const num = v => Math.max(0, Number(String(v ?? '').replace(',', '.')) || 0);
const dateKey = d => { const x = new Date(d); return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`; };
const today = () => dateKey(new Date());
const fmtDate = d => new Intl.DateTimeFormat('ru-RU', { weekday:'long', day:'numeric', month:'long' }).format(new Date(`${d}T12:00:00`));
const fmtShort = d => new Intl.DateTimeFormat('ru-RU', { day:'2-digit', month:'2-digit', year:'numeric' }).format(new Date(`${d}T12:00:00`));
const esc = s => String(s ?? '').replace(/[&<>"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const isDone = j => j.status === 'Выполнен';
const isCancelled = j => j.status === 'Отменён';
const isMeasure = j => j.type === 'Замер';
const activityDate = j => isDone(j) ? (j.completedDate || j.date) : j.date;
const emptyState = () => ({ jobs: [], expenses: [], version: 5 });
const normalize = d => ({ jobs: Array.isArray(d?.jobs) ? d.jobs.map(j => ({ ...j, id:j.id || uid(), date:j.date || today(), slot:String(j.slot || '1'), type:j.type || 'Монтаж', client:j.client || '', price:num(j.price), status:j.status || 'Запланирован', paid:j.paid !== false, completedDate:j.completedDate || '', time:j.time || '', measurePrice:num(j.measurePrice), measurePaid:j.measurePaid === true, measureCredit:num(j.measureCredit), convertedToJobId:j.convertedToJobId || '', source:j.source || j.store || '' })) : [], expenses: Array.isArray(d?.expenses) ? d.expenses.map(e => ({ ...e, id:e.id || uid(), date:e.date || today(), amount:num(e.amount), category:e.category || 'Прочее', comment:e.comment || '', cancelled:e.cancelled === true })) : [], version:5 });
let F, auth, db, user, unsubscribeShared=null, unsubscribeNotes=null; let state=emptyState(), notes=[], serverReady=false, online=navigator.onLine; let month=new Date(new Date().getFullYear(),new Date().getMonth(),1), financePeriod='day', editingType='Монтаж';
function status(text,kind='normal'){const el=$('#syncStatus');if(el){el.textContent=text;el.dataset.state=kind;}}
function toast(text,kind='normal'){let el=$('#toast');if(!el){el=document.createElement('div');el.id='toast';document.body.append(el);}el.textContent=text;el.dataset.state=kind;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.remove(),3400);}
function modal(id,open=true){const el=$(`#${id}`);if(!el)return;el.classList.toggle('open',open);el.setAttribute('aria-hidden',String(!open));document.body.classList.toggle('modal-open',open || !!$('.modal.open'));}
function showAuth(show){$('#authScreen')?.classList.toggle('hidden',!show);$('#app')?.classList.toggle('hidden',show);}
function authError(e){return ({'auth/invalid-credential':'Неверный email или пароль.','auth/invalid-email':'Проверьте email.','auth/user-disabled':'Доступ отключён.','auth/too-many-requests':'Слишком много попыток. Попробуйте позже.','auth/email-already-in-use':'Этот email уже зарегистрирован.','auth/weak-password':'Пароль должен быть не короче 6 символов.','auth/operation-not-allowed':'В Firebase не включён Email/Password.','auth/network-request-failed':'Нет соединения.'}[e?.code]||e?.message||'Ошибка авторизации.');}
function authMessage(text,error=false){const el=$('#authMessage');if(el){el.textContent=text;el.className=`auth-message${error?' auth-message--error':''}`;}}
async function initFirebase(){const [appMod,authMod,fs]=await Promise.all([import(`https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-app.js`),import(`https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-auth.js`),import(`https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-firestore.js`)]);const app=appMod.initializeApp(firebaseConfig,'montaji-aa-production');auth=authMod.getAuth(app);db=fs.getFirestore(app);F={...fs,authMod};}
function bindAuth(){
      const form=$('#authForm');
      if(form&&!form.dataset.bound){form.dataset.bound='1';form.addEventListener('submit',async e=>{e.preventDefault();e.stopPropagation();const email=$('#authEmail').value.trim(),pass=$('#authPassword').value;if(!online)return authMessage('Нет интернета.',true);if(!email||!pass)return authMessage('Введите email и пароль.',true);authMessage('Входим…');const button=form.querySelector('button[type="submit"]');if(button){button.disabled=true;button.textContent='Входим…';}try{await F.authMod.signInWithEmailAndPassword(auth,email,pass)}catch(err){authMessage(authError(err),true)}finally{if(button){button.disabled=false;button.textContent='Войти';}}},{passive:false});}
      $('#signUpBtn')?.addEventListener('click',async()=>{const email=$('#authEmail').value.trim(),pass=$('#authPassword').value;if(!email||!pass)return authMessage('Введите email или пароль.',true);if(pass.length<6)return authMessage('Пароль должен быть не короче 6 символов.');try{const c=await F.authMod.createUserWithEmailAndPassword(auth,email,pass);await F.authMod.sendEmailVerification(c.user);await F.authMod.signOut(auth);authMessage('Письмо отправлено. Подтвердите email и войдите.')}catch(err){authMessage(authError(err),true)}});
      $('#resetBtn')?.addEventListener('click',async()=>{const email=$('#authEmail').value.trim();if(!email)return authMessage('Введите email.',true);try{await F.authMod.sendPasswordResetEmail(auth,email);authMessage('Ссылка для сброса отправлена.')}catch(err){authMessage(authError(err),true)}});
    }
function currentNotesData(s){const d=s?.exists()?s.data()?.data||{}:{};return Array.isArray(d.notes)?d.notes:[];}
function __adapter(){return makeDataAdapterV2({fs:F,db,user,online,status,toast,setState:(next)=>{state=next;},render});}

async function loadServer(){
  serverReady=false;
  const jobsOk = await __adapter().loadServerV2();
  serverReady = jobsOk;
  if(!user||!online){notes=[];return jobsOk;}
  try{
    const notesSnap = await F.getDocFromServer(F.doc(db,...NOTES_DOC));
    notes = currentNotesData(notesSnap);
  }catch(err){console.warn('Notes document unavailable.',err);}
  return jobsOk;
}
function startRealtime(){
  __adapter().startRealtimeV2();
  unsubscribeNotes?.();
  if(!user||!online)return;
  unsubscribeNotes=F.onSnapshot(F.doc(db,...NOTES_DOC),snap=>{if(!online)return;notes=currentNotesData(snap);renderNotes()},()=>{});
}
async function saveShared(mutator){
  return __adapter().saveSharedV2(mutator);
}
async function saveNotes(mutator){if(!serverReady||!online||!user)throw new Error('Нет соединения с общей базой');const ref=F.doc(db,...NOTES_DOC);await F.runTransaction(db,async tx=>{const snap=await tx.get(ref),cur={notes:currentNotesData(snap)},next=await mutator(JSON.parse(JSON.stringify(cur)));tx.set(ref,{data:{notes:Array.isArray(next.notes)?next.notes:[]},version:1,updatedAt:F.serverTimestamp(),updatedBy:user.uid},{merge:true})});}
function jobsForDate(d){return state.jobs.filter(j=>!isCancelled(j)&&j.date===d);} function activeJobs(d){return jobsForDate(d).filter(j=>!isDone(j));} function montageCount(d){return jobsForDate(d).filter(j=>j.type==='Монтаж').length;} function freeSlot(d){return '1';}
function periodBounds(period){const now=new Date();if(period==='day')return[today(),today()];if(period==='week'){const day=(now.getDay()+6)%7,start=new Date(now);start.setDate(now.getDate()-day);const end=new Date(start);end.setDate(start.getDate()+6);return[dateKey(start),dateKey(end)]}if(period==='month')return[dateKey(new Date(now.getFullYear(),now.getMonth(),1)),dateKey(new Date(now.getFullYear(),now.getMonth()+1,0))];return['0000-01-01','9999-12-31'];}
function effectiveIncome(j){if(isCancelled(j)||!isDone(j))return 0;if(isMeasure(j))return num(j.measurePrice||j.price);return num(j.price);}
function totals(period){const[a,b]=periodBounds(period),jobs=state.jobs.filter(j=>!isCancelled(j)&&isDone(j)&&activityDate(j)>=a&&activityDate(j)<=b),income=jobs.reduce((s,j)=>s+effectiveIncome(j),0),expenses=state.expenses.filter(e=>!e.cancelled&&e.date>=a&&e.date<=b).reduce((s,e)=>s+e.amount,0),unpaid=jobs.filter(j=>j.paid===false).reduce((s,j)=>s+effectiveIncome(j),0);return{income,expenses,net:income-expenses,unpaid,done:jobs.length};}
function dateTotals(d){const jobs=jobsForDate(d).filter(isDone),income=jobs.reduce((s,j)=>s+effectiveIncome(j),0),expenses=state.expenses.filter(e=>!e.cancelled&&e.date===d).reduce((s,e)=>s+e.amount,0),unpaid=jobs.filter(j=>j.paid===false).reduce((s,j)=>s+effectiveIncome(j),0);return{income,expenses,net:income-expenses,unpaid};}
function mapLinks(address){const q=encodeURIComponent(address);return`<a class="map-chip" href="https://yandex.ru/maps/?text=${q}" target="_blank" rel="noopener">Яндекс</a><a class="map-chip" href="https://2gis.ru/search/${q}" target="_blank" rel="noopener">2ГИС</a>`;} function callLink(phone){const p=(phone||'').replace(/[^\d+]/g,'');return p?`<a class="action-chip" href="tel:${esc(p)}">Позвонить</a>`:'';} function shareAddress(j){return j.address?`<button class="action-chip share-address" data-id="${esc(j.id)}">Отправить адрес</button>`:'';}
function statusLabel(j){if(j.status==='Выполнен')return`<span class="status-pill done">✓ Выполнен${j.paid===false?' · долг':''}</span>`;if(j.status==='В пути')return'<span class="status-pill route">В пути</span>';if(j.status==='На объекте')return'<span class="status-pill onsite">На объекте</span>';if(j.status==='Отменён')return'<span class="status-pill cancelled">Отменён</span>';if(j.type==='Замер')return'<span class="status-pill measure">Замер</span>';return`<span class="status-pill">${esc(j.status||'Запланирован')}</span>`;}
function jobCard(j,{compact=false}={}){const time=isMeasure(j)?(j.time||SLOTS[j.slot]||'Свободное время'):(SLOTS[j.slot]||j.time||''),amount=isMeasure(j)?num(j.measurePrice||j.price):num(j.price),credit=j.measureCredit?` · зачёт ${money(j.measureCredit)}`:'';return`<article class="job-card ${isDone(j)?'job-done':''} ${isMeasure(j)?'job-measure':''}" data-job-card="${esc(j.id)}"><div class="job-top"><div><div class="job-client">${esc(j.client||'Без клиента')}</div><div class="job-meta">${esc(time)} · ${esc(j.type)}${j.store?' · '+esc(j.store):''}</div></div><div class="amount">${money(amount)}</div></div><div class="job-details">${j.address?`<div class="detail-line">📍 ${esc(j.address)}</div>`:''}${j.comment&&!compact?`<div class="detail-line note-line">${esc(j.comment)}</div>`:''}<div class="card-status">${statusLabel(j)}${j.completedDate?` <small>${fmtShort(j.completedDate)}</small>`:''}${credit?`<small>${credit}</small>`:''}</div></div><div class="actions">${j.address?mapLinks(j.address):''}${callLink(j.phone)}${shareAddress(j)}<button class="action-chip primary-chip edit" data-id="${esc(j.id)}">Открыть</button></div>${!compact&&!isDone(j)&&!isCancelled(j)?`<div class="quick-actions"><button data-quick="route" data-id="${esc(j.id)}">В путь</button><button data-quick="done" data-id="${esc(j.id)}">Выполнено</button>${j.paid===false?`<button data-quick="paid" data-id="${esc(j.id)}">Оплачено</button>`:''}</div>`:''}</article>`;}
function renderToday(){const d=today(),jobs=jobsForDate(d),t=totals('day'),w=totals('week'),m=totals('month');$('#topDate').textContent=new Intl.DateTimeFormat('ru-RU',{weekday:'long',day:'numeric',month:'long'}).format(new Date());$('#todayIncome').textContent=money(t.net);$('#todayGross').textContent=money(t.income);$('#todayExpense').textContent=money(t.expenses);$('#todayLoad').textContent=String(montageCount(d));$('#todayProgress').style.width=montageCount(d)>0?'100%':'0%';$('#todayWeek').textContent=money(w.net);$('#todayMonth').textContent=money(m.net);const advice=[],tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+1);const tc=montageCount(dateKey(tomorrow)),late=state.jobs.filter(j=>!isCancelled(j)&&!isDone(j)&&j.date<d).length;if(late)advice.push(`⚠️ ${late} просроченных выездов`);if(tc>0)advice.push(`✨ Завтра запланировано ${tc} монтажей`);if(t.unpaid)advice.push(`💰 ${money(t.unpaid)} ещё не оплачено`);$('#insights').innerHTML=(advice.slice(0,3).map(x=>x.includes('не оплачено')?`<button class="insight" data-open-debts="1">${x}<span>›</span></button>`:`<div class="insight">${x}</div>`).join('')||'<div class="insight calm">✨ На сегодня всё спокойно</div>');$('#todayList').innerHTML=jobs.length?jobs.sort((a,b)=>String(a.slot).localeCompare(String(b.slot))).map(jobCard).join(''):'<div class="empty-card"><strong>Сегодня свободно</strong><span>Добавь монтаж, замер или расход через +</span></div>';const upcoming=[];for(let i=1;i<=7;i++){const x=new Date();x.setDate(x.getDate()+i);const k=dateKey(x),js=activeJobs(k);if(js.length)upcoming.push({k,x,js});}$('#upcoming').innerHTML=upcoming.slice(0,5).map(o=>`<button class="upcoming" data-date="${o.k}"><b>${o.x.getDate()}</b><span>${esc(o.js[0].client||o.js[0].type)}</span><em>${o.js.length} выезд · ${money(o.js.reduce((s,j)=>s+(j.price||j.measurePrice||0),0))}</em>›</button>`).join('')||'<div class="muted">Ближайшие дни свободны.</div>';renderExpensesToday();renderNotes();bindCards();}
function renderExpensesToday(){const host=$('#todayExpenses');if(!host)return;const ex=state.expenses.filter(e=>!e.cancelled&&e.date===today());host.innerHTML=ex.length?ex.map(e=>`<div class="expense-item"><div><b>${esc(e.category)}</b><small>${esc(e.comment||'Без комментария')}</small></div><strong>− ${money(e.amount)}</strong></div>`).join('')+`<div class="expense-total"><span>Итого</span><b>− ${money(ex.reduce((s,e)=>s+e.amount,0))}</b></div>`:'<div class="muted">Расходов ещё нет</div>';}
function renderCalendar(){const y=month.getFullYear(),m=month.getMonth(),start=(new Date(y,m,1).getDay()+6)%7,last=new Date(y,m+1,0).getDate();let h='';for(let i=0;i<start;i++)h+='<div class="day blank"></div>';for(let n=1;n<=last;n++){const k=dateKey(new Date(y,m,n)),c=montageCount(k),js=activeJobs(k),hasMeasure=js.some(isMeasure);h+=`<button class="day ${c>0?'busy':''} ${hasMeasure?'has-measure':''} ${k===today()?'today':''}" data-date="${k}"><b>${n}</b><span>${js.length} выезд</span><i>${c}/3${hasMeasure?' · замер':''}</i></button>`;}$('#scheduleMonth').textContent=new Intl.DateTimeFormat('ru-RU',{month:'long',year:'numeric'}).format(month);$('#calendar').innerHTML=h;$$('.day[data-date]').forEach(b=>b.onclick=()=>openDay(b.dataset.date));}
function openDay(d){const js=jobsForDate(d),pending=js.filter(j=>!isDone(j)),done=js.filter(isDone),t=dateTotals(d),m=document.createElement('div');m.className='modal open';m.innerHTML=`<div class="backdrop"></div><div class="sheet"><div class="handle"></div><div class="sheet-head"><div><div class="eyebrow">Рабочий день</div><h2>${esc(fmtDate(d))}</h2></div><button class="circle-btn" data-close>×</button></div><div class="day-stats"><div><small>Доход</small><b>${money(t.income)}</b></div><div><small>Расход</small><b>− ${money(t.expenses)}</b></div><div><small>Чистыми</small><b>${money(t.net)}</b></div></div><div class="day-actions"><button id="dayAdd">＋ Выезд</button><button id="dayExpense">− Расход</button><button id="dayNote">＋ Заметка</button></div><h3 class="sheet-section">План</h3>${['1','2','3'].map(s=>{const j=pending.find(x=>x.type==='Монтаж'&&String(x.slot)===s);return`<div class="slot"><div class="slot-title">${SLOTS[s]}</div>${j?jobCard(j,{compact:true}):`<button class="free-slot" data-slot="${s}">＋ Свободное окно</button>`}</div>`}).join('')}${pending.filter(j=>j.type!=='Монтаж').length?`<h3 class="sheet-section">Другие выезды</h3>${pending.filter(j=>j.type!=='Монтаж').map(j=>jobCard(j,{compact:true})).join('')}`:''}${done.length?`<h3 class="sheet-section">История</h3>${done.map(j=>jobCard(j,{compact:true})).join('')}`:''}${t.unpaid?`<button class="debt-banner" data-open-debts="1">💰 Не оплачено: ${money(t.unpaid)} · открыть долги</button>`:''}<button class="archive-day" id="archiveDay">Открыть полный день →</button></div>`;document.body.append(m);m.querySelector('.backdrop').onclick=()=>m.remove();m.querySelector('[data-close]').onclick=()=>m.remove();m.querySelector('#dayAdd').onclick=()=>{m.remove();openJob(null,d,freeSlot(d),'Монтаж')};m.querySelector('#dayExpense').onclick=()=>{m.remove();openExpense(d)};m.querySelector('#dayNote').onclick=()=>{m.remove();openNote()};m.querySelector('#archiveDay').onclick=()=>showDayArchive(d);m.querySelectorAll('.free-slot').forEach(b=>b.onclick=()=>{m.remove();openJob(null,d,b.dataset.slot,'Монтаж')});m.querySelectorAll('.edit').forEach(b=>b.onclick=()=>{m.remove();openJob(b.dataset.id)});bindQuickActions(m);}
function showDayArchive(d){const t=dateTotals(d),jobs=jobsForDate(d),expenses=state.expenses.filter(e=>!e.cancelled&&e.date===d),m=document.createElement('div');m.className='modal open';m.innerHTML=`<div class="backdrop"></div><div class="sheet"><div class="sheet-head"><div><div class="eyebrow">История</div><h2>${esc(fmtDate(d))}</h2></div><button class="circle-btn" data-close>×</button></div><div class="day-stats"><div><small>Доход</small><b>${money(t.income)}</b></div><div><small>Расход</small><b>− ${money(t.expenses)}</b></div><div><small>Чистыми</small><b>${money(t.net)}</b></div></div><h3 class="sheet-section">Выезды</h3>${jobs.length?jobs.map(j=>jobCard(j,{compact:true})).join(''):'<div class="muted">Нет выездов</div>'}<h3 class="sheet-section">Расходы</h3>${expenses.length?expenses.map(e=>`<div class="expense-row"><div><b>${esc(e.category)}</b><small>${esc(e.comment||'')}</small></div><strong>− ${money(e.amount)}</strong><button class="mini-edit" data-expense="${esc(e.id)}">Изм.</button></div>`).join(''):'<div class="muted">Нет расходов</div>'}<button class="primary wide" id="archiveAddExpense">＋ Расход за ${esc(fmtShort(d))}</button></div>`;document.body.append(m);m.querySelector('.backdrop').onclick=()=>m.remove();m.querySelector('[data-close]').onclick=()=>m.remove();m.querySelector('#archiveAddExpense').onclick=()=>{m.remove();openExpense(d)};m.querySelectorAll('.mini-edit').forEach(b=>{const e=state.expenses.find(x=>x.id===b.dataset.expense);b.onclick=()=>{m.remove();openExpense(e?.date,e)}});m.querySelectorAll('.edit').forEach(b=>b.onclick=()=>{m.remove();openJob(b.dataset.id)});}
function updateJob(id,patch){return saveShared(cur=>({...cur,jobs:cur.jobs.map(j=>j.id===id?{...j,...patch}:j)}));}
function openJob(id=null,d=today(),slot=freeSlot(d),type='Монтаж',preset=null){const j=id?state.jobs.find(x=>x.id===id):null;editingType=j?.type||type;$('#modalTitle').textContent=j?'Изменить выезд':'Новый выезд';$('#jobId').value=j?.id||'';$('#jobDate').value=j?.date||d;$('#jobSlot').value=j?.slot||slot;$('#jobTime').value=j?.time||'';$('#jobClient').value=j?.client||preset?.client||'';$('#jobPhone').value=j?.phone||preset?.phone||'';$('#jobPrice').value=j?.price??(preset?.price??'');$('#jobAddress').value=j?.address||preset?.address||'';$('#jobStore').value=j?.store||preset?.store||'';$('#jobStatus').value=j?.status||(type==='Доп. доход'?'Выполнен':'Запланирован');$('#jobCompletedDate').value=j?.completedDate||j?.date||d;$('#jobPaid').value=j?.paid===false?'no':'yes';$('#jobComment').value=j?.comment||preset?.comment||'';$('#measurePrice').value=j?.measurePrice??'';$('#measurePaid').checked=j?.measurePaid===true||j?.paid===true&&isMeasure(j);$('#measureCredit').value=j?.measureCredit??preset?.measureCredit??'';$('#measureLink').value=j?.convertedToJobId||'';$('#measureLink').dataset.sourceMeasure=preset?.measureId||j?.convertedFromMeasureId||'';$$('#typeTabs button').forEach(b=>b.classList.toggle('selected',b.dataset.type===editingType));updateJobForm();modal('jobModal',true);}
function updateJobForm(){const measure=editingType==='Замер',done=$('#jobStatus').value==='Выполнен';$('#slotWrap').classList.toggle('hidden',measure);$('#timeWrap').classList.toggle('hidden',!measure);$('#priceWrap').classList.toggle('hidden',measure);$('#measureWrap').classList.toggle('hidden',!measure);$('#completedDateWrap').style.display=done?'grid':'none';$('#deleteBtn').style.display=$('#jobId').value?'block':'none';$('#convertMeasureBtn').style.display=measure&&$('#jobId').value&&!$('#measureLink').value?'block':'none';}
function checkSlot(){const d=$('#jobDate').value,s=$('#jobSlot').value,id=$('#jobId').value,conflict=null;const w=$('#slotWarning');w.classList.toggle('hidden',!conflict);if(conflict)w.textContent=`Слот занят: ${conflict.client}.`}
async function saveJob(e){e.preventDefault();if(!serverReady)return toast('Нет соединения с общей базой.','error');const id=$('#jobId').value||uid(),d=$('#jobDate').value,client=$('#jobClient').value.trim();if(!d||!client)return toast('Укажите дату и клиента','error');if(editingType==='Монтаж'){const conflict=null;if(conflict)return toast(`Слот занят: ${conflict.client}`,'error')}const job={id,date:d,slot:$('#jobSlot').value,time:$('#jobTime').value,type:editingType,client,phone:$('#jobPhone').value.trim(),price:editingType==='Замер'?0:num($('#jobPrice').value),measurePrice:editingType==='Замер'?num($('#measurePrice').value):0,measurePaid:editingType==='Замер'&&$('#measurePaid').checked,measureCredit:editingType==='Замер'?0:num($('#measureCredit').value),convertedToJobId:$('#measureLink').value.trim(),convertedFromMeasureId:$('#measureLink').dataset.sourceMeasure||'',address:$('#jobAddress').value.trim(),store:$('#jobStore').value.trim(),status:$('#jobStatus').value,completedDate:$('#jobStatus').value==='Выполнен'?($('#jobCompletedDate').value||d):'',paid:editingType==='Замер'?$('#measurePaid').checked:$('#jobPaid').value!=='no',comment:$('#jobComment').value.trim(),source:$('#jobStore').value.trim()};try{await saveShared(cur=>{const jobs=[...cur.jobs],i=jobs.findIndex(x=>x.id===id);i<0?jobs.push(job):jobs[i]={...jobs[i],...job};const sourceId=job.convertedFromMeasureId;if(sourceId){const source=jobs.find(x=>x.id===sourceId);if(source)source.convertedToJobId=id;}return{...cur,jobs}});modal('jobModal',false);toast('Сохранено','success')}catch(err){console.error(err);toast('Не удалось сохранить','error')}}
async function deleteJob(){const id=$('#jobId').value;if(!id)return;const j=state.jobs.find(x=>x.id===id);if(!j)return;if(!confirm('Убрать запись в архив? Данные не будут потеряны.'))return;try{await updateJob(id,{status:'Отменён',cancelledAt:new Date().toISOString()});modal('jobModal',false);toast('Запись сохранена в истории','success')}catch(e){toast('Не удалось изменить запись','error')}}
function convertMeasure(){const id=$('#jobId').value,j=state.jobs.find(x=>x.id===id);if(!j||!isMeasure(j))return;const credit=j.measurePaid?num(j.measurePrice):0;modal('jobModal',false);openJob(null,today(),freeSlot(today()),'Монтаж',{client:j.client,phone:j.phone,address:j.address,store:j.store,comment:j.comment,measureCredit:credit,measureId:j.id});}
function openExpense(d=today(),existing=null){const m=document.createElement('div');m.className='modal open';m.innerHTML=`<div class="backdrop"></div><div class="sheet"><div class="handle"></div><div class="sheet-head"><div><div class="eyebrow">Финансы</div><h2>${existing?'Изменить расход':'Новый расход'}</h2></div><button class="circle-btn" data-close>×</button></div><form id="expenseForm"><div class="form-row"><label>Дата<input id="eDate" type="date" required value="${esc(existing?.date||d)}"></label><label>Сумма<input id="eAmount" type="number" min="0.01" step="0.01" inputmode="decimal" required value="${existing?.amount??''}"></label></div><label>Категория<select id="eCat"><option ${existing?.category==='Топливо'?'selected':''}>Топливо</option><option ${existing?.category==='Парковка'?'selected':''}>Парковка</option><option ${existing?.category==='Материалы'?'selected':''}>Материалы</option><option ${existing?.category==='Инструмент'?'selected':''}>Инструмент</option><option ${existing?.category==='Аренда'?'selected':''}>Аренда</option><option ${existing?.category==='Другое'?'selected':''}>Другое</option></select></label><label>Комментарий<textarea id="eComment" rows="3" placeholder="Что оплатили?">${esc(existing?.comment||'')}</textarea></label><button class="primary wide" type="submit">${existing?'Сохранить изменения':'Сохранить расход'}</button>${existing?'<button class="danger ghost wide" type="button" id="cancelExpense">Списать в архив</button>':''}</form></div>`;document.body.append(m);m.querySelector('.backdrop').onclick=()=>m.remove();m.querySelector('[data-close]').onclick=()=>m.remove();$('#expenseForm',m).onsubmit=async e=>{e.preventDefault();const amount=num($('#eAmount',m).value),date=$('#eDate',m).value;if(!(amount>0)||!date)return toast('Укажите дату и сумму','error');try{await saveShared(cur=>{const expenses=[...cur.expenses],item={...(existing||{}),id:existing?.id||uid(),date,amount,category:$('#eCat',m).value,comment:$('#eComment',m).value.trim(),cancelled:false};const i=expenses.findIndex(x=>x.id===item.id);i>=0?expenses[i]=item:expenses.push(item);return{...cur,expenses}});m.remove();toast('Расход сохранён','success')}catch(err){toast('Не удалось сохранить расход','error')}};$('#cancelExpense',m)?.addEventListener('click',async()=>{if(!confirm('Скрыть расход из расчётов? История сохранится.'))return;try{await saveShared(cur=>({...cur,expenses:cur.expenses.map(e=>e.id===existing.id?{...e,cancelled:true}:e)}));m.remove();toast('Расход отправлен в архив','success')}catch(e){toast('Не удалось изменить расход','error')}})}
function renderMoney(){const t=totals('day'),w=totals('week'),m=totals('month'),a=totals('all'),current=totals(financePeriod);$('#moneyTotal').textContent=money(current.net);$('#moneyPeriod').textContent={day:'Сегодня',week:'Эта неделя',month:'Этот месяц',all:'Всё время'}[financePeriod];$('#moneyGrid').innerHTML=`<div><small>Доход</small><b>${money(current.income)}</b></div><div><small>Расходы</small><b>${money(current.expenses)}</b></div><div><small>Чистыми</small><b>${money(current.net)}</b></div><button class="money-debt" data-open-debts="1"><small>Не оплачено</small><b>${money(current.unpaid)}</b><span>Открыть долги →</span></button>`;$('#moneyHighlights').innerHTML=`<button data-fin="day"><span>День</span><b>${money(t.net)}</b></button><button data-fin="week"><span>Неделя</span><b>${money(w.net)}</b></button><button data-fin="month"><span>Месяц</span><b>${money(m.net)}</b></button><button data-fin="all"><span>Всё</span><b>${money(a.net)}</b></button>`;$$('#moneyHighlights button').forEach(b=>b.onclick=()=>{financePeriod=b.dataset.fin;renderMoney()});const by={};state.jobs.filter(j=>!isCancelled(j)&&isDone(j)).forEach(j=>{const k=j.store||'Без источника';by[k]=(by[k]||0)+effectiveIncome(j)});$('#storeBreakdown').innerHTML=Object.entries(by).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="store-row"><span>${esc(k)}</span><b>${money(v)}</b></div>`).join('')||'<div class="muted">Доходов пока нет</div>';const debts=state.jobs.filter(j=>!isCancelled(j)&&isDone(j)&&j.paid===false);$('#debtList').innerHTML=debts.sort((a,b)=>activityDate(b).localeCompare(activityDate(a))).map(j=>`<button class="debt-row" data-debt-id="${esc(j.id)}"><div><b>${esc(j.client)}</b><small>${fmtShort(activityDate(j))} · ${esc(j.type)}</small></div><strong>${money(effectiveIncome(j))}</strong>›</button>`).join('')||'<div class="muted">Долгов нет — красота.</div>';$('#expenseArchive').innerHTML=state.expenses.filter(e=>!e.cancelled).slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,40).map(e=>`<div class="expense-row"><div><b>${esc(e.category)}</b><small>${fmtShort(e.date)}${e.comment?' · '+esc(e.comment):''}</small></div><strong>− ${money(e.amount)}</strong><button class="mini-edit" data-expense="${esc(e.id)}">Изм.</button></div>`).join('')||'<div class="muted">Расходов пока нет</div>';$$('.mini-edit').forEach(b=>{const e=state.expenses.find(x=>x.id===b.dataset.expense);b.onclick=()=>e&&openExpense(e.date,e)});bindDebtRows();}
function bindDebtRows(){$$('.debt-row').forEach(b=>b.onclick=()=>openJob(b.dataset.debtId));} function openDebts(){document.querySelector('[data-screen="moneyScreen"]')?.click();setTimeout(()=>$('#debtList')?.scrollIntoView({behavior:'smooth',block:'start'}),80);}
function renderClients(){const q=($('#clientSearch').value||'').toLowerCase(),map=new Map();state.jobs.filter(j=>!isCancelled(j)).forEach(j=>{const hay=`${j.client} ${j.phone||''} ${j.address||''}`.toLowerCase();if(q&&!hay.includes(q))return;const key=j.phone||j.client;if(key&&!map.has(key))map.set(key,j)});$('#clientsList').innerHTML=[...map.values()].sort((a,b)=>activityDate(b).localeCompare(activityDate(a))).map(j=>`<article class="client-card"><div><div class="job-client">${esc(j.client)}</div><div class="job-meta">${esc(j.phone||'Телефон не указан')}</div>${j.address?`<small>${esc(j.address)}</small>`:''}</div><div class="client-actions">${callLink(j.phone)}<button class="action-chip edit" data-id="${esc(j.id)}">Открыть</button></div></article>`).join('')||'<div class="empty-card"><strong>Клиенты появятся здесь</strong><span>После первого выезда база начнёт собираться автоматически</span></div>';bindCards();}
function renderNotes(){const active=$('#activeNotes'),archive=$('#archivedNotes');if(!active||!archive)return;const a=notes.filter(n=>n.archived!==true),ar=notes.filter(n=>n.archived===true);active.innerHTML=a.length?a.map(noteCard).join(''):'<div class="muted">Активных заметок нет</div>';archive.innerHTML=ar.length?ar.map(noteCard).join(''):'<div class="muted">Архив пуст</div>';bindNotes();}
function noteCard(n){return`<div class="note-card ${n.archived?'archived':''}"><div class="note-top"><b>${esc(n.title||'Заметка')}</b><div><button class="mini-btn" data-note-edit="${esc(n.id)}">Изм.</button>${n.archived?`<button class="mini-btn" data-note-restore="${esc(n.id)}">Вернуть</button>`:`<button class="mini-btn" data-note-archive="${esc(n.id)}">Архив</button>`}</div></div><p>${esc(n.text||'')}</p></div>`;}
function bindNotes(){$$('.mini-btn').forEach(b=>{b.onclick=()=>{const id=b.dataset.noteEdit||b.dataset.noteArchive||b.dataset.noteRestore,n=notes.find(x=>x.id===id);if(!n)return;if(b.dataset.noteEdit)openNote(n);else setNoteState(id,!!b.dataset.noteArchive)}});}
function openNote(n=null){const m=document.createElement('div');m.className='modal open';m.innerHTML=`<div class="backdrop"></div><div class="sheet"><div class="sheet-head"><div><div class="eyebrow">Общие заметки</div><h2>${n?'Изменить заметку':'Новая заметка'}</h2></div><button class="circle-btn" data-close>×</button></div><form id="noteForm"><label>Заголовок<input id="nTitle" required value="${esc(n?.title||'')}"></label><label>Текст<textarea id="nText" rows="5" required>${esc(n?.text||'')}</textarea></label><button class="primary wide" type="submit">Сохранить</button></form></div>`;document.body.append(m);m.querySelector('.backdrop').onclick=()=>m.remove();m.querySelector('[data-close]').onclick=()=>m.remove();$('#noteForm',m).onsubmit=async e=>{e.preventDefault();const item={id:n?.id||uid(),title:$('#nTitle',m).value.trim(),text:$('#nText',m).value.trim(),archived:n?.archived===true,updatedAt:new Date().toISOString()};if(!item.title||!item.text)return;try{await saveNotes(cur=>({...cur,notes:[...(cur.notes||[]).filter(x=>x.id!==item.id),item]}));m.remove();toast('Заметка сохранена','success')}catch(err){toast('Не удалось сохранить заметку','error')}};}
async function setNoteState(id,archived){try{await saveNotes(cur=>({...cur,notes:(cur.notes||[]).map(n=>n.id===id?{...n,archived,updatedAt:new Date().toISOString()}:n)}));toast(archived?'В архив':'Вернули заметку','success')}catch(e){toast('Не удалось изменить заметку','error')}}
function bindCards(root=document){$$('.edit',root).forEach(b=>b.onclick=()=>openJob(b.dataset.id));$$('.share-address',root).forEach(b=>b.onclick=async()=>{const j=state.jobs.find(x=>x.id===b.dataset.id);if(!j?.address)return;const text=`Адрес: ${j.address}`;try{if(navigator.share)await navigator.share({text});else await navigator.clipboard?.writeText(text);toast(navigator.share?'Отправлено':'Адрес скопирован','success')}catch(e){if(e.name!=='AbortError')toast('Не удалось отправить адрес','error')}});bindQuickActions(root);$$('[data-open-debts]',root).forEach(b=>b.onclick=openDebts);$$('.upcoming',root).forEach(b=>b.onclick=()=>openDay(b.dataset.date));}
function bindQuickActions(root=document){$$('[data-quick]',root).forEach(b=>b.onclick=async()=>{const id=b.dataset.id,j=state.jobs.find(x=>x.id===id);if(!j)return;try{if(b.dataset.quick==='route')await updateJob(id,{status:'В пути'});if(b.dataset.quick==='done')await updateJob(id,{status:'Выполнен',completedDate:today()});if(b.dataset.quick==='paid')await updateJob(id,{paid:true});toast('Готово','success')}catch(e){toast('Не удалось обновить','error')}});}
function render(){if(!$('#app'))return;renderToday();renderCalendar();renderMoney();renderClients();renderNotes();renderExpensesToday();}
function applyTheme(theme){document.body.classList.toggle('dark',theme==='dark');document.documentElement.dataset.theme=theme;document.querySelector('meta[name="theme-color"]')?.setAttribute('content',theme==='dark'?'#111827':'#f5f7fb');const b=$('#themeBtn');if(b)b.textContent=theme==='dark'?'☀':'☾';try{localStorage.setItem('montaji-theme',theme)}catch(e){}}
function bindUI(){applyTheme((()=>{try{return localStorage.getItem('montaji-theme')}catch(e){return null}})()||'light');$('#themeBtn').onclick=()=>applyTheme(document.body.classList.contains('dark')?'light':'dark');$('#addBtn').onclick=()=>openAddMenu();$('#todayIncomeBtn').onclick=()=>openJob(null,today(),freeSlot(today()),'Доп. доход');$('#todayExpenseBtn').onclick=()=>openExpense();$('#todayExpenseBtn2').onclick=()=>openExpense();$('#todayNoteBtn').onclick=()=>openNote();$('#financeExpenseBtn').onclick=()=>openExpense();$('#exportExcelBtn').onclick=exportExcel;$('#exportExcelBtn2').onclick=exportExcel;$('#backupBtn').onclick=exportJson;$('#restoreInput').onchange=e=>{const f=e.target.files?.[0];if(f)restoreJson(f);e.target.value=''};$('#prevMonth').onclick=()=>{month.setMonth(month.getMonth()-1);renderCalendar()};$('#nextMonth').onclick=()=>{month.setMonth(month.getMonth()+1);renderCalendar()};$$('.nav').forEach(b=>b.onclick=()=>{$$('.screen').forEach(s=>s.classList.toggle('active',s.id===b.dataset.screen));$$('.nav').forEach(n=>n.classList.toggle('active',n===b));window.scrollTo(0,0)});$('#clientSearch').oninput=renderClients;$('#jobForm').onsubmit=saveJob;$('#deleteBtn').onclick=deleteJob;$('#jobStatus').onchange=()=>{updateJobForm();checkSlot()};$('#jobDate').onchange=checkSlot;$('#jobSlot').onchange=checkSlot;$$('#typeTabs button').forEach(b=>b.onclick=()=>{editingType=b.dataset.type;$$('#typeTabs button').forEach(x=>x.classList.toggle('selected',x===b));updateJobForm();checkSlot()});$$('[data-close="jobModal"]').forEach(b=>b.onclick=()=>modal('jobModal',false));$('#logoutBtn').onclick=()=>F.authMod.signOut(auth);$('#convertMeasureBtn').onclick=convertMeasure;addEventListener('online',async()=>{online=true;if(user&&await loadServer())startRealtime()});addEventListener('offline',()=>{online=false;serverReady=false;state=emptyState();notes=[];render();status('Нет интернета · серверные данные скрыты','offline')});}
function openAddMenu(){const m=document.createElement('div');m.className='modal open';m.innerHTML=`<div class="backdrop"></div><div class="sheet"><div class="sheet-head"><div><div class="eyebrow">Быстро</div><h2>Что добавить?</h2></div><button class="circle-btn" data-close>×</button></div><div class="add-grid">${[['Монтаж','🛠'],['Замер','⌖'],['Рекламация','↺'],['Доставка','▣'],['Расход','−'],['Заметка','✦']].map(([t,i])=>`<button data-add-type="${t}"><span>${i}</span><b>${t}</b></button>`).join('')}</div></div>`;document.body.append(m);m.querySelector('.backdrop').onclick=()=>m.remove();m.querySelector('[data-close]').onclick=()=>m.remove();m.querySelectorAll('[data-add-type]').forEach(b=>b.onclick=()=>{const t=b.dataset.addType;m.remove();if(t==='Расход')openExpense();else if(t==='Заметка')openNote();else openJob(null,today(),freeSlot(today()),t)});}
function exportExcel(){const rows=[['Тип','Дата','Дата выполнения','Время/слот','Клиент','Телефон','Сумма','Статус','Оплата','Источник','Адрес','Комментарий','Зачёт замера']];state.jobs.slice().sort((a,b)=>activityDate(a).localeCompare(activityDate(b))).forEach(j=>rows.push([j.type,j.date,j.completedDate||'',isMeasure(j)?(j.time||SLOTS[j.slot]||''):SLOTS[j.slot]||'',j.client,j.phone||'',effectiveIncome(j),j.status,j.paid?'Оплачено':'Долг',j.store||'',j.address||'',j.comment||'',j.measureCredit||'']));state.expenses.filter(e=>!e.cancelled).forEach(e=>rows.push(['Расход',e.date,'','','','',-e.amount,'','','',e.category,e.comment||'','']));const csv='\uFEFF'+rows.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(';')).join('\r\n');downloadFile(csv,`montaji-aa-${today()}.csv`,'text/csv;charset=utf-8');toast('Excel-файл сформирован','success');}
function exportJson(){downloadFile(JSON.stringify({data:state,notes},null,2),`montaji-aa-backup-${today()}.json`,'application/json');toast('Резервная копия сохранена','success');} function downloadFile(text,name,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([text],{type}));a.href=url;a.download=name;document.body.append(a);a.click();setTimeout(()=>{URL.revokeObjectURL(url);a.remove()},1000)}
async function restoreJson(file){try{const parsed=JSON.parse(await file.text()),data=normalize(parsed?.data||parsed);if(!confirm('Заменить общую базу этой резервной копией? Это действие нельзя отменить.'))return;await saveShared(()=>data);if(Array.isArray(parsed?.notes))await saveNotes(()=>({notes:parsed.notes}));toast('База восстановлена','success')}catch(e){toast('Не удалось восстановить файл','error')}}
async function onUser(u){user=u;unsubscribeShared?.();unsubscribeNotes?.();unsubscribeShared=unsubscribeNotes=null;if(!u){serverReady=false;state=emptyState();notes=[];showAuth(true);render();status('Требуется вход');return}if(!u.emailVerified){await F.authMod.signOut(auth);showAuth(true);authMessage('Подтвердите email по ссылке из письма.',true);return}showAuth(false);if(await loadServer())startRealtime();}
(async()=>{try{bindUI();bindAuth();await initFirebase();F.authMod.onAuthStateChanged(auth,onUser)}catch(e){console.error(e);showAuth(true);authMessage('Не удалось запустить приложение. Проверьте Firebase.',true)}})();
