import { firebaseConfig } from './firebase-config.js';
import { canPlace, jobsFor, montageCount, totals, montageTotals, SLOT_LABELS, SLOTS } from './core.js';

const KEY='astera-v3-data';
const THEME='astera-theme';
const today=new Date();
const fmtDate=d=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`};
const money=n=>new Intl.NumberFormat('ru-RU').format(Math.round(Number(n)||0))+' ₽';
const dayName=d=>new Intl.DateTimeFormat('ru-RU',{weekday:'short'}).format(new Date(d)).replace('.','');
const fullDate=d=>new Intl.DateTimeFormat('ru-RU',{weekday:'long',day:'numeric',month:'long'}).format(new Date(d));
const uid=()=>crypto.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2);
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const seed=[
{id:uid(),date:'2026-08-10',slot:'1',type:'Монтаж',client:'ООО «МАРИМАР»',phone:'',address:'пос. Малое Исаково, ул. Коммунальная, 16Б',store:'LAVETRA DOORS',price:0,status:'Запланирован',comment:'СТР Термо Пластик 960, правая. Есть доборы. Клиент демонтирует сам. Предложить ПСУЛ. Заказ от июня'},
{id:uid(),date:'2026-08-10',slot:'2',type:'Сервис',client:'Старый клиент',phone:'',address:'Зеленоградск',store:'',price:6500,status:'Подтверждён',comment:'Замена замка на биометрию. + замер двери в подвал. Контакты в Telegram'},
{id:uid(),date:'2026-08-12',slot:'1',type:'Монтаж',client:'Королева Марина Егоровна',phone:'8 909 788-29-64',address:'Калининград, ул. Дзержинского, д. 116, кв. 1',store:'',price:0,status:'Подтверждён',comment:'Гарда с зеркалом 960, правая. Замер выполнен 10.08. Хрущёвка, проём около 96 см. Верхний наличник вероятно под отпил. +500 ₽ за выезд в счёт будущих работ'},
{id:uid(),date:'2026-08-12',slot:'2',type:'Монтаж',client:'Катя / база дверей',phone:'',address:'',store:'',price:8000,status:'Подтверждён',comment:'Дверь + доборы. +500 ₽ за выезд в счёт будущих работ'},
{id:uid(),date:'2026-08-13',slot:'1',type:'Монтаж',client:'Ильина Татьяна Петровна',phone:'',address:'г. Гурьевск, ул. Солнечная, 17',store:'LAVETRA DOORS',price:10500,status:'Запланирован',comment:'ВИНТЕР ПАНОРАМА ПРО 980, правая. 10 000 ₽ монтаж + 500 ₽ доставка. Дверь с витрины Ялта'},
{id:uid(),date:'2026-08-13',slot:'2',type:'Монтаж',client:'Алексей',phone:'8 911 450-96-1',address:'ул. Борзова, 100',store:'ASTERA',price:0,status:'Запланирован',comment:'Эссен 960, левое открывание'}
];
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if(x?.jobs)return x}catch{}return {jobs:seed,expenses:{}}}
let state=load(); let month=new Date(today.getFullYear(),today.getMonth(),1); let period='month'; let editingType='Монтаж';
function save(){localStorage.setItem(KEY,JSON.stringify(state));renderAll()}
function isToday(d){return d===fmtDate(today)}
function renderAll(){renderTop();renderToday();renderCalendar();renderMoney();renderClients()}
function renderTop(){$('#topDate').textContent=fullDate(today)}
function card(j){const tel=(j.phone||'').replace(/[^\d+]/g,'');const maps=j.address?`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(j.address)}`:'';return `<article class="job-card" data-id="${esc(j.id)}"><div class="job-card__top"><div><div class="job-card__client">${esc(j.client)}</div><div class="job-card__meta">${SLOT_LABELS[j.slot]} · ${esc(j.type)}${j.store?' · '+esc(j.store):''}</div></div><span class="pill">${money(j.price)}</span></div><div class="job-card__details">${j.address?`<div>📍 ${esc(j.address)}</div>`:''}${j.comment?`<div>◦ ${esc(j.comment)}</div>`:''}</div><div class="job-card__actions">${maps?`<a class="action-link" href="${maps}" target="_blank" rel="noopener">Маршрут</a>`:''}${tel?`<a class="action-link" href="tel:${tel}">Позвонить</a>`:''}<button class="action-link edit" data-id="${esc(j.id)}">Открыть</button></div></article>`}
function renderToday(){const ds=fmtDate(today),jobs=jobsFor(state.jobs,ds),mont=montageCount(state.jobs,ds),income=jobs.reduce((s,j)=>s+Number(j.price||0),0);$('#todayIncome').textContent=money(income);$('#todayLoad').textContent=`${mont}/3 монтажей`;$(`#todayProgress`).style.width=Math.min(100,mont/3*100)+'%';$('#todayList').innerHTML=jobs.length?jobs.map(card).join(''):`<div class="job-card"><div class="job-card__client">На сегодня ничего не запланировано</div><div class="job-card__meta">Можно спокойно добавить выезд.</div></div>`;bindCards();const upcoming=[];for(let i=1;i<=7;i++){const d=new Date(today);d.setDate(d.getDate()+i);const key=fmtDate(d),js=jobsFor(state.jobs,key);if(js.length)upcoming.push({d,key,js})}$('#upcomingList').innerHTML=upcoming.slice(0,5).map(x=>`<button class="upcoming-card" data-date="${x.key}"><div class="upcoming-date"><b>${x.d.getDate()}</b><span>${dayName(x.d)}</span></div><div class="upcoming-main"><b>${esc(x.js[0].client)}${x.js.length>1?' + '+(x.js.length-1):''}</b><span>${montageCount(state.jobs,x.key)}/3 монтажей · ${money(x.js.reduce((s,j)=>s+Number(j.price||0),0))}</span></div><span class="load-badge">›</span></button>`).join('')||'<div class="muted">Ближайшие дни свободны.</div>';$$('.upcoming-card').forEach(b=>b.onclick=()=>openDay(b.dataset.date))}
function bindCards(){$$('.edit').forEach(b=>b.onclick=e=>openJob(e.currentTarget.dataset.id))}
function renderCalendar(){const y=month.getFullYear(),m=month.getMonth(),first=new Date(y,m,1),start=(first.getDay()+6)%7,days=new Date(y,m+1,0).getDate();$('#scheduleMonth').textContent=new Intl.DateTimeFormat('ru-RU',{month:'long',year:'numeric'}).format(month);let html='';for(let i=0;i<start;i++)html+='<div class="day muted"></div>';for(let n=1;n<=days;n++){const d=new Date(y,m,n),key=fmtDate(d),js=jobsFor(state.jobs,key),c=montageCount(state.jobs,key),cls=c>=3?'full':c===2?'busy':c?'partial':'';html+=`<button class="day ${cls} ${isToday(key)?'today':''}" data-date="${key}"><span class="num">${n}</span><div class="bars">${SLOTS.map(s=>`<i class="bar ${js.some(j=>j.slot===s)?'on':''}"></i>`).join('')}</div><span class="count">${c}/3</span></button>`}$('#calendar').innerHTML=html;$$('.day[data-date]').forEach(b=>b.onclick=()=>openDay(b.dataset.date))}
function openDay(date){const js=jobsFor(state.jobs,date),title=fullDate(date);let html='';for(const slot of SLOTS){const j=js.find(x=>x.slot===slot);html+=`<div class="slot-block"><div class="slot-block__head"><h3>${SLOT_LABELS[slot]}</h3>${slot==='3'?'<span class="muted">резерв</span>':''}</div>${j?card(j):`<button class="slot-empty" data-add-slot="${slot}">Свободно · добавить</button>`}</div>`}const old=$('#daySheet');if(old)old.remove();const modal=document.createElement('div');modal.className='modal open';modal.id='daySheet';modal.innerHTML=`<div class="backdrop" data-close="daySheet"></div><div class="sheet"><div class="handle"></div><div class="sheet-head"><div><div class="eyebrow">Расписание</div><h2>${title}</h2></div><button class="circle-btn" data-close="daySheet">×</button></div><div class="section-head"><h2>Выезды</h2><button class="text-btn" id="dayAdd">+ выезд</button></div>${html}<div class="chart-card"><div class="section-head"><h2>Итог</h2></div><div class="money-grid"><div class="metric"><span>Монтажей</span><b>${montageCount(state.jobs,date)}/3</b></div><div class="metric"><span>Сумма</span><b>${money(js.reduce((s,j)=>s+Number(j.price||0),0))}</b></div></div></div></div>`;document.body.append(modal);modal.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>modal.remove());modal.querySelector('#dayAdd').onclick=()=>{modal.remove();openJob(null,date,firstFreeSlot(date))};modal.querySelectorAll('[data-add-slot]').forEach(x=>x.onclick=()=>{modal.remove();openJob(null,date,x.dataset.addSlot)});modal.querySelectorAll('.edit').forEach(x=>x.onclick=()=>{modal.remove();openJob(x.dataset.id)})}
function firstFreeSlot(date){const used=new Set(jobsFor(state.jobs,date).map(j=>j.slot));return SLOTS.find(s=>!used.has(s))||'3'}
function renderMoney(){const jobs=state.jobs.filter(j=>j.status!=='Отменён'&&Number(j.price||0)>0);let start,end,label;if(period==='day'){start=end=fmtDate(today);label='сегодня'}else if(period==='week'){const d=new Date(today),dow=(d.getDay()+6)%7;d.setDate(d.getDate()-dow);start=fmtDate(d);d.setDate(d.getDate()+6);end=fmtDate(d);label='эта неделя'}else if(period==='month'){start=fmtDate(new Date(today.getFullYear(),today.getMonth(),1));end=fmtDate(new Date(today.getFullYear(),today.getMonth()+1,0));label=new Intl.DateTimeFormat('ru-RU',{month:'long',year:'numeric'}).format(today)}else{start='0000-01-01';end='9999-12-31';label='за всё время'}const filtered=jobs.filter(j=>j.date>=start&&j.date<=end),total=filtered.reduce((s,j)=>s+Number(j.price||0),0),expenses=Object.entries(state.expenses||{}).filter(([d])=>d>=start&&d<=end).reduce((s,[,x])=>s+Number(x.amount||0),0),montages=montageTotals(state.jobs,start,end);$('#moneyTotal').textContent=money(total);$('#moneySub').textContent=label;$('#moneyGrid').innerHTML=`<div class="metric"><span>Монтажей</span><b>${montages}</b></div><div class="metric"><span>Средний</span><b>${money(montages?total/montages:0)}</b></div><div class="metric"><span>Расходы</span><b>${money(expenses)}</b></div><div class="metric"><span>Чистыми</span><b>${money(total-expenses)}</b></div>`;renderChart(filtered,start,end);renderStores(filtered)}
function renderChart(jobs,start){const map={};jobs.forEach(j=>map[j.date]=(map[j.date]||0)+Number(j.price||0));let keys=[];if(period==='day')keys=[start];else if(period==='week'){let d=new Date(start);for(let i=0;i<7;i++){keys.push(fmtDate(d));d.setDate(d.getDate()+1)}}else if(period==='month'){for(let i=1;i<=31;i++){const d=new Date(today.getFullYear(),today.getMonth(),i);if(d.getMonth()===today.getMonth())keys.push(fmtDate(d))}}else keys=Object.keys(map).sort().slice(-30);const vals=keys.map(k=>map[k]||0),max=Math.max(...vals,1);$('#chart').innerHTML=keys.map((k,i)=>`<div class="chart-col"><i class="chart-bar" style="height:${Math.max(3,vals[i]/max*125)}px"></i><small>${new Date(k).getDate()}</small></div>`).join('')||'<span class="muted">Пока нет данных.</span>';$('#chartCaption').textContent=jobs.length?money(jobs.reduce((s,j)=>s+Number(j.price||0),0)):'нет данных'}
function renderStores(jobs){const map={};jobs.forEach(j=>{const k=j.store||'Без магазина';map[k]=(map[k]||0)+Number(j.price||0)});const arr=Object.entries(map).sort((a,b)=>b[1]-a[1]),max=arr[0]?.[1]||1;$('#storeBreakdown').innerHTML=arr.length?arr.map(([k,v])=>`<div class="store-row"><b>${esc(k)}</b><div class="line"><span style="width:${v/max*100}%"></span></div><span>${money(v)}</span></div>`).join(''):'<div class="muted">Нет данных за период.</div>'}
function renderClients(){const q=($('#clientSearch')?.value||'').toLowerCase();const map=new Map();state.jobs.forEach(j=>{const k=(j.client||'').trim();if(!k)return;const old=map.get(k)||{client:k,phone:j.phone,address:j.address,count:0,last:j.date};old.count++;if(j.date>old.last){old.last=j.date;old.phone=j.phone||old.phone;old.address=j.address||old.address}map.set(k,old)});const arr=[...map.values()].filter(x=>`${x.client} ${x.phone||''} ${x.address||''}`.toLowerCase().includes(q)).sort((a,b)=>b.last.localeCompare(a.last));$('#clientsList').innerHTML=arr.map(x=>`<article class="client-card"><b>${esc(x.client)}</b><p>${x.phone||'Телефон не указан'} · ${x.count} выезд(а)</p><p>${esc(x.address||'Адрес не указан')}</p><div class="client-actions">${x.phone?`<a class="action-link" href="tel:${x.phone.replace(/\D/g,'')}">Позвонить</a>`:''}</div></article>`).join('')||'<div class="muted">Клиентов пока нет.</div>'}
function setType(type){editingType=type;$$('#typeTabs [data-type]').forEach(b=>b.classList.toggle('selected',b.dataset.type===type))}
function openJob(id=null,date=fmtDate(today),slot=firstFreeSlot(date)){const modal=$('#jobModal'),j=id?state.jobs.find(x=>x.id===id):null;modal.classList.add('open');modal.setAttribute('aria-hidden','false');$('#modalTitle').textContent=j?'Редактировать выезд':'Новый выезд';$('#jobId').value=j?.id||'';$('#jobDate').value=j?.date||date;$('#jobSlot').value=j?.slot||slot;$('#jobClient').value=j?.client||'';$('#jobPhone').value=j?.phone||'';$('#jobPrice').value=j?.price||'';$('#jobAddress').value=j?.address||'';$('#jobStore').value=j?.store||'';$('#jobStatus').value=j?.status||'Запланирован';$('#jobComment').value=j?.comment||'';setType(j?.type||'Монтаж');$('#deleteBtn').style.display=j?'block':'none';checkSlot()}
function checkSlot(){const id=$('#jobId').value||null,date=$('#jobDate').value,slot=$('#jobSlot').value,type=editingType;const r=canPlace(state.jobs,{id:id||'new',date,slot,type},{ignoreId:id});const el=$('#slotWarning');if(!r.ok){el.textContent='⚠️ '+r.reason;el.classList.remove('hidden')}else{el.textContent='';el.classList.add('hidden')}}
async function saveJob(e){e.preventDefault();const id=$('#jobId').value||uid(),job={id,date:$('#jobDate').value,slot:$('#jobSlot').value,type:editingType,client:$('#jobClient').value.trim(),phone:$('#jobPhone').value.trim(),price:Number($('#jobPrice').value||0),address:$('#jobAddress').value.trim(),store:$('#jobStore').value.trim(),status:$('#jobStatus').value,comment:$('#jobComment').value.trim()};const r=canPlace(state.jobs,job,{ignoreId:$('#jobId').value||null});if(!r.ok){checkSlot();return}const i=state.jobs.findIndex(x=>x.id===id);if(i>=0)state.jobs[i]=job;else state.jobs.push(job);save();closeModal()}
function closeModal(){const m=$('#jobModal');m.classList.remove('open');m.setAttribute('aria-hidden','true')}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`astera-backup-${fmtDate(today)}.json`;a.click();URL.revokeObjectURL(a.href)}
function initEvents(){$$('.nav').forEach(b=>b.onclick=()=>{$$('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.screen).classList.add('active')});$('#addBtn').onclick=()=>openJob();$('#todayJump').onclick=()=>window.scrollTo({top:0,behavior:'smooth'});$('#prevMonth').onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()-1,1);renderCalendar()};$('#nextMonth').onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()+1,1);renderCalendar()};$$('#periodTabs button').forEach(b=>b.onclick=()=>{$$('#periodTabs button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');period=b.dataset.period;renderMoney()});$$('#typeTabs [data-type]').forEach(b=>b.onclick=()=>{setType(b.dataset.type);checkSlot()});['jobDate','jobSlot'].forEach(id=>$('#'+id).addEventListener('change',checkSlot));$('#jobForm').onsubmit=saveJob;$('#deleteBtn').onclick=()=>{const id=$('#jobId').value;if(id){state.jobs=state.jobs.filter(j=>j.id!==id);save();closeModal()}};$$('[data-close="jobModal"]').forEach(x=>x.onclick=closeModal);$('#backupBtn').onclick=exportData;$('#restoreInput').onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!Array.isArray(x.jobs))throw Error();state={jobs:x.jobs,expenses:x.expenses||{}};save()}catch{alert('Не удалось восстановить резервную копию')}};r.readAsText(f)};$('#clearDemoBtn').onclick=()=>{if(confirm('Сбросить к исходным данным ASTERA?')){state={jobs:seed,expenses:{}};save()}};$('#clientSearch').addEventListener('input',renderClients);$('#themeBtn').onclick=()=>{const dark=document.documentElement.classList.toggle('dark');localStorage.setItem(THEME,dark?'dark':'light')};if(localStorage.getItem(THEME)==='dark')document.documentElement.classList.add('dark')}

function markSync(mode){const el=$('#syncStatus');if(el)el.textContent=mode}
async function initFirebase(){
 if(!firebaseConfig?.apiKey||!firebaseConfig?.projectId){markSync('Локальный режим · Firebase ещё не подключён');return}
 try{
  const [{initializeApp},{getApps},authMod,fsMod]=await Promise.all([
   import('https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js'),
   import('https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js'),
   import('https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js'),
   import('https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js')
  ]);
  const app=(getApps()[0])||initializeApp(firebaseConfig); const auth=authMod.getAuth(app); const db=fsMod.getFirestore(app);
  const btn=document.createElement('button');btn.className='setting-row';btn.id='firebaseLogin';btn.innerHTML='<span>Синхронизация</span><b>Войти через Google ›</b>';$('.settings-card').prepend(btn);
  btn.onclick=async()=>{try{await authMod.signInWithPopup(auth,new authMod.GoogleAuthProvider());markSync('Firebase · вход выполнен')}catch(e){markSync('Firebase: '+(e?.code||'ошибка входа'))}};
  authMod.onAuthStateChanged(auth,async user=>{if(!user)return;markSync('Firebase · синхронизация включена');const ref=fsMod.doc(db,'astera_workspaces','default');const snap=await fsMod.getDoc(ref);if(snap.exists()){const remote=snap.data();if(Array.isArray(remote.jobs)){state={jobs:remote.jobs,expenses:remote.expenses||{}};localStorage.setItem(KEY,JSON.stringify(state));renderAll()}}});
  window.addEventListener('beforeunload',async()=>{const user=auth.currentUser;if(user)await fsMod.setDoc(fsMod.doc(db,'astera_workspaces','default'),{jobs:state.jobs,expenses:state.expenses||{},updatedAt:Date.now()})});
 }catch(e){markSync('Локальный режим · Firebase недоступен');console.warn(e)}
}

initEvents();renderAll();initFirebase();
