import { firebaseConfig } from './firebase-config.js';
import { planningViewModel } from './modules/planning-view.js?v=20260914-step3';

const FIREBASE_VERSION = '10.14.1';
const SHARED_DOC = ['appData', 'shared'];
const NOTES_DOC = ['appData', 'notes'];
const SLOTS = { '1': '10:00–12:00', '2': '14:00–16:00', '3': '3-й слот / резерв' };
const $ = (s, root = document) => root.querySelector(s);
const $$ = (s, root = document) => [...root.querySelectorAll(s)];
const uid = () => crypto.randomUUID?.() || `${Date.now()}-${Math.random()}`;
const money = n => new Intl.NumberFormat('ru-RU').format(Math.round(Number(n) || 0)) + ' ₽';
const num = v => Math.max(0, Number(String(v ?? '').replace(',', '.')) || 0);
const dateKey = d => { const x = new Date(d); return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`; };
const today = () => dateKey(new Date());
const fmtDate = d => new Intl.DateTimeFormat('ru-RU', { weekday:'long', day:'numeric', month:'long' }).format(new Date(`${d}T12:00:00`));
const fmtShort = d => new Intl.DateTimeFormat('ru-RU', { day:'2-digit', month:'2-digit', year:'numeric' }).format(new Date(`${d}T12:00:00`));
const esc = s => String(s ?? '').replace(/[&<>\"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
const isDone = j => j.status === 'Выполнен';
const isCancelled = j => j.status === 'Отменён';
const isMeasure = j => j.type === 'Замер';
const activityDate = j => isDone(j) ? (j.completedDate || j.date) : j.date;
const emptyState = () => ({ jobs: [], expenses: [], version: 5 });
const normalize = d => ({ jobs: Array.isArray(d?.jobs) ? d.jobs.map(j => ({ ...j, id:j.id || uid(), date:j.date || today(), slot:String(j.slot || '1'), type:j.type || 'Монтаж', client:j.client || '', price:num(j.price), status:j.status || 'Запланирован', paid:j.paid !== false, completedDate:j.completedDate || '', time:j.time || '', measurePrice:num(j.measurePrice), measurePaid:j.measurePaid === true, measureCredit:num(j.measureCredit), convertedToJobId:j.convertedToJobId || '', source:j.source || j.store || '' })) : [], expenses: Array.isArray(d?.expenses) ? d.expenses.map(e => ({ ...e, id:e.id || uid(), date:e.date || today(), amount:num(e.amount), category:e.category || 'Прочее', comment:e.comment || '', cancelled:e.cancelled === true })) : [], version:5 });
let F, auth, db, user, unsubscribeShared=null, unsubscribeNotes=null; let state=emptyState(), notes=[], serverReady=false, online=navigator.onLine; let month=new Date(new Date().getFullYear(),new Date().getMonth(),1), financePeriod='day', editingType='Монтаж';
function status(text,kind='normal'){const el=$('#syncStatus');if(el){el.textContent=text;el.dataset.state=kind;}}
function toast(text,kind='normal'){let el=$('#toast');if(!el){el=document.createElement('div');el.id='toast';document.body.append(el);}el.textContent=text;el.dataset.state=kind;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.remove(),3400);}
function modal(id,open=true){const el=$(`#${id}`);if(!el)return;el.classList.toggle('open',open);el.setAttribute('aria-hidden',String(!open));document.body.classList.toggle('modal-open',open || !!$('.modal.open'));}
function showAuth(show){$('#authScreen')?.classList.toggle('hidden',!show);$('#app')?.classList.toggle('hidden',show);}
function authError(e){return ({'auth/invalid-credential':'Неверный email или пароль.','auth/invalid-email':'Проверьте email.','auth/user-disabled':'Доступ отключён.','auth/too-many-requests':'Слишком много попыток. Попробуйте позже.','auth/email-already-in-use':'Этот email уже зарегистрирован.','auth/weak-password':'Пароль должен быть не короче 6 символов.','auth/operation-not-allowed':'В Firebase не включён Email/Password.','auth/network-request-failed':'Нет соединения.'}[e?.code]||e?.message||'Ошибка авторизации.');}
function authMessage(text,error=false){const el=$('#authMessage');if(el){el.textContent=text;el.className=`auth-message${error?' auth-message--error':''}`;}}
async function initFirebase(){const [appMod,authMod,fs]=await Promise.all([import(`https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-app.js`),import(`https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-auth.js`),import(`https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-firestore.js`)]);const app=appMod.initializeApp(firebaseConfig,'montaji-aa-production');auth=authMod.getAuth(app);db=fs.getFirestore(app);F={...fs,authMod};}
function bindAuth(){$('#authForm').onsubmit=async e=>{e.preventDefault();const email=$('#authEmail').value.trim(),pass=$('#authPassword').value;if(!online)return authMessage('Нет интернета.',true);if(!email||!pass)return authMessage('Введите email и пароль.',true);authMessage('Входим…');try{await F.authMod.signInWithEmailAndPassword(auth,email,pass)}catch(err){authMessage(authError(err),true)}};$('#signUpBtn').onclick=async()=>{const email=$('#authEmail').value.trim(),pass=$('#authPassword').value;if(!email||!pass)return authMessage('Введите email и пароль.',true);if(pass.length<6)return authMessage('Пароль должен быть не короче 6 символов.');try{const c=await F.authMod.createUserWithEmailAndPassword(auth,email,pass);await F.authMod.sendEmailVerification(c.user);await F.authMod.signOut(auth);authMessage('Письмо отправлено. Подтвердите email и войдите.')}catch(err){authMessage(authError(err),true)}};$('#resetBtn').onclick=async()=>{const email=$('#authEmail').value.trim();if(!email)return authMessage('Введите email.',true);try{await F.authMod.sendPasswordResetEmail(auth,email);authMessage('Ссылка для сброса отправлена.')}catch(err){authMessage(authError(err),true)}};}
function currentNotesData(s){const d=s?.exists()?s.data()?.data||{}:{};return Array.isArray(d.notes)?d.notes:[];}
async function loadServer(){if(!user||!online){serverReady=false;state=emptyState();notes=[];render();status('Нет интернета · данные не загружены','offline');return false;}status('Подключаем общую базу…');try{const [sharedSnap,notesSnap]=await Promise.all([F.getDocFromServer(F.doc(db,...SHARED_DOC)),F.getDocFromServer(F.doc(db,...NOTES_DOC))]);state=sharedSnap.exists()?normalize(sharedSnap.data().data):emptyState();notes=currentNotesData(notesSnap);serverReady=true;render();status('● Общая база · синхронизировано','online');return true;}catch(err){console.error(err);serverReady=false;state=emptyState();notes=[];render();status('База недоступна','offline');toast('Не удалось получить данные с сервера.','error');return false;}}
function startRealtime(){unsubscribeShared?.();unsubscribeNotes?.();if(!user||!online)return;unsubscribeShared=F.onSnapshot(F.doc(db,...SHARED_DOC),snap=>{if(!online)return;state=snap.exists()?normalize(snap.data().data):emptyState();serverReady=true;render();status('● Общая база · обновлено','online')},()=>{serverReady=false;status('Нет связи с общей базой','offline');toast('Потеряна связь с общей базой','error')});unsubscribeNotes=F.onSnapshot(F.doc(db,...NOTES_DOC),snap=>{if(!online)return;notes=currentNotesData(snap);renderNotes()},()=>{});}
async function saveShared(mutator){if(!serverReady||!online||!user)throw new Error('Нет соединения с общей базой');const ref=F.doc(db,...SHARED_DOC);await F.runTransaction(db,async tx=>{const snap=await tx.get(ref),current=snap.exists()?normalize(snap.data().data):emptyState(),next=normalize(await mutator(current));tx.set(ref,{data:next,version:5,updatedAt:F.serverTimestamp(),updatedBy:user.uid},{merge:true})});}
async function saveNotes(mutator){if(!serverReady||!online||!user)throw new Error('Нет соединения с общей базой');const ref=F.doc(db,...NOTES_DOC);await F.runTransaction(db,async tx=>{const snap=await tx.get(ref),cur={notes:currentNotesData(snap)},next=await mutator(JSON.parse(JSON.stringify(cur)));tx.set(ref,{data:{notes:Array.isArray(next.notes)?next.notes:[]},version:1,updatedAt:F.serverTimestamp(),updatedBy:user.uid},{merge:true})});}
function jobsForDate(d){return state.jobs.filter(j=>!isCancelled(j)&&j.date===d);} function activeJobs(d){return jobsForDate(d).filter(j=>!isDone(j));} function montageCount(d){return planningViewModel(state.jobs,d,3).actualCount;} function isPlanningSlot(slot){return ['1','2','3'].includes(String(slot));} function freeSlot(d){const used=new Set(activeJobs(d).filter(j=>j.type==='Монтаж').map(j=>String(j.slot)));return ['1','2','3'].find(s=>!used.has(s))||'extra';} function ensureExtraSlotOption(){const select=$('#jobSlot');if(!select||select.querySelector('option[value="extra"]'))return;const option=document.createElement('option');option.value='extra';option.textContent='Дополнительный монтаж · без планового окна';select.append(option);}
function periodBounds(period){const now=new Date();if(period==='day')return[today(),today()];if(period==='week'){const day=(now.getDay()+6)%7,start=new Date(now);start.setDate(now.getDate()-day);const end=new Date(start);end.setDate(start.getDate()+6);return[dateKey(start),dateKey(end)]}if(period==='month')return[dateKey(new Date(now.getFullYear(),now.getMonth(),1)),dateKey(new Date(now.getFullYear(),now.getMonth()+1,0))];return['0000-01-01','9999-12-31'];}
function effectiveIncome(j){if(isCancelled(j)||!isDone(j))return 0;if(isMeasure(j))return num(j.measurePrice||j.price);return num(j.price);}
function totals(period){const[a,b]=periodBounds(period),jobs=state.jobs.filter(j=>!isCancelled(j)&&isDone(j)&&activityDate(j)>=a&&activityDate(j)<=b),income=jobs.reduce((s,j)=>s+effectiveIncome(j),0),expenses=state.expenses.filter(e=>!e.cancelled&&e.date>=a&&e.date<=b).reduce((s,e)=>s+e.amount,0),unpaid=jobs.filter(j=>j.paid===false).reduce((s,j)=>s+effectiveIncome(j),0);return{income,expenses,net:income-expenses,unpaid,done:jobs.length};}
function dateTotals(d){const jobs=jobsForDate(d).filter(isDone),income=jobs.reduce((s,j)=>s+effectiveIncome(j),0),expenses=state.expenses.filter(e=>!e.cancelled&&e.date===d).reduce((s,e)=>s+e.amount,0),unpaid=jobs.filter(j=>j.paid===false).reduce((s,j)=>s+effectiveIncome(j),0);return{income,expenses,net:income-expenses,unpaid};}
function mapLinks(address){const q=encodeURIComponent(address);return`<a class="map-chip" href="https://yandex.ru/maps/?text=${q}" target="_blank" rel="noopener">Яндекс</a><a class="map-chip" href="https://2gis.ru/search/${q}" target="_blank" rel="noopener">2ГИС</a>`;} function callLink(phone){const p=(phone||'').replace(/[^\d+]/g,'');return p?`<a class="action-chip" href="tel:${esc(p)}">Позвонить</a>`:'';} function shareAddress(j){return j.address?`<button class="action-chip share-address" data-id="${esc(j.id)}">Отправить адрес</button>`:'';}
function statusLabel(j){if(j.status==='Выполнен')return`<span class="status-pill done">✓ Выполнен${j.paid===false?' · долг':''}</span>`;if(j.status==='В пути')return'<span class="status-pill route">В пути</span>';if(j.status==='На объекте')return'<span class="status-pill onsite">На объекте</span>';if(j.status==='Отменён')return'<span class="status-pill cancelled">Отменён</span>';if(j.type==='Замер')return'<span class="status-pill measure">Замер</span>';return`<span class="status-pill">${esc(j.status||'Запланирован')}</span>`;}
function jobCard(j,{compact=false}={}){const time=isMeasure(j)?(j.time||SLOTS[j.slot]||'Свободное время'):(SLOTS[j.slot]||j.time||(isPlanningSlot(j.slot)?'':'Дополнительный монтаж')),amount=isMeasure(j)?num(j.measurePrice||j.price):num(j.price),credit=j.measureCredit?` · зачёт ${money(j.measureCredit)}`:'';return`<article class="job-card ${isDone(j)?'job-done':''} ${isMeasure(j)?'job-measure':''}" data-job-card="${esc(j.id)}"><div class="job-top"><div><div class="job-client">${esc(j.client||'Без клиента')}</div><div class="job-meta">${esc(time)} · ${esc(j.type)}${j.store?' · '+esc(j.store):''}</div></div><div class="amount">${money(amount)}</div></div><div class="job-details">${j.address?`<div class="detail-line">📍 ${esc(j.address)}</div>`:''}${j.comment&&!compact?`<div class="detail-line note-line">${esc(j.comment)}</div>`:''}<div class="card-status">${statusLabel(j)}${j.completedDate?` <small>${fmtShort(j.completedDate)}</small>`:''}${credit?`<small>${credit}</small>`:''}</div></div><div class="actions">${j.address?mapLinks(j.address):''}${callLink(j.phone)}${shareAddress(j)}<button class="action-chip primary-chip edit" data-id="${esc(j.id)}">Открыть</button></div>${!compact&&!isDone(j)&&!isCancelled(j)?`<div class="quick-actions"><button data-quick="route" data-id="${esc(j.id)}">В путь</button><button data-quick="done" data-id="${esc(j.id)}">Выполнено</button>${j.paid===false?`<button data-quick="paid" data-id="${esc(j.id)}">Оплачено</button>`:''}</div>`:''}</article>`;}
function renderToday(){const d=today(),jobs=jobsForDate(d),t=totals('day'),w=totals('week'),m=totals('month');$('#topDate').textContent=new Intl.DateTimeFormat('ru-RU',{weekday:'long',day:'numeric',month:'long'}).format(new Date());$('#todayIncome').textContent=money(t.net);$('#todayGross').textContent=money(t.income);$('#todayExpense').textContent=money(t.expenses);const planning=planningViewModel(state.jobs,d,3);$('#todayLoad').textContent=String(planning.actualCount);$('#todayProgress').style.width=Math.min(100,planning.actualCount/Math.max(3,planning.averageLoad)*100)+'%';$('#todayWeek').textContent=money(w.net);$('#todayMonth').textContent=money(m.net);const advice=[],tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+1);const tc=montageCount(dateKey(tomorrow)),late=state.jobs.filter(j=>!isCancelled(j)&&!isDone(j)&&j.date<d).length;if(late)advice.push(`⚠️ ${late} просроченных выездов`);if(tc>3)advice.push(`📋 Завтра ${tc} монтажей — выше средней нагрузки`);else if(tc===3)advice.push('📋 Завтра плановая средняя нагрузка · 3 монтажа');else if(tc===2)advice.push('✨ Завтра одно плановое монтажное окно свободно');if(t.unpaid)advice.push(`💰 ${money(t.unpaid)} ещё не оплачено`);$('#insights').innerHTML=advice.slice(0,3).map(x=>`<div class="insight">${esc(x)}</div>`).join('');const list=jobsForDate(d).sort((a,b)=>String(a.slot).localeCompare(String(b.slot)));$('#todayList').innerHTML=list.length?list.map(j=>jobCard(j)).join(''):'<div class="empty">На сегодня выездов нет.</div>';bindJobCards($('#todayList'));}
function renderCalendar(){const y=month.getFullYear(),m=month.getMonth(),start=(new Date(y,m,1).getDay()+6)%7,last=new Date(y,m+1,0).getDate();let h='';for(let i=0;i<start;i++)h+='<div class="day blank"></div>';for(let n=1;n<=last;n++){const k=dateKey(new Date(y,m,n)),planning=planningViewModel(state.jobs,k,3),c=planning.actualCount,js=activeJobs(k),hasMeasure=js.some(isMeasure);h+=`<button class="day ${planning.overAverage?'busy':c===2?'partial':c?'partial':''} ${hasMeasure?'has-measure':''} ${k===today()?'today':''}" data-date="${k}"><b>${n}</b><span>${js.length} выезд${js.length===1?'':'а'}</span><i>${c} монтаж${c===1?'':'а'}${hasMeasure?' · замер':''}</i></button>`;}$('#scheduleMonth').textContent=new Intl.DateTimeFormat('ru-RU',{month:'long',year:'numeric'}).format(month);$('#calendar').innerHTML=h;$$('.day[data-date]').forEach(b=>b.onclick=()=>openDay(b.dataset.date));}
function openDay(d){const js=jobsForDate(d),pending=js.filter(j=>!isDone(j)),done=js.filter(isDone),t=dateTotals(d),planning=planningViewModel(state.jobs,d,3),m=document.createElement('div');m.className='modal open';m.innerHTML=`<div class="backdrop"></div><div class="sheet"><div class="handle"></div><div class="sheet-head"><div><div class="eyebrow">Рабочий день</div><h2>${esc(fmtDate(d))}</h2></div><button class="circle-btn" data-close>×</button></div><div class="day-stats"><div><small>Монтажей</small><b>${planning.actualCount}</b></div><div><small>Плановая средняя</small><b>${planning.averageLoad}</b></div><div><small>Свободные окна</small><b>${planning.freeSlots.length}</b></div></div><div class="day-actions"><button id="dayAdd">＋ Выезд</button><button id="dayExpense">− Расход</button><button id="dayNote">＋ Заметка</button></div><h3 class="sheet-section">Плановые окна</h3>${['1','2','3'].map(s=>{const j=pending.find(x=>x.type==='Монтаж'&&String(x.slot)===s);return`<div class="slot"><div class="slot-title">${SLOTS[s]}</div>${j?jobCard(j,{compact:true}):`<button class="free-slot" data-slot="${s}">＋ Свободное окно</button>`}</div>`}).join('')}${pending.filter(j=>j.type==='Монтаж'&&!isPlanningSlot(j.slot)).length?`<h3 class="sheet-section">Дополнительные монтажи</h3>${pending.filter(j=>j.type==='Монтаж'&&!isPlanningSlot(j.slot)).map(j=>jobCard(j,{compact:true})).join('')}`:''}${pending.filter(j=>j.type!=='Монтаж').length?`<h3 class="sheet-section">Другие выезды</h3>${pending.filter(j=>j.type!=='Монтаж').map(j=>jobCard(j,{compact:true})).join('')}`:''}${done.length?`<h3 class="sheet-section">История</h3>${done.map(j=>jobCard(j,{compact:true})).join('')}`:''}${t.unpaid?`<button class="debt-banner" data-open-debts="1">💰 Не оплачено: ${money(t.unpaid)} · открыть долги</button>`:''}<button class="archive-day" id="archiveDay">Открыть полный день →</button></div>`;document.body.append(m);m.querySelector('.backdrop').onclick=()=>m.remove();m.querySelector('[data-close]').onclick=()=>m.remove();m.querySelector('#dayAdd').onclick=()=>{m.remove();openJob(null,d,freeSlot(d),'Монтаж')};m.querySelector('#dayExpense').onclick=()=>{m.remove();openExpense(d)};m.querySelector('#dayNote').onclick=()=>{m.remove();openNote()};m.querySelector('#archiveDay').onclick=()=>showDayArchive(d);m.querySelectorAll('.free-slot').forEach(b=>b.onclick=()=>{m.remove();openJob(null,d,b.dataset.slot,'Монтаж')});m.querySelectorAll('.edit').forEach(b=>b.onclick=()=>{m.remove();openJob(b.dataset.id)});bindQuickActions(m);}
function showDayArchive(d){const t=dateTotals(d),jobs=jobsForDate(d),expenses=state.expenses.filter(e=>!e.cancelled&&e.date===d),m=document.createElement('div');m.className='modal open';m.innerHTML=`<div class="backdrop"></div><div class="sheet"><div class="sheet-head"><div><div class="eyebrow">История</div><h2>${esc(fmtDate(d))}</h2></div><button class="circle-btn" data-close>×</button></div><div class="day-stats"><div><small>Доход</small><b>${money(t.income)}</b></div><div><small>Расход</small><b>− ${money(t.expenses)}</b></div><div><small>Чистыми</small><b>${money(t.net)}</b></div></div><h3 class="sheet-section">Выезды</h3>${jobs.length?jobs.map(j=>jobCard(j,{compact:true})).join(''):'<div class="muted">Нет выездов</div>'}<h3 class="sheet-section">Расходы</h3>${expenses.length?expenses.map(e=>`<div class="expense-row"><div><b>${esc(e.category)}</b><small>${esc(e.comment||'')}</small></div><strong>− ${money(e.amount)}</strong><button class="mini-edit" data-expense="${esc(e.id)}">Изм.</button></div>`).join(''):'<div class="muted">Нет расходов</div>'}<button class="primary wide" id="archiveAddExpense">＋ Расход за ${esc(fmtShort(d))}</button></div>`;document.body.append(m);m.querySelector('.backdrop').onclick=()=>m.remove();m.querySelector('[data-close]').onclick=()=>m.remove();m.querySelector('#archiveAddExpense').onclick=()=>{m.remove();openExpense(d)};m.querySelectorAll('.mini-edit').forEach(b=>{const e=state.expenses.find(x=>x.id===b.dataset.expense);b.onclick=()=>{m.remove();openExpense(e?.date,e)}});m.querySelectorAll('.edit').forEach(b=>{b.onclick=()=>{m.remove();openJob(b.dataset.id)}});}
function bindJobCards(root){root.querySelectorAll('.edit').forEach(b=>b.onclick=()=>openJob(b.dataset.id));root.querySelectorAll('.share-address').forEach(b=>b.onclick=()=>{const j=state.jobs.find(x=>x.id===b.dataset.id);if(j?.address)navigator.clipboard?.writeText(j.address).then(()=>toast('Адрес скопирован','success')).catch(()=>toast('Адрес: '+j.address));});bindQuickActions(root);}
function bindQuickActions(root=document){root.querySelectorAll('[data-quick]').forEach(b=>b.onclick=async()=>{const j=state.jobs.find(x=>x.id===b.dataset.id);if(!j)return;const action=b.dataset.quick,patch=action==='route'?{status:'В пути'}:action==='done'?{status:'Выполнен',completedDate:today()}:action==='paid'?{paid:true}:{};try{await updateJob(j.id,patch);toast('Статус обновлён','success')}catch(e){toast('Не удалось обновить','error')}});}
function openExpense(d=today(),edit=null){$('#expenseId').value=edit?.id||'';$('#expenseDate').value=edit?.date||d;$('#expenseAmount').value=edit?.amount??'';$('#expenseCategory').value=edit?.category||'Прочее';$('#expenseComment').value=edit?.comment||'';modal('expenseModal',true);}
function openNote(){modal('noteModal',true);}
function updateJob(id,patch){return saveShared(cur=>({...cur,jobs:cur.jobs.map(j=>j.id===id?{...j,...patch}:j)}));}
function openJob(id=null,d=today(),slot=freeSlot(d),type='Монтаж',preset=null){ensureExtraSlotOption();const j=id?state.jobs.find(x=>x.id===id):null;editingType=j?.type||type;$('#modalTitle').textContent=j?'Изменить выезд':'Новый выезд';$('#jobId').value=j?.id||'';$('#jobDate').value=j?.date||d;$('#jobSlot').value=j?.slot||slot;if(!isPlanningSlot($('#jobSlot').value))$('#jobSlot').value='extra';$('#jobTime').value=j?.time||'';$('#jobClient').value=j?.client||preset?.client||'';$('#jobPhone').value=j?.phone||preset?.phone||'';$('#jobPrice').value=j?.price??(preset?.price??'');$('#jobAddress').value=j?.address||preset?.address||'';$('#jobStore').value=j?.store||preset?.store||'';$('#jobStatus').value=j?.status||(type==='Доп. доход'?'Выполнен':'Запланирован');$('#jobCompletedDate').value=j?.completedDate||j?.date||d;$('#jobPaid').value=j?.paid===false?'no':'yes';$('#jobComment').value=j?.comment||preset?.comment||'';$('#measurePrice').value=j?.measurePrice??'';$('#measurePaid').checked=j?.measurePaid===true||j?.paid===true&&isMeasure(j);$('#measureCredit').value=j?.measureCredit??preset?.measureCredit??'';$('#measureLink').value=j?.convertedToJobId||'';$('#measureLink').dataset.sourceMeasure=preset?.measureId||j?.convertedFromMeasureId||'';$$('#typeTabs button').forEach(b=>b.classList.toggle('selected',b.dataset.type===editingType));updateJobForm();modal('jobModal',true);}
function updateJobForm(){const measure=editingType==='Замер',done=$('#jobStatus').value==='Выполнен';$('#slotWrap').classList.toggle('hidden',measure);$('#timeWrap').classList.toggle('hidden',!measure);$('#priceWrap').classList.toggle('hidden',measure);$('#measureWrap').classList.toggle('hidden',!measure);$('#completedDateWrap').style.display=done?'grid':'none';$('#deleteBtn').style.display=$('#jobId').value?'block':'none';$('#convertMeasureBtn').style.display=measure&&$('#jobId').value&&!$('#measureLink').value?'block':'none';}
function checkSlot(){const d=$('#jobDate').value,s=$('#jobSlot').value,id=$('#jobId').value,conflict=editingType==='Монтаж'&&isPlanningSlot(s)&&state.jobs.find(j=>j.id!==id&&!isCancelled(j)&&!isDone(j)&&j.type==='Монтаж'&&j.date===d&&isPlanningSlot(j.slot)&&String(j.slot)===s);const w=$('#slotWarning');w.classList.toggle('hidden',!conflict);if(conflict)w.textContent=`Слот занят: ${conflict.client}.`;}
async function saveJob(e){e.preventDefault();if(!serverReady)return toast('Нет соединения с общей базой.','error');const id=$('#jobId').value||uid(),d=$('#jobDate').value,client=$('#jobClient').value.trim();if(!d||!client)return toast('Укажите дату и клиента','error');let selectedSlot=$('#jobSlot').value;if(editingType==='Монтаж'){if(!isPlanningSlot(selectedSlot))selectedSlot=`extra-${uid()}`;const conflict=isPlanningSlot($('#jobSlot').value)&&state.jobs.find(j=>j.id!==id&&!isCancelled(j)&&!isDone(j)&&j.type==='Монтаж'&&j.date===d&&isPlanningSlot(j.slot)&&String(j.slot)===$('#jobSlot').value);if(conflict)return toast(`Слот занят: ${conflict.client}`,'error')}const job={id,date:d,slot:selectedSlot,time:$('#jobTime').value,type:editingType,client,phone:$('#jobPhone').value.trim(),price:editingType==='Замер'?0:num($('#jobPrice').value),measurePrice:editingType==='Замер'?num($('#measurePrice').value):0,measurePaid:editingType==='Замер'&&$('#measurePaid').checked,measureCredit:editingType==='Замер'?0:num($('#measureCredit').value),convertedToJobId:$('#measureLink').value.trim(),convertedFromMeasureId:$('#measureLink').dataset.sourceMeasure||'',address:$('#jobAddress').value.trim(),store:$('#jobStore').value.trim(),status:$('#jobStatus').value,completedDate:$('#jobStatus').value==='Выполнен'?($('#jobCompletedDate').value||d):'',paid:editingType==='Замер'?$('#measurePaid').checked:$('#jobPaid').value!=='no',comment:$('#jobComment').value.trim(),source:$('#jobStore').value.trim()};try{await saveShared(cur=>{const jobs=[...cur.jobs],i=jobs.findIndex(x=>x.id===id);i<0?jobs.push(job):jobs[i]={...jobs[i],...job};const sourceId=job.convertedFromMeasureId;if(sourceId){const source=jobs.find(x=>x.id===sourceId);if(source)source.convertedToJobId=id;}return{...cur,jobs}});modal('jobModal',false);toast('Сохранено','success')}catch(err){console.error(err);toast('Не удалось сохранить','error')}}
async function deleteJob(){const id=$('#jobId').value;if(!id)return;const j=state.jobs.find(x=>x.id===id);if(!j)return;if(!confirm('Убрать запись в архив? Данные не будут потеряны.'))return;try{await updateJob(id,{status:'Отменён'});modal('jobModal',false);toast('Запись отправлена в архив','success')}catch(e){toast('Не удалось архивировать','error')}}
async function saveExpense(e){e.preventDefault();if(!serverReady)return toast('Нет соединения с общей базой.','error');const id=$('#expenseId').value||uid(),expense={id,date:$('#expenseDate').value||today(),amount:num($('#expenseAmount').value),category:$('#expenseCategory').value,comment:$('#expenseComment').value.trim(),cancelled:false};if(!expense.amount)return toast('Укажите сумму','error');try{await saveShared(cur=>{const expenses=[...cur.expenses],i=expenses.findIndex(x=>x.id===id);i<0?expenses.push(expense):expenses[i]={...expenses[i],...expense};return{...cur,expenses}});modal('expenseModal',false);toast('Расход сохранён','success')}catch(e){toast('Не удалось сохранить расход','error')}}
async function saveNoteForm(e){e.preventDefault();const text=$('#noteText').value.trim();if(!text)return;try{await saveNotes(cur=>({...cur,notes:[...cur.notes,{id:uid(),text,date:today(),archived:false}]}));modal('noteModal',false);$('#noteText').value='';toast('Заметка сохранена','success')}catch(e){toast('Не удалось сохранить заметку','error')}}
function renderNotes(){const active=notes.filter(n=>!n.archived),arch=notes.filter(n=>n.archived);$('#activeNotes').innerHTML=active.length?active.map(n=>`<div class="note-row"><span>${esc(n.text)}</span><button data-note-archive="${esc(n.id)}">✓</button></div>`).join(''):'<div class="muted">Активных заметок нет</div>';$('#archivedNotes').innerHTML=arch.length?arch.map(n=>`<div class="note-row archived"><span>${esc(n.text)}</span></div>`).join(''):'<div class="muted">Архив пуст</div>';$$('[data-note-archive]').forEach(b=>b.onclick=async()=>{try{await saveNotes(cur=>({...cur,notes:cur.notes.map(n=>n.id===b.dataset.noteArchive?{...n,archived:true}:n)}))}catch(e){toast('Не удалось обновить заметку','error')}});}
function renderUpcoming(){const ds=[1,2,3,4,5].map(n=>{const d=new Date();d.setDate(d.getDate()+n);return dateKey(d)});$('#upcoming').innerHTML=ds.map(d=>{const js=activeJobs(d),c=montageCount(d);return`<button class="upcoming-row" data-date="${d}"><span>${esc(fmtShort(d))}</span><b>${c} монтаж${c===1?'':'а'}</b><small>${js.length} выезд${js.length===1?'':'а'}</small></button>`}).join('');$$('.upcoming-row').forEach(b=>b.onclick=()=>openDay(b.dataset.date));}
function renderExpenses(){const d=today(),ex=state.expenses.filter(e=>!e.cancelled&&e.date===d);$('#todayExpenses').innerHTML=ex.length?ex.map(e=>`<div class="expense-row"><div><b>${esc(e.category)}</b><small>${esc(e.comment||'')}</small></div><strong>− ${money(e.amount)}</strong></div>`).join(''):'<div class="muted">Расходов сегодня нет</div>';}
function renderMoney(){const t=totals(financePeriod);$('#moneyTotal').textContent=money(t.net);$('#moneyPeriod').textContent=financePeriod==='day'?'Сегодня':financePeriod==='week'?'Неделя':financePeriod==='month'?'Месяц':'Весь период';$('#moneyHighlights').innerHTML=`<div><small>Доход</small><b>${money(t.income)}</b></div><div><small>Расход</small><b>− ${money(t.expenses)}</b></div><div><small>Долги</small><b>${money(t.unpaid)}</b></div>`;$('#moneyGrid').innerHTML=['day','week','month','all'].map(p=>`<button class="money-period-btn ${financePeriod===p?'selected':''}" data-period="${p}">${p==='day'?'Сегодня':p==='week'?'Неделя':p==='month'?'Месяц':'Весь период'}</button>`).join('');$$('.money-period-btn').forEach(b=>b.onclick=()=>{financePeriod=b.dataset.period;renderMoney()});const debts=state.jobs.filter(j=>isDone(j)&&!isCancelled(j)&&j.paid===false);$('#debtList').innerHTML=debts.length?debts.map(j=>`<div class="debt-row"><span>${esc(j.client)}</span><b>${money(effectiveIncome(j))}</b></div>`).join(''):'<div class="muted">Долгов нет</div>';const stores={};state.jobs.filter(j=>isDone(j)&&!isCancelled(j)).forEach(j=>{const k=j.store||j.source||'Без источника';stores[k]=(stores[k]||0)+effectiveIncome(j)});$('#storeBreakdown').innerHTML=Object.entries(stores).length?Object.entries(stores).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="source-row"><span>${esc(k)}</span><b>${money(v)}</b></div>`).join(''):'<div class="muted">Нет данных</div>';const ex=state.expenses.filter(e=>!e.cancelled).sort((a,b)=>b.date.localeCompare(a.date));$('#expenseArchive').innerHTML=ex.length?ex.slice(0,30).map(e=>`<div class="expense-row"><div><b>${esc(e.category)}</b><small>${esc(e.date)} · ${esc(e.comment||'')}</small></div><strong>− ${money(e.amount)}</strong></div>`).join(''):'<div class="muted">Расходов нет</div>';}
function renderClients(){const q=$('#clientSearch').value.trim().toLowerCase();const map=new Map();state.jobs.filter(j=>!isCancelled(j)).forEach(j=>{const key=(j.phone||j.client||'').trim().toLowerCase();if(!key)return;const prev=map.get(key)||{client:j.client,phone:j.phone,address:j.address,last:j.date,count:0};prev.count++;prev.last=prev.last>j.date?prev.last:j.date;prev.address=prev.address||j.address;map.set(key,prev)});const list=[...map.values()].filter(x=>`${x.client} ${x.phone} ${x.address}`.toLowerCase().includes(q)).sort((a,b)=>b.last.localeCompare(a.last));$('#clientsList').innerHTML=list.length?list.map(x=>`<article class="client-card"><b>${esc(x.client||'Без имени')}</b><span>${esc(x.phone||'')}</span><small>${esc(x.address||'')} · ${x.count} выезд${x.count===1?'':'а'}</small></article>`).join(''):'<div class="muted">Клиентов пока нет</div>';}
function render(){window.__montajiProfileState=state;window.dispatchEvent(new CustomEvent('montaji:runtime',{detail:{user,state,notes}}));renderToday();renderCalendar();renderUpcoming();renderExpenses();renderMoney();renderClients();renderNotes();}
function switchScreen(id){$$('.screen').forEach(s=>s.classList.toggle('active',s.id===id));$$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.screen===id));}
function bindUI(){bindAuth();$('#addBtn').onclick=()=>openJob();$$('.nav').forEach(b=>b.onclick=()=>switchScreen(b.dataset.screen));$('#todayIncomeBtn').onclick=()=>openJob(null,today(),freeSlot(today()),'Доп. доход');$('#todayExpenseBtn').onclick=()=>openExpense();$('#todayExpenseBtn2').onclick=()=>openExpense();$('#todayNoteBtn').onclick=()=>openNote();$('#financeExpenseBtn').onclick=()=>openExpense();$('#clientSearch').oninput=renderClients;$('#prevMonth').onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()-1,1);renderCalendar()};$('#nextMonth').onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()+1,1);renderCalendar()};$('#jobForm').onsubmit=saveJob;$('#deleteBtn').onclick=deleteJob;$('#expenseForm')?.addEventListener('submit',saveExpense);$('#noteForm')?.addEventListener('submit',saveNoteForm);$$('[data-close]').forEach(b=>b.onclick=()=>modal(b.dataset.close,false));$('#jobDate').onchange=checkSlot;$('#jobSlot').onchange=checkSlot;$('#jobStatus').onchange=updateJobForm;$$('#typeTabs button').forEach(b=>b.onclick=()=>{editingType=b.dataset.type;$$('#typeTabs button').forEach(x=>x.classList.toggle('selected',x===b));updateJobForm()});$('#logoutBtn').onclick=async()=>{try{await F.authMod.signOut(auth)}catch(e){console.error(e)}};$('#backupBtn').onclick=downloadBackup;$('#restoreInput').onchange=restoreBackup;$('#exportExcelBtn').onclick=exportCsv;$('#exportExcelBtn2').onclick=exportCsv;window.addEventListener('online',()=>{online=true;if(user){loadServer();startRealtime()}});window.addEventListener('offline',()=>{online=false;serverReady=false;status('Нет интернета · запись заблокирована','offline')});}
function downloadBackup(){const blob=new Blob([JSON.stringify({version:5,data:state,notes},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`montaji-backup-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
async function restoreBackup(e){const file=e.target.files?.[0];if(!file)return;try{const data=JSON.parse(await file.text());if(!data?.data?.jobs||!Array.isArray(data.data.jobs))throw new Error('bad backup');if(!confirm('Восстановить резервную копию? Текущие данные будут заменены.'))return;await saveShared(()=>normalize(data.data));if(Array.isArray(data.notes))await saveNotes(()=>({notes:data.notes}));toast('Резервная копия восстановлена','success')}catch(err){console.error(err);toast('Не удалось восстановить резервную копию','error')}finally{e.target.value='';}}
function exportCsv(){const rows=[['Дата','Тип','Клиент','Телефон','Адрес','Источник','Слот','Сумма','Статус','Оплата','Комментарий'],...state.jobs.map(j=>[j.date,j.type,j.client,j.phone,j.address,j.store||j.source,j.slot,isMeasure(j)?j.measurePrice:j.price,j.status,j.paid?'Оплачено':'Долг',j.comment])];const csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(';')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`montaji-${today()}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
async function boot(){bindUI();try{await initFirebase();F.authMod.onAuthStateChanged(auth,async u=>{user=u;if(!u){showAuth(true);return;}showAuth(false);await loadServer();startRealtime()});}catch(e){console.error(e);authMessage('Не удалось подключить Firebase.',true);showAuth(true);}}
boot();