import { firebaseConfig } from './firebase-config.js';

const FIREBASE_VERSION = '10.14.1';
const DOC_PATH = ['appData', 'shared'];
const SLOTS = { '1': '10:00–12:00', '2': '14:00–16:00', '3': '3-й слот / резерв' };
const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const uid = () => crypto.randomUUID?.() || `${Date.now()}-${Math.random()}`;
const money = (n) => new Intl.NumberFormat('ru-RU').format(Math.round(Number(n) || 0)) + ' ₽';
const num = (v) => Math.max(0, Number(String(v ?? '').replace(',', '.')) || 0);
const dateKey = (d) => { const x = new Date(d); return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`; };
const today = () => dateKey(new Date());
const fmtDate = (d) => new Intl.DateTimeFormat('ru-RU', { weekday:'long', day:'numeric', month:'long' }).format(new Date(`${d}T12:00:00`));
const fmtShort = (d) => new Intl.DateTimeFormat('ru-RU', { day:'2-digit', month:'2-digit', year:'numeric' }).format(new Date(`${d}T12:00:00`));
const esc = (s) => String(s ?? '').replace(/[&<>"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const isDone = (j) => j.status === 'Выполнен';
const isCancelled = (j) => j.status === 'Отменён';
const activityDate = (j) => isDone(j) ? (j.completedDate || j.date) : j.date;
const emptyState = () => ({ jobs: [], expenses: [], version: 5 });
const normalize = (d) => ({
  jobs: Array.isArray(d?.jobs) ? d.jobs.map(j => ({ ...j, id:j.id||uid(), date:j.date||today(), slot:String(j.slot||'1'), type:j.type||'Монтаж', client:j.client||'', price:num(j.price), status:j.status||'Запланирован', paid:j.paid!==false, completedDate:j.completedDate||'' })) : [],
  expenses: Array.isArray(d?.expenses) ? d.expenses.map(e => ({ ...e, id:e.id||uid(), date:e.date||today(), amount:num(e.amount), category:e.category||'Прочее', comment:e.comment||'' })) : [],
  version:5
});

let F, auth, db, user, unsubscribe=null, state=emptyState(), serverReady=false, online=navigator.onLine;
let month=new Date(new Date().getFullYear(),new Date().getMonth(),1), financePeriod='day', editType='Монтаж';

function status(text,kind='normal'){const el=$('#syncStatus');if(el){el.textContent=text;el.dataset.state=kind;}}
function toast(text,kind='normal'){let el=$('#toast');if(!el){el=document.createElement('div');el.id='toast';document.body.append(el);}el.textContent=text;el.dataset.state=kind;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.remove(),3200);}
function modal(id,open=true){const el=$(`#${id}`);if(!el)return;el.classList.toggle('open',open);el.setAttribute('aria-hidden',String(!open));}
function showAuth(show){$('#authScreen')?.classList.toggle('hidden',!show);$('#app')?.classList.toggle('hidden',show);}

async function initFirebase(){const [appMod,authMod,fs]=await Promise.all([import(`https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-app.js`),import(`https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-auth.js`),import(`https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-firestore.js`)]);const app=appMod.initializeApp(firebaseConfig,'montaji-aa-v5');auth=authMod.getAuth(app);db=fs.getFirestore(app);F={...fs,authMod};}
function authError(e){return ({'auth/invalid-credential':'Неверный email или пароль.','auth/invalid-email':'Проверьте email.','auth/user-disabled':'Доступ отключён.','auth/too-many-requests':'Слишком много попыток. Попробуйте позже.','auth/email-already-in-use':'Этот email уже зарегистрирован.','auth/weak-password':'Пароль должен быть не короче 6 символов.','auth/operation-not-allowed':'В Firebase не включён Email/Password.','auth/network-request-failed':'Нет соединения.'}[e?.code]||e?.message||'Ошибка авторизации.');}
function authMessage(text,error=false){const el=$('#authMessage');if(el){el.textContent=text;el.className=`auth-message${error?' auth-message--error':''}`;}}
function bindAuth(){$('#authForm').onsubmit=async e=>{e.preventDefault();const email=$('#authEmail').value.trim(),pass=$('#authPassword').value;if(!online)return authMessage('Нет интернета.',true);if(!email||!pass)return authMessage('Введите email и пароль.',true);authMessage('Входим…');try{await F.authMod.signInWithEmailAndPassword(auth,email,pass);}catch(err){authMessage(authError(err),true);}};$('#signUpBtn').onclick=async()=>{const email=$('#authEmail').value.trim(),pass=$('#authPassword').value;if(!email||!pass)return authMessage('Введите email и пароль.',true);if(pass.length<6)return authMessage('Пароль должен быть не короче 6 символов.',true);try{const c=await F.authMod.createUserWithEmailAndPassword(auth,email,pass);await F.authMod.sendEmailVerification(c.user);await F.authMod.signOut(auth);authMessage('Письмо отправлено. Подтвердите email и войдите.');}catch(err){authMessage(authError(err),true);}};$('#resetBtn').onclick=async()=>{const email=$('#authEmail').value.trim();if(!email)return authMessage('Введите email.',true);try{await F.authMod.sendPasswordResetEmail(auth,email);authMessage('Ссылка для сброса отправлена.');}catch(err){authMessage(authError(err),true);}};}

async function loadShared(){if(!user||!online){serverReady=false;state=emptyState();render();status('Нет интернета · данные не загружены','offline');return;}status('Подключаем общую базу…');try{const snap=await F.getDocFromServer(F.doc(db,...DOC_PATH));state=snap.exists()?normalize(snap.data().data):emptyState();serverReady=true;render();status('● Общая база · синхронизировано','online');}catch(err){serverReady=false;state=emptyState();render();status('База недоступна','offline');toast('Не удалось получить данные с сервера.','error');}}
function startRealtime(){if(!user||!online)return;if(unsubscribe)unsubscribe();unsubscribe=F.onSnapshot(F.doc(db,...DOC_PATH),snap=>{if(!online)return;state=snap.exists()?normalize(snap.data().data):emptyState();serverReady=true;render();status('● Общая база · обновлено','online');},()=>{serverReady=false;render();status('Нет связи с общей базой','offline');});}
async function saveShared(mutator){if(!serverReady||!online||!user)throw new Error('OFFLINE');const ref=F.doc(db,...DOC_PATH);await F.runTransaction(db,async tx=>{const snap=await tx.get(ref),current=snap.exists()?normalize(snap.data().data):emptyState(),next=normalize(await mutator(current));tx.set(ref,{data:next,version:5,updatedAt:F.serverTimestamp(),updatedBy:user.uid},{merge:true});});}

function jobsForDate(d){return state.jobs.filter(j=>!isCancelled(j)&&j.date===d);}
function activeJobs(d){return jobsForDate(d).filter(j=>!isDone(j));}
function montageCount(d){return activeJobs(d).filter(j=>j.type==='Монтаж').length;}
function freeSlot(d){const used=new Set(activeJobs(d).map(j=>String(j.slot)));return ['1','2','3'].find(s=>!used.has(s))||'3';}
function weekBounds(ref=new Date()){const d=new Date(ref),day=(d.getDay()+6)%7,start=new Date(d),end=new Date(d);start.setDate(d.getDate()-day);end.setDate(start.getDate()+6);return [dateKey(start),dateKey(end)];}
function monthBounds(ref=new Date()){return [dateKey(new Date(ref.getFullYear(),ref.getMonth(),1)),dateKey(new Date(ref.getFullYear(),ref.getMonth()+1,0))];}
function periodBounds(period){const now=new Date();if(period==='day')return[today(),today()];if(period==='week')return weekBounds(now);if(period==='month')return monthBounds(now);return['0000-01-01','9999-12-31'];}
function totals(period){const[a,b]=periodBounds(period),income=state.jobs.filter(j=>!isCancelled(j)&&isDone(j)&&activityDate(j)>=a&&activityDate(j)<=b).reduce((s,j)=>s+j.price,0),expenses=state.expenses.filter(e=>e.date>=a&&e.date<=b).reduce((s,e)=>s+e.amount,0),unpaid=state.jobs.filter(j=>!isCancelled(j)&&isDone(j)&&j.paid===false&&activityDate(j)>=a&&activityDate(j)<=b).reduce((s,j)=>s+j.price,0);return{income,expenses,net:income-expenses,unpaid};}
function mapLinks(address){const q=encodeURIComponent(address);return`<a class="map-chip" href="https://yandex.ru/maps/?text=${q}" target="_blank" rel="noopener">Яндекс</a><a class="map-chip" href="https://2gis.ru/search/${q}" target="_blank" rel="noopener">2ГИС</a>`;}
function jobCard(j){const phone=(j.phone||'').replace(/[^\d+]/g,'');return`<article class="job-card ${isDone(j)?'job-done':''}"><div class="job-top"><div><div class="job-client">${esc(j.client)}</div><div class="job-meta">${esc(SLOTS[j.slot]||'')} · ${esc(j.type)}${j.store?' · '+esc(j.store):''}</div></div><div class="amount">${money(j.price)}</div></div><div class="job-details">${j.address?`<div class="detail-line">📍 ${esc(j.address)}</div>`:''}${j.comment?`<div class="detail-line">${esc(j.comment)}</div>`:''}${isDone(j)?`<div class="status-pill">Выполнен · ${esc(fmtShort(activityDate(j)))}${j.paid===false?' · долг':''}</div>`:''}</div><div class="actions">${j.address?mapLinks(j.address):''}${phone?`<a class="action-chip" href="tel:${esc(phone)}">Позвонить</a>`:''}<button class="action-chip edit" data-id="${esc(j.id)}">Изменить</button></div></article>`;}
function renderToday(){const d=today(),jobs=jobsForDate(d),t=totals('day'),w=totals('week'),m=totals('month');$('#todayIncome').textContent=money(t.net);$('#todayGross').textContent=money(t.income);$('#todayExpense').textContent=money(t.expenses);$('#todayLoad').textContent=`${montageCount(d)}/3`,$('#todayProgress').style.width=Math.min(100,montageCount(d)/3*100)+'%',$('#todayWeek').textContent=money(w.net),$('#todayMonth').textContent=money(m.net);const advice=[],tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+1);const tc=montageCount(dateKey(tomorrow)),late=state.jobs.filter(j=>!isCancelled(j)&&!isDone(j)&&j.date<d).length;if(late)advice.push(`⚠️ ${late} просроченных выездов — проверь статус.`);if(tc===3)advice.push('🔥 Завтра 3/3 монтажей — день полностью загружен.');else if(tc===2)advice.push('✨ Завтра осталось одно монтажное окно.');if(t.unpaid)advice.push(`💰 ${money(t.unpaid)} выполненных работ ещё не оплачено.`);$('#insights').innerHTML=(advice.slice(0,3).map(x=>`<div class="insight">${x}</div>`).join('')||'<div class="insight">✨ На сегодня всё спокойно.</div>');$('#todayList').innerHTML=jobs.length?jobs.sort((a,b)=>String(a.slot).localeCompare(String(b.slot))).map(jobCard).join(''):'<div class="empty-card">Сегодня нет выездов. Можно спокойно добавить работу.</div>';bindEditButtons();const upcoming=[];for(let i=1;i<=7;i++){const x=new Date();x.setDate(x.getDate()+i);const k=dateKey(x),js=activeJobs(k);if(js.length)upcoming.push({k,x,js});}$('#upcoming').innerHTML=upcoming.slice(0,5).map(o=>`<button class="upcoming" data-date="${o.k}"><b>${o.x.getDate()}</b><span>${esc(o.js[0].client)}</span><em>${o.js.length} выезд · ${money(o.js.reduce((s,j)=>s+j.price,0))}</em>›</button>`).join('')||'<div class="muted">Ближайшие дни свободны.</div>';$$('.upcoming').forEach(b=>b.onclick=()=>openDay(b.dataset.date));}
function renderCalendar(){const y=month.getFullYear(),m=month.getMonth(),start=(new Date(y,m,1).getDay()+6)%7,last=new Date(y,m+1,0).getDate();let h='';for(let i=0;i<start;i++)h+='<div class="day blank"></div>';for(let n=1;n<=last;n++){const k=dateKey(new Date(y,m,n)),c=montageCount(k),j=activeJobs(k).length;h+=`<button class="day ${c>=3?'full':c===2?'busy':c?'partial':''} ${k===today()?'today':''}" data-date="${k}"><b>${n}</b><span>${j} выезд</span><i>${c}/3</i></button>`;}$('#scheduleMonth').textContent=new Intl.DateTimeFormat('ru-RU',{month:'long',year:'numeric'}).format(month);$('#calendar').innerHTML=h;$$('.day[data-date]').forEach(b=>b.onclick=()=>openDay(b.dataset.date));}
function openDay(d){const js=jobsForDate(d),pending=js.filter(j=>!isDone(j)),slots=['1','2','3'].map(s=>{const j=pending.find(x=>String(x.slot)===s);return`<div class="slot"><div class="slot-title">${SLOTS[s]}</div>${j?jobCard(j):`<button class="free-slot" data-slot="${s}">＋ Свободное окно</button>`}</div>`;}).join(''),completed=js.filter(isDone).map(jobCard).join(''),m=document.createElement('div');m.className='modal open';m.innerHTML=`<div class="backdrop"></div><div class="sheet"><div class="handle"></div><div class="sheet-head"><div><div class="eyebrow">График</div><h2>${esc(fmtDate(d))}</h2></div><button class="circle-btn" data-close>×</button></div><div class="day-actions"><button id="dayAdd">＋ Выезд</button><button id="dayIncome">＋ Доход</button><button id="dayExpense">− Расход</button></div>${slots}${completed?`<h3 class="sheet-section">Выполнено</h3>${completed}`:''}</div>`;document.body.append(m);m.querySelector('.backdrop').onclick=()=>m.remove();m.querySelector('[data-close]').onclick=()=>m.remove();m.querySelector('#dayAdd').onclick=()=>{m.remove();openJob(null,d,freeSlot(d),'Монтаж')};m.querySelector('#dayIncome').onclick=()=>{m.remove();openJob(null,d,freeSlot(d),'Доп. доход')};m.querySelector('#dayExpense').onclick=()=>{m.remove();openExpense(d)};m.querySelectorAll('.free-slot').forEach(b=>b.onclick=()=>{m.remove();openJob(null,d,b.dataset.slot,'Монтаж')});m.querySelectorAll('.edit').forEach(b=>b.onclick=()=>{m.remove();openJob(b.dataset.id)});}
function openJob(id=null,d=today(),slot=freeSlot(d),type='Монтаж'){const j=id?state.jobs.find(x=>x.id===id):null;editType=j?.type||type;$('#modalTitle').textContent=j?'Изменить выезд':'Новый выезд';$('#jobId').value=j?.id||'';$('#jobDate').value=j?.date||d;$('#jobSlot').value=j?.slot||slot;$('#jobClient').value=j?.client||'';$('#jobPhone').value=j?.phone||'';$('#jobPrice').value=j?.price||'';$('#jobAddress').value=j?.address||'';$('#jobStore').value=j?.store||'';$('#jobStatus').value=j?.status||(type==='Доп. доход'?'Выполнен':'Запланирован');$('#jobCompletedDate').value=j?.completedDate||j?.date||d;$('#jobPaid').value=j?.paid===false?'no':'yes';$('#jobComment').value=j?.comment||'';$$('#typeTabs button').forEach(b=>b.classList.toggle('selected',b.dataset.type===editType));toggleDone();checkSlot();modal('jobModal',true);}
function toggleDone(){$('#completedDateWrap').style.display=$('#jobStatus').value==='Выполнен'?'grid':'none';}
function checkSlot(){const d=$('#jobDate').value,s=$('#jobSlot').value,id=$('#jobId').value,conflict=state.jobs.find(j=>j.id!==id&&!isCancelled(j)&&!isDone(j)&&j.type==='Монтаж'&&j.date===d&&String(j.slot)===s&&editType==='Монтаж'),w=$('#slotWarning');w.classList.toggle('hidden',!conflict);if(conflict)w.textContent=`Слот занят: ${conflict.client}.`;}
async function saveJob(e){e.preventDefault();if(!serverReady)return toast('Нет соединения с общей базой.','error');const id=$('#jobId').value||uid(),d=$('#jobDate').value,s=$('#jobSlot').value,client=$('#jobClient').value.trim();if(!d||!client)return;const conflict=state.jobs.find(j=>j.id!==id&&!isCancelled(j)&&!isDone(j)&&j.type==='Монтаж'&&j.date===d&&String(j.slot)===s&&editType==='Монтаж');if(conflict)return toast(`Слот занят: ${conflict.client}`,'error');const job={id,date:d,slot:s,type:editType,client,phone:$('#jobPhone').value.trim(),price:num($('#jobPrice').value),address:$('#jobAddress').value.trim(),store:$('#jobStore').value.trim(),status:$('#jobStatus').value,completedDate:$('#jobStatus').value==='Выполнен'?($('#jobCompletedDate').value||d):'',paid:$('#jobPaid').value!=='no',comment:$('#jobComment').value.trim()};try{await saveShared(cur=>{const jobs=[...cur.jobs],i=jobs.findIndex(x=>x.id===id);i<0?jobs.push(job):jobs[i]={...jobs[i],...job};return{...cur,jobs};});modal('jobModal',false);toast('Сохранено','success');}catch(err){toast('Не удалось сохранить.','error');}}
async function deleteJob(){const id=$('#jobId').value;if(!id)return modal('jobModal',false);if(!confirm('Удалить этот выезд?'))return;try{await saveShared(cur=>({...cur,jobs:cur.jobs.filter(j=>j.id!==id)}));modal('jobModal',false);toast('Удалено','success');}catch(e){toast('Не удалось удалить','error');}}
function openExpense(d=today(),existing=null){const m=document.createElement('div');m.className='modal open';m.innerHTML=`<div class="backdrop"></div><div class="sheet"><div class="handle"></div><div class="sheet-head"><div><div class="eyebrow">Финансы</div><h2>${existing?'Изменить расход':'Новый расход'}</h2></div><button class="circle-btn" data-close>×</button></div><label>Дата<input id="eDate" type="date" value="${esc(existing?.date||d)}"></label><label>Сумма<input id="eAmount" type="number" min="0.01" step="0.01" inputmode="decimal" placeholder="180" value="${existing?.amount??''}"></label><label>Категория<input id="eCat" placeholder="Топливо, парковка, аренда…" value="${esc(existing?.category||'')}"></label><label>Комментарий<textarea id="eComment" rows="3" placeholder="Например: аренда машины">${esc(existing?.comment||'')}</textarea></label><button class="primary" id="saveE">${existing?'Сохранить изменения':'Сохранить расход'}</button></div>`;document.body.append(m);m.querySelector('.backdrop').onclick=()=>m.remove();m.querySelector('[data-close]').onclick=()=>m.remove();m.querySelector('#saveE').onclick=async()=>{const amount=num($('#eAmount').value),date=$('#eDate').value;if(!(amount>0)||!date)return toast('Укажите дату и сумму','error');try{await saveShared(cur=>{const expenses=[...cur.expenses],item={id:existing?.id||uid(),date,amount,category:$('#eCat').value.trim()||'Прочее',comment:$('#eComment').value.trim()};if(existing){const i=expenses.findIndex(x=>x.id===existing.id);if(i>=0)expenses[i]=item;else expenses.push(item);}else expenses.push(item);return{...cur,expenses};});m.remove();toast('Расход сохранён','success');}catch(e){toast('Не удалось сохранить расход','error');}};}
function renderMoney(){const t=totals('day'),w=totals('week'),m=totals('month'),a=totals('all'),current=totals(financePeriod);$('#moneyTotal').textContent=money(current.net);$('#moneyPeriod').textContent={day:'Сегодня',week:'Эта неделя',month:'Этот месяц',all:'За всё время'}[financePeriod];$('#moneyGrid').innerHTML=`<div><small>Доход</small><b>${money(current.income)}</b></div><div><small>Расходы</small><b>${money(current.expenses)}</b></div><div><small>Чистыми</small><b>${money(current.net)}</b></div><div><small>Не оплачено</small><b>${money(current.unpaid)}</b></div>`;$('#moneyHighlights').innerHTML=`<button data-fin="day"><span>День</span><b>${money(t.net)}</b><em>${money(t.expenses)} расход</em></button><button data-fin="week"><span>Неделя</span><b>${money(w.net)}</b><em>${money(w.expenses)} расход</em></button><button data-fin="month"><span>Месяц</span><b>${money(m.net)}</b><em>${money(m.expenses)} расход</em></button><button data-fin="all"><span>Всё время</span><b>${money(a.net)}</b><em>${money(a.expenses)} расход</em></button>`;$$('#moneyHighlights button').forEach(b=>b.onclick=()=>{financePeriod=b.dataset.fin;renderMoney();});const by={};state.jobs.filter(j=>!isCancelled(j)&&isDone(j)).forEach(j=>by[j.store||'Без магазина']=(by[j.store||'Без магазина']||0)+j.price);$('#storeBreakdown').innerHTML=Object.entries(by).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="store-row"><span>${esc(k)}</span><b>${money(v)}</b></div>`).join('')||'<div class="muted">Доходов пока нет.</div>';$('#financeAdvice').innerHTML=current.unpaid?`<div class="insight">💰 ${money(current.unpaid)} выполненных работ ещё не оплачено.</div>`:'<div class="insight">✨ Все выполненные работы в выбранном периоде оплачены.</div>';$('#expenseArchive').innerHTML=state.expenses.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,30).map(e=>`<div class="expense-row"><div><b>${esc(e.category)}</b><small>${fmtShort(e.date)}${e.comment?' · '+esc(e.comment):''}</small></div><strong>− ${money(e.amount)}</strong><button class="mini-edit" data-expense="${esc(e.id)}">Изменить</button></div>`).join('')||'<div class="muted">Расходов пока нет.</div>';$$('.mini-edit').forEach(b=>b.onclick=()=>{const e=state.expenses.find(x=>x.id===b.dataset.expense);if(e)openExpense(e.date,e);});}
function renderClients(){const q=($('#clientSearch').value||'').toLowerCase(),map=new Map();state.jobs.forEach(j=>{const hay=`${j.client} ${j.phone||''} ${j.address||''}`.toLowerCase();if(q&&!hay.includes(q))return;const k=j.phone||j.client;if(k&&!map.has(k))map.set(k,j);});$('#clientsList').innerHTML=[...map.values()].sort((a,b)=>activityDate(b).localeCompare(activityDate(a))).map(j=>`<article class="job-card"><div class="job-top"><div><div class="job-client">${esc(j.client)}</div><div class="job-meta">${esc(j.phone||'Телефон не указан')}</div></div><div class="amount">${money(j.price)}</div></div><div class="job-details">${j.address?`<div>${esc(j.address)}</div>`:''}${j.paid===false?'<div class="debt">Не оплачено</div>':''}</div><div class="actions"><button class="action-chip edit" data-id="${esc(j.id)}">Открыть</button>${j.address?mapLinks(j.address):''}</div></article>`).join('')||'<div class="empty-card">Клиенты появятся после первого выезда.</div>';bindEditButtons();}
function bindEditButtons(){$$('.edit').forEach(b=>b.onclick=()=>openJob(b.dataset.id));}
function csvEscape(v){const s=String(v??'');return`"${s.replace(/"/g,'""')}"`;}
function downloadFile(text,name,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([text],{type}));a.href=url;a.download=name;document.body.append(a);a.click();setTimeout(()=>{URL.revokeObjectURL(url);a.remove();},1000);}
function exportExcel(){const rows=[['Тип','Дата','Дата выполнения','Слот','Клиент / операция','Телефон','Сумма','Статус','Оплата','Магазин','Адрес','Комментарий']];state.jobs.slice().sort((a,b)=>activityDate(a).localeCompare(activityDate(b))).forEach(j=>rows.push(['Монтаж/выезд',j.date,j.completedDate||'',SLOTS[j.slot]||'',j.client,j.phone||'',j.price,j.status,j.paid?'Оплачено':'Долг',j.store||'',j.address||'',j.comment||'']));state.expenses.slice().sort((a,b)=>a.date.localeCompare(b.date)).forEach(e=>rows.push(['Расход',e.date,'','','','',-e.amount,'','','',e.category,e.comment||'']));const csv='\uFEFF'+rows.map(r=>r.map(csvEscape).join(';')).join('\r\n');downloadFile(csv,`montaji-aa-${today()}.csv`,'text/csv;charset=utf-8');toast('Excel-файл сформирован','success');}
function exportJson(){downloadFile(JSON.stringify(state,null,2),`montaji-aa-backup-${today()}.json`,'application/json');toast('Резервная копия сохранена','success');}
async function restoreJson(file){try{const parsed=normalize(JSON.parse(await file.text()));if(!confirm('Заменить общую базу этой резервной копией?'))return;await saveShared(()=>parsed);toast('База восстановлена','success');}catch(e){toast('Не удалось восстановить файл','error');}}
function render(){if(!$('#app'))return;$('#topDate').textContent=new Intl.DateTimeFormat('ru-RU',{weekday:'long',day:'numeric',month:'long'}).format(new Date());renderToday();renderCalendar();renderMoney();renderClients();}
function bindUI(){$('#themeBtn').onclick=()=>document.body.classList.toggle('dark');$('#addBtn').onclick=()=>openJob();$('#todayIncomeBtn').onclick=()=>openJob(null,today(),freeSlot(today()),'Доп. доход');$('#todayExpenseBtn').onclick=()=>openExpense();$('#financeExpenseBtn').onclick=()=>openExpense();$('#exportExcelBtn').onclick=exportExcel;$('#backupBtn').onclick=exportJson;$('#restoreInput').onchange=e=>{const f=e.target.files?.[0];if(f)restoreJson(f);e.target.value='';};$('#prevMonth').onclick=()=>{month.setMonth(month.getMonth()-1);renderCalendar();};$('#nextMonth').onclick=()=>{month.setMonth(month.getMonth()+1);renderCalendar();};$$('.nav').forEach(b=>b.onclick=()=>{$$('.screen').forEach(s=>s.classList.toggle('active',s.id===b.dataset.screen));$$('.nav').forEach(n=>n.classList.toggle('active',n===b));});$('#clientSearch').oninput=renderClients;$('#jobForm').onsubmit=saveJob;$('#deleteBtn').onclick=deleteJob;$('#jobStatus').onchange=()=>{toggleDone();checkSlot();};$('#jobDate').onchange=checkSlot;$('#jobSlot').onchange=checkSlot;$$('#typeTabs button').forEach(b=>b.onclick=()=>{editType=b.dataset.type;$$('#typeTabs button').forEach(x=>x.classList.toggle('selected',x===b));});$$('[data-close="jobModal"]').forEach(b=>b.onclick=()=>modal('jobModal',false));$('#logoutBtn').onclick=()=>F.authMod.signOut(auth);addEventListener('online',async()=>{online=true;await loadShared();if(serverReady)startRealtime();});addEventListener('offline',()=>{online=false;serverReady=false;state=emptyState();render();status('Нет интернета · серверные данные скрыты','offline');});}
async function onUser(u){user=u;if(unsubscribe){unsubscribe();unsubscribe=null;}if(!u){serverReady=false;state=emptyState();showAuth(true);render();status('Требуется вход');return;}if(!u.emailVerified){await F.authMod.signOut(auth);showAuth(true);authMessage('Подтвердите email по ссылке из письма.',true);return;}showAuth(false);await loadShared();if(serverReady)startRealtime();}
(async()=>{try{bindUI();bindAuth();await initFirebase();F.authMod.onAuthStateChanged(auth,onUser);}catch(e){console.error(e);showAuth(true);authMessage('Не удалось запустить приложение. Проверьте Firebase.',true);}})();
