const KEY='montaji-aa-data-v4';
const SLOT_LABELS={1:'10:00–12:00',2:'14:00–16:00',3:'3-й слот / резерв'};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
const money=n=>new Intl.NumberFormat('ru-RU').format(Math.round(Number(n)||0))+' ₽';
const today=()=>new Date().toISOString().slice(0,10);
function read(){try{return JSON.parse(localStorage.getItem(KEY)||'null')||{jobs:[],expenses:[]}}catch{return {jobs:[],expenses:[]}}}
function write(x){localStorage.setItem(KEY,JSON.stringify({...x,version:4}));}
function allRows(){const s=read();const jobs=(s.jobs||[]).map(j=>({...j,rowType:'Выезд',activityDate:j.status==='Выполнен'?(j.completedDate||j.date):j.date}));const expenses=(s.expenses||[]).map(e=>({id:e.id,date:e.date,slot:'',type:'Расход',client:e.category||'Расход',phone:'',price:-Math.abs(Number(e.amount||0)),address:'',store:'',status:'Учтён',comment:e.comment||'',rowType:'Расход',activityDate:e.date}));return [...jobs,...expenses].sort((a,b)=>(b.activityDate||'').localeCompare(a.activityDate||''));}
function openArchive(){let modal=document.getElementById('archiveModal');if(modal)modal.remove();modal=document.createElement('div');modal.className='modal open';modal.id='archiveModal';modal.innerHTML=`<div class="backdrop" data-close></div><div class="sheet archive-sheet"><div class="handle"></div><div class="sheet-head"><div><div class="eyebrow">История</div><h2>Архив всех выездов</h2></div><button class="circle-btn" data-close>×</button></div><div class="archive-tools"><input id="archiveSearch" class="search" placeholder="Поиск клиента, адреса, комментария"><div class="period-tabs" id="archiveTabs"><button class="selected" data-filter="all">Все</button><button data-filter="month">Месяц</button><button data-filter="done">Выполнены</button><button data-filter="montage">Монтажи</button></div><div class="quick-inline"><button class="text-btn" id="archiveExcel">↓ Excel</button><button class="text-btn" id="archiveJson">↓ JSON</button></div></div><div id="archiveList" class="job-list"></div></div>`;document.body.append(modal);modal.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>modal.remove());let filter='all';const render=()=>{const q=(modal.querySelector('#archiveSearch').value||'').toLowerCase();const now=today();let rows=allRows().filter(j=>`${j.client} ${j.address} ${j.comment} ${j.phone}`.toLowerCase().includes(q));if(filter==='month')rows=rows.filter(j=>(j.activityDate||'').slice(0,7)===now.slice(0,7));if(filter==='done')rows=rows.filter(j=>j.status==='Выполнен');if(filter==='montage')rows=rows.filter(j=>j.type==='Монтаж');modal.querySelector('#archiveList').innerHTML=rows.length?rows.map(j=>`<article class="job-card"><div class="job-card__top"><div><div class="job-card__client">${esc(j.client)}</div><div class="job-card__meta">${esc(j.activityDate||j.date||'')} · ${esc(j.type||j.rowType)}${j.slot?` · ${SLOT_LABELS[j.slot]||''}`:''}</div></div><div><span class="pill">${j.price<0?'− ':''}${money(Math.abs(Number(j.price||0)))}</span></div></div><div class="job-card__details"><div>${esc(j.status||'')}${j.address?' · '+esc(j.address):''}</div>${j.comment?`<div>◦ ${esc(j.comment)}</div>`:''}</div>${j.rowType==='Выезд'?`<div class="job-card__actions"><button class="action-link" data-edit="${esc(j.id)}">Открыть / изменить</button></div>`:''}</article>`).join(''):'<div class="job-card"><div class="job-card__client">Ничего не найдено</div><div class="job-card__meta">История хранится в общей базе.</div></div>';modal.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEdit(b.dataset.id));};modal.querySelector('#archiveSearch').oninput=render;modal.querySelectorAll('#archiveTabs button').forEach(b=>b.onclick=()=>{modal.querySelectorAll('#archiveTabs button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');filter=b.dataset.filter;render()});modal.querySelector('#archiveExcel').onclick=exportExcel;modal.querySelector('#archiveJson').onclick=exportJson;render();}
function openEdit(id){const s=read(),j=(s.jobs||[]).find(x=>x.id===id);if(!j)return;const m=document.createElement('div');m.className='modal open';m.innerHTML=`<div class="backdrop" data-close></div><div class="sheet"><div class="handle"></div><div class="sheet-head"><div><div class="eyebrow">Архив</div><h2>Изменить выезд</h2></div><button class="circle-btn" data-close>×</button></div><form id="archiveEdit"><div class="form-row"><label>Дата<input id="aeDate" type="date" value="${esc(j.date||'')}" required></label><label>Дата выполнения<input id="aeCompleted" type="date" value="${esc(j.completedDate||j.date||'')}"></label></div><label>Клиент / за что<input id="aeClient" value="${esc(j.client||'')}" required></label><div class="form-row"><label>Тип<select id="aeType">${['Монтаж','Замер','Рекламация','Доставка','Сервис','Доп. доход'].map(x=>`<option ${x===j.type?'selected':''}>${x}</option>`).join('')}</select></label><label>Сумма<input id="aePrice" type="number" min="0" step="100" value="${Number(j.price||0)}"></label></div><label>Телефон<input id="aePhone" value="${esc(j.phone||'')}"></label><label>Адрес<textarea id="aeAddress" rows="2">${esc(j.address||'')}</textarea></label><div class="form-row"><label>Магазин<input id="aeStore" value="${esc(j.store||'')}"></label><label>Статус<select id="aeStatus">${['Запланирован','Подтверждён','В пути','На объекте','Выполнен','Перенос','Отменён'].map(x=>`<option ${x===j.status?'selected':''}>${x}</option>`).join('')}</select></label></div><label>Комментарий<textarea id="aeComment" rows="3">${esc(j.comment||'')}</textarea></label><div class="form-actions"><button class="primary">Сохранить</button><button class="danger ghost" type="button" id="aeDelete">Удалить</button></div></form></div>`;document.body.append(m);m.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>m.remove());m.querySelector('#archiveEdit').onsubmit=e=>{e.preventDefault();const i=s.jobs.findIndex(x=>x.id===id);s.jobs[i]={...j,date:$('#aeDate').value,completedDate:$('#aeStatus').value==='Выполнен'?($('#aeCompleted').value||$('#aeDate').value):'',client:$('#aeClient').value.trim(),type:$('#aeType').value,price:Number($('#aePrice').value||0),phone:$('#aePhone').value.trim(),address:$('#aeAddress').value.trim(),store:$('#aeStore').value.trim(),status:$('#aeStatus').value,comment:$('#aeComment').value.trim()};write(s);location.reload()};m.querySelector('#aeDelete').onclick=()=>{if(confirm('Удалить запись из архива?')){s.jobs=s.jobs.filter(x=>x.id!==id);write(s);location.reload()}};}
function rowsForExport(){return allRows().map(j=>({Дата:j.activityDate||j.date||'','Дата плановая':j.date||'','Клиент / за что':j.client||'','Тип':j.type||j.rowType||'','Статус':j.status||'','Сумма':Number(j.price||0),'Телефон':j.phone||'','Адрес':j.address||'','Магазин':j.store||'','Комментарий':j.comment||''}));}
function exportJson(){const blob=new Blob([JSON.stringify(read(),null,2)],{type:'application/json;charset=utf-8'});download(blob,`montaji-aa-backup-${today()}.json`)}
function exportCsv(){const rows=rowsForExport(),keys=Object.keys(rows[0]||{'Дата':''});const q=v=>'"'+String(v??'').replaceAll('"','""')+'"';const csv='\uFEFF'+[keys.map(q).join(';'),...rows.map(r=>keys.map(k=>q(r[k])).join(';'))].join('\n');download(new Blob([csv],{type:'text/csv;charset=utf-8'}),`montaji-aa-${today()}.csv`)}
async function exportExcel(){try{const XLSX=await import('https://cdn.jsdelivr.net/npm/xlsx@0.18.5/+esm');const rows=rowsForExport();const wb=XLSX.utils.book_new();const ws=XLSX.utils.json_to_sheet(rows);ws['!cols']=[{wch:12},{wch:14},{wch:28},{wch:16},{wch:16},{wch:12},{wch:20},{wch:38},{wch:22},{wch:60}];XLSX.utils.book_append_sheet(wb,ws,'Все выезды');const s=read();const ex=(s.expenses||[]).map(e=>({Дата:e.date,Категория:e.category||'',Сумма:Number(e.amount||0),Комментарий:e.comment||''}));XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(ex),'Расходы');XLSX.writeFile(wb,`montaji-aa-${today()}.xlsx`)}catch(e){console.warn(e);exportCsv()}}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000)}
function install(){const more=document.querySelector('#moreScreen .settings-card');if(!more||document.getElementById('archiveBtn'))return;const b=document.createElement('button');b.className='setting-row';b.id='archiveBtn';b.innerHTML='<span>Архив всех выездов</span><b>Открыть ›</b>';b.onclick=openArchive;more.prepend(b);const note=document.querySelector('#moreScreen .system-note');if(note)note.textContent='Общая база · локальная копия · Excel/JSON доступны в любой момент';}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(install,0));else setTimeout(install,0);
window.addEventListener('online',install);

// Финансовый блок главной: неделя Пн–Вс, текущий месяц и накопительный итог за всё время.
const moneyHomeDate=d=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`};
function moneyHomeWeek(){const d=new Date();d.setHours(12,0,0,0);const dow=(d.getDay()+6)%7;d.setDate(d.getDate()-dow);const start=moneyHomeDate(d);d.setDate(d.getDate()+6);return [start,moneyHomeDate(d)]}
function moneyHomeActivity(j){return j.status==='Выполнен'?(j.completedDate||j.date):j.date}
function moneyHomeSum(rows,start,end){return rows.filter(j=>j.status==='Выполнен'&&j.status!=='Отменён'&&moneyHomeActivity(j)>=start&&moneyHomeActivity(j)<=end).reduce((s,j)=>s+Number(j.price||0),0)}
function moneyHomeExpenseSum(expenses,start,end){return expenses.filter(e=>e.date>=start&&e.date<=end).reduce((s,e)=>s+Number(e.amount||0),0)}
function renderMoneyHome(){const s=read(),jobs=s.jobs||[],expenses=s.expenses||[],[weekStart,weekEnd]=moneyHomeWeek(),now=new Date(),monthStart=moneyHomeDate(new Date(now.getFullYear(),now.getMonth(),1)),monthEnd=moneyHomeDate(new Date(now.getFullYear(),now.getMonth()+1,0)),allStart='0000-01-01',allEnd='9999-12-31';const week=moneyHomeSum(jobs,weekStart,weekEnd),month=moneyHomeSum(jobs,monthStart,monthEnd),all=moneyHomeSum(jobs,allStart,allEnd),weekExpenses=moneyHomeExpenseSum(expenses,weekStart,weekEnd);const income=$('#todayIncome');if(income)income.textContent=money(week);const label=document.querySelector('.hero-label');if(label)label.textContent='доход за неделю';const sub=$('#todaySub');if(sub)sub.textContent=`Расходы за неделю: ${money(weekExpenses)} · Чистыми: ${money(week-weekExpenses)}`;let box=document.getElementById('moneyHomeSummary');if(!box){const hero=document.querySelector('.hero-card');if(!hero)return;box=document.createElement('div');box.id='moneyHomeSummary';box.className='money-home-summary';hero.appendChild(box)}const monthName=new Intl.DateTimeFormat('ru-RU',{month:'long'}).format(now).replace(/^./,c=>c.toUpperCase());box.innerHTML=`<div><span>За ${esc(monthName)}</span><b>${money(month)}</b></div><div><span>За всё время</span><b>${money(all)}</b></div><small>Неделя обновляется каждый понедельник · месяц — 1-го числа</small>`}
const moneyHomeStyle=document.createElement('style');moneyHomeStyle.textContent='#moneyHomeSummary{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:16px;padding-top:14px;border-top:1px solid rgba(255,255,255,.22)}#moneyHomeSummary>div{display:flex;flex-direction:column;gap:3px}#moneyHomeSummary span{font-size:13px;opacity:.78}#moneyHomeSummary b{font-size:18px}#moneyHomeSummary small{grid-column:1/-1;font-size:11px;opacity:.68;margin-top:3px}';document.head.appendChild(moneyHomeStyle);
renderMoneyHome();setInterval(renderMoneyHome,1000);window.addEventListener('storage',renderMoneyHome);
