import { firebaseConfig } from './firebase-config.js';
const FV='10.14.1';
const DOC=['appData','shared'];
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const money=n=>new Intl.NumberFormat('ru-RU').format(Math.round(Number(n)||0))+' ₽';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
let F,auth,db,user,unsub=null,ready=false,state={jobs:[],expenses:[]};
async function init(){const [appMod,authMod,fs]=await Promise.all([import(`https://www.gstatic.com/firebasejs/${FV}/firebase-app.js`),import(`https://www.gstatic.com/firebasejs/${FV}/firebase-auth.js`),import(`https://www.gstatic.com/firebasejs/${FV}/firebase-firestore.js`)]);const app=appMod.initializeApp(firebaseConfig,'montaji-aa-v8');auth=authMod.getAuth(app);db=fs.getFirestore(app);F={...fs,authMod};authMod.onAuthStateChanged(auth,u=>{user=u;if(u)startSync();else ready=false;});}
function normalize(d){return {jobs:Array.isArray(d?.jobs)?d.jobs.map(j=>({...j,id:j.id||uid(),date:j.date||today(),slot:String(j.slot??'1'),type:j.type||'Монтаж',client:j.client||'',price:Number(j.price)||0,status:j.status||'Запланирован',paid:j.paid!==false,completedDate:j.completedDate||''})):[],expenses:Array.isArray(d?.expenses)?d.expenses:[]};}
function startSync(){if(unsub)unsub();unsub=F.onSnapshot(F.doc(db,...DOC),snap=>{state=normalize(snap.exists()?snap.data()?.data:{});ready=true;refresh();},()=>{ready=false;});}
async function tx(mut){if(!ready||!user)throw Error('Нет соединения с общей базой');const ref=F.doc(db,...DOC);await F.runTransaction(db,async t=>{const s=await t.get(ref);const cur=normalize(s.exists()?s.data()?.data:{});const next=normalize(await mut(cur));t.set(ref,{data:next,version:8,updatedAt:F.serverTimestamp(),updatedBy:user.uid},{merge:true});});}
function toast(t,k='normal'){let e=$('#toast');if(!e){e=document.createElement('div');e.id='toast';document.body.append(e)}e.textContent=t;e.dataset.state=k;clearTimeout(toast.t);toast.t=setTimeout(()=>e.remove(),2800)}
function sheet(html){const m=document.createElement('div');m.className='modal open aa-v8-modal';m.innerHTML=`<div class="backdrop"></div><div class="sheet aa-v8-sheet"><div class="handle"></div>${html}</div>`;document.body.append(m);m.querySelector('.backdrop').onclick=()=>m.remove();m.querySelector('[data-close]')?.addEventListener('click',()=>m.remove());return m;}
function choice(){const m=sheet(`<div class="sheet-head"><div><div class="eyebrow">Новая запись</div><h2>Что добавляем?</h2></div><button class="circle-btn" data-close>×</button></div><div class="v8-choice-grid"><button data-c="montage"><b>＋</b><strong>Монтаж</strong><span>Выезд по графику</span></button><button data-c="measure"><b>⌖</b><strong>Замер</strong><span>Любое удобное время</span></button><button data-c="claim"><b>!</b><strong>Рекламация</strong><span>Повторный выезд</span></button><button data-c="delivery"><b>→</b><strong>Доставка</strong><span>Отдельный выезд</span></button><button data-c="income"><b>₽</b><strong>Доход</strong><span>Дополнительная оплата</span></button><button data-c="expense"><b>−</b><strong>Расход</strong><span>Топливо, аренда и т.д.</span></button></div>`);m.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>{const c=b.dataset.c;m.remove();if(c==='measure')openMeasure();else if(c==='expense')$('#financeExpenseBtn')?.click();else if(c==='income')$('#todayIncomeBtn')?.click();else openNativeJob({montage:'Монтаж',claim:'Рекламация',delivery:'Доставка'}[c]||'Монтаж');});}
function openNativeJob(type='Монтаж'){const modal=$('#jobModal');if(!modal)return;const d=today();$('#modalTitle').textContent='Новый выезд';$('#jobId').value='';$('#jobDate').value=d;$('#jobSlot').value=['1','2','3'].find(s=>!state.jobs.some(j=>j.type==='Монтаж'&&j.date===d&&String(j.slot)===s&&j.status!=='Выполнен'&&j.status!=='Отменён'))||'3';$('#jobClient').value='';$('#jobPhone').value='';$('#jobPrice').value='';$('#jobAddress').value='';$('#jobStore').value='';$('#jobStatus').value='Запланирован';$('#jobCompletedDate').value=d;$('#jobPaid').value='yes';$('#jobComment').value='';$$('#typeTabs button').forEach(b=>b.classList.toggle('selected',b.dataset.type===type));modal.classList.add('open');modal.setAttribute('aria-hidden','false');}
function openMeasure(j=null){const x=j||{};const m=sheet(`<div class="sheet-head"><div><div class="eyebrow">Замер</div><h2>${j?'Изменить замер':'Новый замер'}</h2></div><button class="circle-btn" data-close>×</button></div><div class="v8-measure-note"><b>Замер не занимает монтажный слот.</b><span>Можно утром, вечером или сразу после звонка.</span></div><form id="v8mf"><label>Дата<input id="v8d" type="date" required value="${esc(x.date||today())}"></label><label>Когда удобно?<input id="v8t" placeholder="08:30, после 18:00, вечером" value="${esc(x.measureTime||'')}"></label><label>Клиент<input id="v8c" required value="${esc(x.client||'')}" placeholder="ФИО клиента"></label><label>Телефон<input id="v8p" type="tel" value="${esc(x.phone||'')}"></label><label>Адрес<textarea id="v8a" rows="2">${esc(x.address||'')}</textarea></label><label>Магазин<input id="v8s" value="${esc(x.store||'')}" placeholder="ASTERA / LAVETRA DOORS"></label><div class="form-row"><label>Замер, ₽<input id="v8fee" type="number" min="0" value="${Number(x.measurePrice)||0}"></label><label>Оплата<select id="v8paid"><option value="no" ${x.measurePaid===true?'':'selected'}>Не оплачено</option><option value="yes" ${x.measurePaid===true?'selected':''}>Оплачено</option></select></label></div><label>Комментарий<textarea id="v8com" rows="3">${esc(x.comment||'')}</textarea></label><div class="form-actions"><button class="primary" type="submit">Сохранить замер</button>${j?'<button class="secondary" id="v8to" type="button">→ В монтаж</button>':''}</div></form>`);m.querySelector('#v8mf').onsubmit=async e=>{e.preventDefault();const item={id:x.id||uid(),type:'Замер',date:$('#v8d').value,slot:'0',client:$('#v8c').value.trim(),phone:$('#v8p').value.trim(),address:$('#v8a').value.trim(),store:$('#v8s').value.trim(),price:0,measurePrice:Math.max(0,Number($('#v8fee').value)||0),measurePaid:$('#v8paid').value==='yes',paid:$('#v8paid').value==='yes',status:x.status||'Запланирован',measureTime:$('#v8t').value.trim(),comment:$('#v8com').value.trim(),completedDate:''};if(!item.client)return toast('Укажите клиента','error');try{await tx(cur=>{const jobs=[...cur.jobs],i=jobs.findIndex(z=>z.id===item.id);if(i<0)jobs.push(item);else jobs[i]={...jobs[i],...item};return {...cur,jobs}});m.remove();toast('Замер сохранён','success')}catch(e){toast(e.message,'error')}};if(j)m.querySelector('#v8to').onclick=()=>{m.remove();convertMeasure(j)};}
function convertMeasure(j){const m=sheet(`<div class="sheet-head"><div><div class="eyebrow">Замер → монтаж</div><h2>Поставить монтаж</h2></div><button class="circle-btn" data-close>×</button></div><div class="v8-convert-card"><b>${esc(j.client)}</b><span>${esc(j.address||'Адрес не указан')}</span><small>Замер: ${money(j.measurePrice||0)}${j.measurePaid?' · оплачен':''}</small></div><form id="v8cf"><div class="form-row"><label>Дата<input id="v8md" type="date" required value="${esc(j.date||today())}"></label><label>Слот<select id="v8ms"><option value="1">10:00–12:00</option><option value="2">14:00–16:00</option><option value="3">3-й слот / резерв</option></select></label></div><label>Цена монтажа для клиента, ₽<input id="v8mp" type="number" min="0" required placeholder="6500"></label><div class="v8-convert-note">Оплаченный замер вычтем из суммы монтажа, чтобы не задвоить доход.</div><button class="primary" type="submit">Создать монтаж</button></form>`);m.querySelector('#v8cf').onsubmit=async e=>{e.preventDefault();const date=$('#v8md').value,slot=$('#v8ms').value,gross=Math.max(0,Number($('#v8mp').value)||0),fee=Math.max(0,Number(j.measurePrice)||0),credited=j.measurePaid===true?fee:0,net=Math.max(0,gross-credited);try{await tx(cur=>{const jobs=[...cur.jobs],i=jobs.findIndex(z=>z.id===j.id),conflict=jobs.find(z=>z.id!==j.id&&z.type==='Монтаж'&&z.status!=='Выполнен'&&z.status!=='Отменён'&&z.date===date&&String(z.slot)===slot);if(conflict)throw Error(`Слот занят: ${conflict.client}`);const next={...j,type:'Монтаж',date,slot,price:net,grossPrice:gross,measureConverted:true,measurePrice:fee,creditedMeasureFee:credited,status:'Запланирован',completedDate:'',paid:true};if(i>=0)jobs[i]=next;else jobs.push(next);return {...cur,jobs}});m.remove();toast(`Монтаж создан · ${money(net)} в учёте`,'success')}catch(e){toast(e.message||'Не удалось сохранить','error')}};}
function debt(j){const m=sheet(`<div class="sheet-head"><div><div class="eyebrow">Долг</div><h2>${esc(j.client)}</h2></div><button class="circle-btn" data-close>×</button></div><div class="v8-debt-hero"><span>К оплате</span><b>${money(j.price)}</b><small>Выполнен · ${esc(j.completedDate||j.date)}</small></div>${j.address?`<div class="v8-detail">📍 ${esc(j.address)}</div>`:''}${j.phone?`<div class="v8-detail">☎ ${esc(j.phone)}</div>`:''}<div class="form-actions"><button class="primary" id="v8pay">Отметить как оплачено</button></div>`);m.querySelector('#v8pay').onclick=async()=>{try{await tx(cur=>({...cur,jobs:cur.jobs.map(x=>x.id===j.id?{...x,paid:true}:x)}));m.remove();toast('Долг закрыт','success')}catch(e){toast('Не удалось сохранить','error')}};}
function refreshDebt(){const host=$('#financeAdvice');if(!host)return;const debts=state.jobs.filter(j=>j.type==='Монтаж'&&j.status==='Выполнен'&&j.paid===false);let box=$('#v8DebtBox');if(!debts.length){box?.remove();return}if(!box){box=document.createElement('div');box.id='v8DebtBox';box.className='chart-card v8-debt-box';host.after(box)}box.innerHTML=`<div class="section-head"><h2>Ожидаем оплату</h2><span class="v8-debt-total">${money(debts.reduce((s,j)=>s+j.price,0))}</span></div>${debts.map(j=>`<button class="v8-debt-row" data-debt="${esc(j.id)}"><span><b>${esc(j.client)}</b><small>${esc(j.store||'')} · ${esc(j.completedDate||j.date)}</small></span><strong>${money(j.price)}</strong><i>›</i></button>`).join('')}`;box.querySelectorAll('[data-debt]').forEach(b=>b.onclick=()=>{const j=state.jobs.find(x=>x.id===b.dataset.debt);if(j)debt(j)});}
function refreshMeasures(){const list=$('#todayList');if(!list)return;list.querySelectorAll('.job-card').forEach(card=>{if(card.querySelector('.job-meta')?.textContent.includes('Замер'))card.classList.add('v8-measure-card-hidden')});let box=$('#v8TodayMeasures');const ms=state.jobs.filter(j=>j.type==='Замер'&&j.date===today()&&j.status!=='Отменён');if(!ms.length){box?.remove();return}if(!box){box=document.createElement('section');box.id='v8TodayMeasures';box.className='v8-measure-section';list.before(box)}box.innerHTML=`<div class="section-head"><h2>Замеры сегодня</h2><span>${ms.length}</span></div>${ms.map(j=>`<article class="v8-measure-card"><div class="v8-measure-top"><div><b>${esc(j.client)}</b><small>${esc(j.measureTime||'Время не указано')}</small></div><strong>${j.measurePrice?money(j.measurePrice):'Бесплатно'}</strong></div>${j.address?`<div class="v8-detail">📍 ${esc(j.address)}</div>`:''}<div class="actions"><button class="action-chip" data-me="${esc(j.id)}">Изменить</button><button class="action-chip" data-convert="${esc(j.id)}">→ В монтаж</button></div></article>`).join('')}`;box.querySelectorAll('[data-me]').forEach(b=>b.onclick=()=>{const j=state.jobs.find(x=>x.id===b.dataset.me);if(j)openMeasure(j)});box.querySelectorAll('[data-convert]').forEach(b=>b.onclick=()=>{const j=state.jobs.find(x=>x.id===b.dataset.convert);if(j)convertMeasure(j)});}
function patchCalendar(){const cal=$('#calendar');if(cal)$$('#calendar .day[data-date]').forEach(b=>{const d=b.dataset.date,m=state.jobs.filter(j=>j.type==='Монтаж'&&j.status!=='Отменён'&&j.date===d).length,me=state.jobs.filter(j=>j.type==='Замер'&&j.status!=='Отменён'&&j.date===d).length;b.querySelector('i')?.replaceChildren(document.createTextNode(`${m}/3`));const s=b.querySelector('span');if(s)s.textContent=me?`${m+me} выезд · ${me} замер${me===1?'':'а'}`:`${m} выезд`;let mm=b.querySelector('.v8-measure-count');if(me&&!mm){mm=document.createElement('small');mm.className='v8-measure-count';b.append(mm)}if(mm)mm.textContent=me?`${me} замер${me===1?'':'а'}`:'';b.classList.toggle('partial',m===1);b.classList.toggle('busy',m===2);b.classList.toggle('full',m>=3)});const d=today(),m=state.jobs.filter(j=>j.type==='Монтаж'&&j.status!=='Отменён'&&j.date===d).length;$('#todayLoad')?.replaceChildren(document.createTextNode(`${m}/3`));if($('#todayProgress'))$('#todayProgress').style.width=Math.min(100,m/3*100)+'%';}
function bind(){const b=$('#addBtn');if(!b||b.dataset.v8)return;const n=b.cloneNode(true);b.replaceWith(n);n.dataset.v8='1';n.onclick=choice;}
function refresh(){bind();refreshMeasures();refreshDebt();patchCalendar();}
function observe(){new MutationObserver(()=>{bind();refreshDebt();patchCalendar();}).observe(document.body,{subtree:true,childList:true});}
init().then(()=>{bind();observe();setTimeout(refresh,500)}).catch(console.error);
