import { firebaseConfig } from './firebase-config.js';
const FV='10.14.1'; const DOC=['appData','shared']; let db,auth,F,user=null,ready=false,unsub=null;
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('ru-RU').format(Math.round(Number(n)||0))+' ₽';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const dateKey=d=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`}; const today=()=>dateKey(new Date());
async function init(){const [appMod,authMod,fs]=await Promise.all([import(`https://www.gstatic.com/firebasejs/${FV}/firebase-app.js`),import(`https://www.gstatic.com/firebasejs/${FV}/firebase-auth.js`),import(`https://www.gstatic.com/firebasejs/${FV}/firebase-firestore.js`)]);const app=appMod.initializeApp(firebaseConfig,'montaji-aa-measures-v7');auth=authMod.getAuth(app);db=fs.getFirestore(app);F={...fs,authMod};F.authMod.onAuthStateChanged(auth,u=>{user=u;ready=!!u;if(u)start()})}
function start(){if(unsub)unsub();unsub=F.onSnapshot(F.doc(db,...DOC),snap=>{if(!snap.exists())return;const data=snap.data()?.data||{};window.__aaMeasures=(Array.isArray(data.jobs)?data.jobs:[]).filter(j=>j.type==='Замер');refreshMeasureUI();hideLegacyMeasures();fixCalendarLabels()})}
async function read(){const s=await F.getDocFromServer(F.doc(db,...DOC));return s.exists()?s.data()?.data||{jobs:[],expenses:[]}:{jobs:[],expenses:[]}}
async function tx(mut){if(!ready)throw Error('Нет соединения с общей базой');const ref=F.doc(db,...DOC);await F.runTransaction(db,async t=>{const s=await t.get(ref),cur=s.exists()?s.data()?.data||{jobs:[],expenses:[]}:{};t.set(ref,{data:await mut(cur),version:6,updatedAt:F.serverTimestamp(),updatedBy:user.uid},{merge:true})})}
function toast(t){const e=document.createElement('div');e.className='toast aa-measure-toast';e.textContent=t;document.body.append(e);setTimeout(()=>e.remove(),2600)}
function modal(inner){const m=document.createElement('div');m.className='modal open aa-measure-modal';m.innerHTML=`<div class="backdrop"></div><div class="sheet aa-measure-sheet"><div class="handle"></div>${inner}</div>`;document.body.append(m);m.querySelector('.backdrop').onclick=()=>m.remove();m.querySelector('[data-close]')?.addEventListener('click',()=>m.remove());return m}
function form({job=null,date=today()}={}){const j=job||{},paid=j.measurePaid===true;return `<div class="sheet-head"><div><div class="eyebrow">Замер</div><h2>${job?'Изменить замер':'Новый замер'}</h2></div><button class="circle-btn" data-close>×</button></div><form id="aaMeasureForm"><label>Дата<input id="aaMDate" type="date" required value="${esc(j.date||date)}"></label><label>Время / когда удобно<input id="aaMTime" type="text" placeholder="Например: 08:30, после 18:00, вечером" value="${esc(j.measureTime||'')}"></label><label>Клиент<input id="aaMClient" required placeholder="ФИО, компания" value="${esc(j.client||'')}"></label><label>Телефон<input id="aaMPhone" type="tel" value="${esc(j.phone||'')}"></label><label>Адрес<textarea id="aaMAddress" rows="2" placeholder="Адрес объекта">${esc(j.address||'')}</textarea></label><label>Магазин<input id="aaMStore" placeholder="ASTERA / LAVETRA DOORS" value="${esc(j.store||'')}"></label><div class="aa-measure-price-grid"><label>Стоимость замера<input id="aaMPrice" type="number" min="0" step="1" inputmode="numeric" value="${j.measurePrice??j.price??0}"></label><label>Оплата<select id="aaMPaid"><option value="no" ${paid?'':'selected'}>Не оплачено</option><option value="yes" ${paid?'selected':''}>Оплачено</option></select></label></div><label>Комментарий<textarea id="aaMComment" rows="3" placeholder="Особенности, договорённости…">${esc(j.comment||'')}</textarea></label><div class="aa-measure-note">Замер не занимает монтажный слот и не влияет на загрузку 0/3, 1/3, 2/3, 3/3.</div><div class="form-actions"><button class="primary" type="submit">Сохранить замер</button>${job?'<button class="secondary" type="button" id="aaToMontage">→ Перевести в монтаж</button>':''}</div></form>`}
function openMeasure(job=null,date=today()){const m=modal(form({job,date}));m.querySelector('#aaMeasureForm').onsubmit=async e=>{e.preventDefault();const item={id:job?.id||crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`,type:'Замер',date:$('#aaMDate',m).value,slot:'0',client:$('#aaMClient',m).value.trim(),phone:$('#aaMPhone',m).value.trim(),address:$('#aaMAddress',m).value.trim(),store:$('#aaMStore',m).value.trim(),price:0,measurePrice:Math.max(0,Number($('#aaMPrice',m).value)||0),measurePaid:$('#aaMPaid',m).value==='yes',paid:$('#aaMPaid',m).value==='yes',status:'Запланирован',measureTime:$('#aaMTime',m).value.trim(),comment:$('#aaMComment',m).value.trim(),completedDate:''};if(!item.client)return;try{await tx(cur=>{const jobs=Array.isArray(cur.jobs)?[...cur.jobs]:[],i=jobs.findIndex(x=>x.id===item.id);if(i>=0)jobs[i]={...jobs[i],...item};else jobs.push(item);return {...cur,jobs}});m.remove();toast('Замер сохранён');refreshMeasureUI()}catch(err){toast(err.message||'Не удалось сохранить')}};if(job)m.querySelector('#aaToMontage').onclick=()=>{m.remove();openConvert(job)}}
function openConvert(job){const m=modal(`<div class="sheet-head"><div><div class="eyebrow">Следующий шаг</div><h2>Перевести в монтаж</h2></div><button class="circle-btn" data-close>×</button></div><div class="aa-convert-source"><b>${esc(job.client)}</b><span>${esc(job.address||'Адрес не указан')}</span><small>Оплачено за замер: ${money(job.measurePaid?job.measurePrice:0)}</small></div><form id="aaConvertForm"><label>Дата монтажа<input id="aaCDate" type="date" required value="${esc(job.installDate||job.date||today())}"></label><label>Слот<select id="aaCSlot"><option value="1">10:00–12:00</option><option value="2">14:00–16:00</option><option value="3">3-й слот / резерв</option></select></label><label>Цена монтажа<input id="aaCPrice" type="number" min="0" step="1" inputmode="numeric" placeholder="6500" required></label><div id="aaCResult" class="aa-convert-result"></div><div class="form-actions"><button class="primary" type="submit">Создать монтаж</button></div></form>`);const calc=()=>{const p=Math.max(0,Number($('#aaCPrice',m).value)||0),paid=job.measurePaid?Math.max(0,Number(job.measurePrice)||0):0;$('#aaCResult',m).textContent=`К оплате после замера: ${money(Math.max(0,p-paid))}`};$('#aaCPrice',m).oninput=calc;calc();m.querySelector('#aaConvertForm').onsubmit=async e=>{e.preventDefault();const d=$('#aaCDate',m).value,s=$('#aaCSlot',m).value,p=Math.max(0,Number($('#aaCPrice',m).value)||0);if(!d||!p)return toast('Укажи дату и цену монтажа');const paid=job.measurePaid?Math.max(0,Number(job.measurePrice)||0):0,montageId=crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;try{await tx(data=>{const jobs=[...(data.jobs||[])];const conflict=jobs.find(j=>j.id!==montageId&&j.type==='Монтаж'&&j.status!=='Выполнен'&&j.status!=='Отменён'&&j.date===d&&String(j.slot)===s);if(conflict)throw Error(`Слот занят: ${conflict.client}`);const montage={id:montageId,type:'Монтаж',date:d,slot:s,client:job.client,phone:job.phone||'',address:job.address||'',store:job.store||'',price:Math.max(0,p-paid),grossPrice:p,status:'Запланирован',paid:Math.max(0,p-paid)===0,completedDate:'',comment:[job.comment,paid?`Монтаж ${p} ₽. За замер оплачено ${paid} ₽. Остаток: ${Math.max(0,p-paid)} ₽.`:''].filter(Boolean).join(' '),measureSourceId:job.id,measurePaidAmount:paid};const next=jobs.map(x=>x.id===job.id?{...x,convertedToMontageId:montage.id,installDate:d,status:'Выполнен',completedDate:d,price:paid,paid:job.measurePaid,measureConverted:true}:x);next.push(montage);return {...data,jobs:next}});m.remove();toast('Монтаж создан — данные перенесены');refreshMeasureUI()}catch(err){toast(err.message||'Не удалось создать монтаж')}}}
function card(j){return `<article class="aa-measure-card"><div class="aa-measure-card-top"><div><div class="aa-measure-client">${esc(j.client)}</div><div class="aa-measure-meta">${esc(j.date)}${j.measureTime?' · '+esc(j.measureTime):''}</div></div><div class="aa-measure-cost">${j.measurePrice?money(j.measurePrice):'Бесплатно'}</div></div>${j.address?`<div class="aa-measure-address">📍 ${esc(j.address)}</div>`:''}<div class="aa-measure-status">${j.measurePaid?'Оплачен':'Не оплачен'} · Замер не занимает слот</div><div class="actions"><button class="action-chip aa-edit-measure" data-id="${esc(j.id)}">Изменить</button><button class="primary aa-convert-measure" data-id="${esc(j.id)}">→ В монтаж</button></div></article>`}
function refreshMeasureUI(){const host=$('#scheduleScreen');if(!host||!ready)return;let box=$('#aaMeasureList');if(!box){box=document.createElement('div');box.id='aaMeasureList';box.className='aa-measure-list';host.append(box)}const arr=(window.__aaMeasures||[]).filter(j=>j.status!=='Отменён'&&!j.convertedToMontageId).sort((a,b)=>(a.date||'').localeCompare(b.date||'')||(a.measureTime||'').localeCompare(b.measureTime||''));box.innerHTML=`<div class="section-head"><h2>Замеры</h2><button class="text-btn" id="aaAddMeasure">＋ Замер</button></div>${arr.length?arr.map(card).join(''):'<div class="empty-card">Активных замеров нет.</div>'}`;$('#aaAddMeasure',box)?.addEventListener('click',()=>openMeasure());$$('.aa-edit-measure',box).forEach(b=>b.onclick=()=>{const j=(window.__aaMeasures||[]).find(x=>x.id===b.dataset.id);if(j)openMeasure(j)});$$('.aa-convert-measure',box).forEach(b=>b.onclick=()=>{const j=(window.__aaMeasures||[]).find(x=>x.id===b.dataset.id);if(j)openConvert(j)})}
function hideLegacyMeasures(){ $$('.job-card').forEach(card=>{const meta=$('.job-meta',card);if(meta?.textContent.includes('Замер'))card.classList.add('aa-legacy-measure-hidden')}) }
function fixCalendarLabels(){ $$('.day[data-date]').forEach(day=>{const i=$('i',day),span=$('span',day);if(i&&span){const n=(i.textContent||'0/3').split('/')[0];span.textContent=`${n} монтаж${n==='1'?'':'ей'}`}}) }
function intercept(){document.addEventListener('click',e=>{const tab=e.target.closest('#typeTabs button[data-type="Замер"]');if(tab){e.preventDefault();e.stopImmediatePropagation();const d=$('#jobDate')?.value||today();document.querySelector('#jobModal')?.classList.remove('open');openMeasure(null,d)}},true)}
function fixOverflow(){document.documentElement.classList.add('aa-no-x');document.body.classList.add('aa-no-x')}
(async()=>{fixOverflow();intercept();await init();new MutationObserver(()=>{hideLegacyMeasures();fixCalendarLabels()}).observe(document.body,{childList:true,subtree:true});setTimeout(refreshMeasureUI,500)})();
