import { firebaseConfig } from './firebase-config.js';

const FIREBASE_VERSION='10.14.1';
const APP_NAME='montaji-aa-production';
const PROD_NOTES=['appData','notes'];
const SANDBOX=location.hostname.includes('git-dev-safe');
const NOTES_PATH=SANDBOX?['appData','notesSandbox']:PROD_NOTES;
const SHARED_PATH=['appData','shared'];
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const fmtDate=d=>d?new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'long'}).format(new Date(`${d}T12:00:00`)):'';
const TYPES={note:'Заметка',control:'Контроль',urgent:'Срочно'}, PRIORITIES={low:'Низкий',normal:'Обычный',high:'Высокий'};
let fs,db,auth,notes=[],jobs=[],unNotes,unShared,filter='all',query='';
const normalize=n=>({...n,id:n.id||uid(),title:n.title||'Заметка',text:n.text||'',type:n.type||'note',priority:n.priority||'normal',status:n.status||(n.deleted?'deleted':n.archived?'archived':'active'),checkDate:n.checkDate||'',phone:n.phone||'',client:n.client||'',jobId:n.jobId||'',lastResult:n.lastResult||'',nextAction:n.nextAction||'',createdAt:n.createdAt||n.updatedAt||new Date().toISOString(),updatedAt:n.updatedAt||new Date().toISOString(),archivedAt:n.archivedAt||null,completedAt:n.completedAt||null,deletedAt:n.deletedAt||null});
const normalizeAll=a=>Array.isArray(a)?a.map(normalize):[];
const snapNotes=s=>normalizeAll(s?.exists()?s.data()?.data?.notes:[]);
const isDue=n=>n.status==='active'&&n.checkDate&&n.checkDate<=today();
const dueText=n=>n.checkDate?(n.checkDate<today()?'Просрочено':n.checkDate===today()?'Сегодня':fmtDate(n.checkDate)):'';
function toast(t,k='normal'){let e=$('#toast');if(!e){e=document.createElement('div');e.id='toast';document.body.append(e)}e.textContent=t;e.dataset.state=k;clearTimeout(toast.t);toast.t=setTimeout(()=>e.remove(),3000)}
async function init(){const [app,am,f]=await Promise.all([import(`https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-app.js`),import(`https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-auth.js`),import(`https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-firestore.js`)]);fs=f;const a=app.getApps().find(x=>x.name===APP_NAME)||app.initializeApp(firebaseConfig,APP_NAME);auth=am.getAuth(a);db=f.getFirestore(a);am.onAuthStateChanged(auth,u=>{unNotes?.();unShared?.();if(u?.emailVerified)start()})}
async function start(){const ref=fs.doc(db,...NOTES_PATH);if(SANDBOX)await seedSandbox(ref);unNotes=fs.onSnapshot(ref,s=>{notes=snapNotes(s);render()},e=>{console.error(e);toast('Не удалось загрузить заметки','error')});unShared=fs.onSnapshot(fs.doc(db,...SHARED_PATH),s=>{const d=s.exists()?s.data()?.data||{}:{};jobs=Array.isArray(d.jobs)?d.jobs:[];setTimeout(addCancelledControls,0)},e=>console.error(e));render()}
async function seedSandbox(target){try{const t=await fs.getDoc(target);if(t.exists())return;const source=await fs.getDoc(fs.doc(db,...PROD_NOTES));const copy=snapNotes(source);await fs.setDoc(target,{data:{notes:copy},version:2,seededFrom:'appData/notes',seededAt:fs.serverTimestamp(),updatedAt:fs.serverTimestamp(),updatedBy:auth.currentUser?.uid||''},{merge:true});notes=copy}catch(e){console.error('sandbox seed',e);toast('Не удалось подготовить копию заметок','error')}}
async function write(mut){if(!auth.currentUser)throw Error('Нет авторизации');const ref=fs.doc(db,...NOTES_PATH);await fs.runTransaction(db,async tx=>{const s=await tx.get(ref),cur=snapNotes(s),next=normalizeAll(await mut(cur));tx.set(ref,{data:{notes:next},version:2,updatedAt:fs.serverTimestamp(),updatedBy:auth.currentUser.uid},{merge:true})})}
function list(){const q=query.trim().toLowerCase();return notes.filter(n=>{if(filter==='trash')return n.status==='deleted';if(filter==='archive')return n.status==='archived';if(filter!=='all'&&n.type!==filter)return false;if(n.status!=='active')return false;if(!q)return true;return `${n.title} ${n.text} ${n.client} ${n.phone} ${n.nextAction} ${n.lastResult}`.toLowerCase().includes(q)}).sort((a,b)=>Number(isDue(b))-Number(isDue(a))||({high:0,normal:1,low:2}[a.priority]||1)-({high:0,normal:1,low:2}[b.priority]||1)||String(a.checkDate||'9999').localeCompare(String(b.checkDate||'9999')))}
function render(){const h=$('#megaNotes');if(!h)return;const active=notes.filter(n=>n.status==='active');h.querySelector('[data-count="active"]').textContent=active.length;h.querySelector('[data-count="overdue"]').textContent=active.filter(isDue).length;h.querySelector('[data-count="control"]').textContent=active.filter(n=>n.type==='control').length;h.querySelector('[data-count="urgent"]').textContent=active.filter(n=>n.type==='urgent').length;const a=list();h.querySelector('.mega-notes-list').innerHTML=a.length?a.map(card).join(''):`<div class="mega-empty"><strong>${filter==='trash'?'Корзина пуста':filter==='archive'?'Архив пуст':'Ничего не найдено'}</strong><span>${filter==='all'?'Добавь первую запись — дальше она сама будет держать контроль.':''}</span></div>`;$$('.mega-filter').forEach(b=>b.classList.toggle('active',b.dataset.filter===filter));bindCards();setTimeout(addCancelledControls,0)}
function card(n){const j=n.jobId?jobs.find(x=>x.id===n.jobId):null,meta=[n.client,n.phone,n.checkDate?`${dueText(n)} · ${n.checkDate}`:''].filter(Boolean).map(esc).join(' · ');return `<article class="mega-note ${n.type}${isDue(n)?' due':''} ${n.status}"><div class="mega-note-accent"></div><div class="mega-note-main"><div class="mega-note-head"><div><span class="mega-badge ${n.type}">${TYPES[n.type]}</span><span class="mega-priority ${n.priority}">${PRIORITIES[n.priority]}</span></div><button class="mega-more" data-edit-note="${esc(n.id)}">•••</button></div><h3>${esc(n.title)}</h3>${n.text?`<p>${esc(n.text)}</p>`:''}${meta?`<div class="mega-note-meta">${meta}</div>`:''}${n.nextAction?`<div class="mega-next"><span>Следующее действие</span><b>${esc(n.nextAction)}</b></div>`:''}${n.lastResult?`<div class="mega-result"><span>Последний результат</span>${esc(n.lastResult)}</div>`:''}${j?`<div class="mega-linked">Выезд: <b>${esc(j.client||j.type||'')}</b>${j.status==='Отменён'?' · отменён':''}</div>`:''}<div class="mega-actions">${n.status==='active'?`<button data-note-done="${esc(n.id)}">✓ Проверено</button><button data-note-archive="${esc(n.id)}">В архив</button><button data-note-delete="${esc(n.id)}">Удалить</button>`:''}${n.status==='archived'?`<button data-note-restore="${esc(n.id)}">Вернуть</button><button data-note-delete="${esc(n.id)}">Удалить</button>`:''}${n.status==='deleted'?`<button data-note-restore="${esc(n.id)}">Восстановить</button><button class="danger" data-note-hard-delete="${esc(n.id)}">Удалить навсегда</button>`:''}</div></div></article>`}
function bindCards(){$$('.mega-more').forEach(b=>b.onclick=()=>openNote(notes.find(n=>n.id===b.dataset.editNote)));$$('[data-note-done]').forEach(b=>b.onclick=()=>followUp(notes.find(n=>n.id===b.dataset.noteDone)));$$('[data-note-archive]').forEach(b=>b.onclick=()=>setStatus(b.dataset.noteArchive,'archived'));$$('[data-note-delete]').forEach(b=>b.onclick=()=>setStatus(b.dataset.noteDelete,'deleted'));$$('[data-note-restore]').forEach(b=>b.onclick=()=>setStatus(b.dataset.noteRestore,'active'));$$('[data-note-hard-delete]').forEach(b=>b.onclick=()=>hardDelete(b.dataset.noteHardDelete))}
async function setStatus(id,status){try{await write(a=>a.map(n=>n.id===id?{...n,status,archivedAt:status==='archived'?new Date().toISOString():n.archivedAt,deletedAt:status==='deleted'?new Date().toISOString():n.deletedAt}:n));toast(status==='archived'?'В архив':status==='deleted'?'В корзину':'Восстановлено','success')}catch(e){toast('Не удалось изменить запись','error')}}
async function hardDelete(id){if(!confirm('Удалить навсегда?'))return;try{await write(a=>a.filter(n=>n.id!==id));toast('Удалено навсегда','success')}catch(e){toast('Не удалось удалить','error')}}
function modal(title,body){const m=document.createElement('div');m.className='modal open mega-note-modal';m.innerHTML=`<div class="backdrop"></div><div class="sheet"><div class="handle"></div><div class="sheet-head"><div><div class="eyebrow">Контроль и заметки${SANDBOX?' · ПЕСОЧНИЦА':''}</div><h2>${title}</h2></div><button class="circle-btn" data-close>×</button></div>${body}</div>`;document.body.append(m);m.querySelector('.backdrop').onclick=()=>m.remove();m.querySelector('[data-close]').onclick=()=>m.remove();return m}
function openNote(n=null,p={}){const x=n||{},m=modal(n?'Изменить запись':'Новая запись',`<form id="megaNoteForm" class="mega-note-form"><div class="mega-type-grid">${Object.entries(TYPES).map(([k,v])=>`<button type="button" data-type="${k}" class="${(x.type||p.type||'note')===k?'active':''}">${k==='urgent'?'⚠️':k==='control'?'🎯':'✦'} ${v}</button>`).join('')}</div><input id="mnType" type="hidden" value="${esc(x.type||p.type||'note')}"><div class="form-row"><label>Заголовок<input id="mnTitle" required value="${esc(x.title||p.title||'')}" placeholder="Например: Перезвонить Ирине"></label><label>Приоритет<select id="mnPriority"><option value="low" ${x.priority==='low'?'selected':''}>Низкий</option><option value="normal" ${!x.priority||x.priority==='normal'?'selected':''}>Обычный</option><option value="high" ${x.priority==='high'?'selected':''}>Высокий</option></select></div><label>Что нужно помнить<textarea id="mnText" rows="4" placeholder="Контекст, договорённости, детали…">${esc(x.text||p.text||'')}</textarea></label><div class="form-row"><label>Дата контроля<input id="mnDate" type="date" value="${esc(x.checkDate||p.checkDate||'')}"></label><label>Следующее действие<input id="mnNext" value="${esc(x.nextAction||p.nextAction||'')}" placeholder="Что сделать дальше"></label></div><div class="form-row"><label>Клиент<input id="mnClient" value="${esc(x.client||p.client||'')}" placeholder="Имя клиента"></label><label>Телефон<input id="mnPhone" type="tel" value="${esc(x.phone||p.phone||'')}" placeholder="+7…"></label></div><label>Связанный выезд<select id="mnJob"><option value="">Без привязки</option>${jobs.filter(j=>j.status!=='Выполнен').map(j=>`<option value="${esc(j.id)}" ${x.jobId===j.id||p.jobId===j.id?'selected':''}>${esc(j.date||'')} · ${esc(j.client||j.type||'')} · ${esc(j.status||'')}</option>`).join('')}</select></label><div class="mega-save-row"><button class="primary wide" type="submit">Сохранить</button>${n?'<button class="danger ghost wide" type="button" id="mnDelete">В корзину</button>':''}</div></form>`);$$('.mega-type-grid button',m).forEach(b=>b.onclick=()=>{$$('.mega-type-grid button',m).forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#mnType',m).value=b.dataset.type});$('#megaNoteForm',m).onsubmit=async e=>{e.preventDefault();const item=normalize({...x,id:x.id||uid(),title:$('#mnTitle',m).value.trim(),text:$('#mnText',m).value.trim(),type:$('#mnType',m).value,priority:$('#mnPriority',m).value,checkDate:$('#mnDate',m).value,nextAction:$('#mnNext',m).value.trim(),client:$('#mnClient',m).value.trim(),phone:$('#mnPhone',m).value.trim(),jobId:$('#mnJob',m).value,updatedAt:new Date().toISOString(),status:x.status||'active'});try{await write(a=>[...a.filter(q=>q.id!==item.id),item]);m.remove();toast('Сохранено','success')}catch(e){toast('Не удалось сохранить','error')}};$('#mnDelete',m)?.addEventListener('click',()=>{m.remove();setStatus(x.id,'deleted')})}
function followUp(n){if(!n)return;const m=modal('Проверка контроля',`<form id="megaFollowForm" class="mega-note-form"><div class="follow-context"><b>${esc(n.title)}</b><span>${n.checkDate?`Срок: ${esc(fmtDate(n.checkDate))}`:''}</span></div><label>Что выяснили?<textarea id="mfResult" rows="4" required>${esc(n.lastResult||'')}</textarea></label><div class="form-row"><label>Следующая дата<input id="mfDate" type="date" value="${esc(n.checkDate||'')}"></label><label>Следующее действие<input id="mfNext" value="${esc(n.nextAction||'')}"></label></div><button class="primary wide" type="submit">Сохранить проверку</button></form>`);$('#megaFollowForm',m).onsubmit=async e=>{e.preventDefault();const d=$('#mfDate',m).value;try{await write(a=>a.map(x=>x.id===n.id?{...x,lastResult:$('#mfResult',m).value.trim(),checkDate:d,nextAction:$('#mfNext',m).value.trim(),status:d?'active':'completed',completedAt:d?null:new Date().toISOString(),updatedAt:new Date().toISOString()}:x));m.remove();toast(d?'Контроль обновлён':'Контроль закрыт','success')}catch(e){toast('Не удалось сохранить проверку','error')}}}
function addCancelledControls(){$$('[data-job-card]').forEach(el=>{const j=jobs.find(x=>x.id===el.dataset.jobCard);if(!j||j.status!=='Отменён'||el.querySelector('[data-mega-control]'))return;const box=el.querySelector('.actions')||el,b=document.createElement('button');b.className='action-chip';b.dataset.megaControl='1';b.textContent='Поставить на контроль';b.onclick=()=>openNote(null,{type:'control',title:`Контроль: ${j.client||'отменённый выезд'}`,client:j.client||'',phone:j.phone||'',jobId:j.id,nextAction:'Связаться с клиентом'});box.append(b)})}
function bind(){const add=$('#megaAddNote');if(add)add.onclick=()=>openNote();const old=$('#todayNoteBtn');if(old)old.onclick=e=>{e.preventDefault();openNote()};$('#megaNotesSearch')?.addEventListener('input',e=>{query=e.target.value;render()});$$('.mega-filter').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render()});document.addEventListener('click',e=>{const b=e.target.closest('[data-add-type="Заметка"]');if(b){e.preventDefault();e.stopImmediatePropagation();openNote()}},true)}
(async()=>{try{await init();bind();setTimeout(addCancelledControls,800)}catch(e){console.error('mega notes',e)}})();