import { getApps, getApp, initializeApp } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js';
import { getAuth, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js';
import { getFirestore, doc, onSnapshot, runTransaction, serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';
import { firebaseConfig } from './firebase-config.js';

const NOTES_DOC=['appData','notes'];
const $=id=>document.querySelector('#'+id);
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const todayKey=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const fmtDate=d=>d?new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short'}).format(new Date(`${d}T12:00:00`)).replace('.',''):'';
const normalize=n=>({id:n?.id||uid(),type:['note','task','reminder'].includes(n?.type)?n.type:'note',title:String(n?.title||''),text:String(n?.text||n?.body||''),dueDate:String(n?.dueDate||n?.date||''),dueTime:String(n?.dueTime||n?.time||''),priority:['normal','important','urgent'].includes(n?.priority)?n.priority:'normal',assignee:['all','anatoly','alexander'].includes(n?.assignee)?n.assignee:'all',completed:n?.completed===true||n?.status==='done',archived:n?.archived===true});
let app,auth,db,user=null,notes=[],unsub=null,filter='all',query='',editingId=null;
function initFirebase(){const apps=getApps();app=apps.find(a=>a.name==='montaji-aa-production')||initializeApp(firebaseConfig,'montaji-aa-production-notes');auth=getAuth(app);db=getFirestore(app)}
function counts(){const a=notes.filter(n=>!n.archived&&!n.completed);return{active:a.length,today:a.filter(n=>n.dueDate===todayKey()).length,overdue:a.filter(n=>n.dueDate&&n.dueDate<todayKey()).length,important:a.filter(n=>n.priority!=='normal').length}}
function visible(){let a=notes.filter(n=>!n.archived);if(filter==='today')a=a.filter(n=>!n.completed&&n.dueDate===todayKey());if(filter==='overdue')a=a.filter(n=>!n.completed&&n.dueDate&&n.dueDate<todayKey());if(filter==='important')a=a.filter(n=>!n.completed&&n.priority!=='normal');if(filter==='done')a=a.filter(n=>n.completed);if(query)a=a.filter(n=>(n.title+' '+n.text).toLowerCase().includes(query.toLowerCase()));return a.sort((x,y)=>{const score=n=>(n.completed?30:0)+(n.priority==='urgent'?0:n.priority==='important'?5:10)+(n.dueDate?(n.dueDate<todayKey()?-10:0):20);return score(x)-score(y)||String(x.dueDate).localeCompare(String(y.dueDate))||String(x.dueTime).localeCompare(String(y.dueTime))})}
function typeLabel(n){return n.type==='reminder'?'НАПОМИНАНИЕ':n.type==='task'?'ЗАДАЧА':'ЗАМЕТКА'}
function assignee(a){return a==='anatoly'?'Анатолий':a==='alexander'?'Александр':'Оба'}
function card(n,compact=false){const overdue=!n.completed&&n.dueDate&&n.dueDate<todayKey();const priority=n.priority==='urgent'?'urgent':n.priority==='important'?'important':'';return `<article class="ni-card ${priority} ${n.completed?'is-done':''}" data-note-id="${esc(n.id)}"><button class="ni-check" data-note-action="toggle" title="${n.completed?'Вернуть в работу':'Выполнить'}">${n.completed?'✓':''}</button><div class="ni-card-main"><div class="ni-type-row"><span class="ni-type">${typeLabel(n)}</span>${n.priority!=='normal'?`<span class="ni-priority">${n.priority==='urgent'?'СРОЧНО':'ВАЖНО'}</span>`:''}</div><h3>${esc(n.title||'Без названия')}</h3>${n.text?`<p>${esc(n.text)}</p>`:''}<div class="ni-meta">${n.dueDate?`<span class="${overdue?'overdue':''}">${overdue?'Просрочено · ':''}${fmtDate(n.dueDate)}${n.dueTime?' · '+esc(n.dueTime):''}</span>`:''}${!compact?`<span>${assignee(n.assignee)}</span>`:''}</div></div><button class="ni-more" data-note-action="edit" aria-label="Открыть">•••</button></article>`}
function findLegacy(){
  const byId=document.querySelector('#activeNotes');
  if(byId)return byId.closest('.inline-card')||byId;
  return [...document.querySelectorAll('.inline-card,.settings-card,.chart-card,.system-note,section,article,div')].find(el=>{
    const t=(el.textContent||'').replace(/\s+/g,' ').trim();
    return t.startsWith('Заметки')&&t.includes('Общие для обоих телефонов');
  })||null;
}
function hideLegacy(el){if(!el)return;el.classList.add('ni-legacy-hidden');el.style.setProperty('display','none','important');el.setAttribute('aria-hidden','true')}
function mount(){if($('#notesInbox'))return;const legacy=findLegacy();hideLegacy(legacy);const anchor=legacy||document.querySelector('.main')?.lastElementChild||document.querySelector('.main');const cardEl=document.createElement('section');cardEl.id='notesInbox';cardEl.className='ni-preview';if(anchor?.parentNode)anchor.parentNode.insertBefore(cardEl,anchor);else document.querySelector('.main')?.append(cardEl);
const modal=document.createElement('div');modal.id='notesModal';modal.className='ni-modal';modal.innerHTML=`<div class="ni-backdrop" data-ni-close></div><div class="ni-sheet"><div class="ni-handle"></div><header class="ni-sheet-head"><div><span class="ni-eyebrow">РАБОЧИЙ INBOX</span><h2>Входящие</h2><p id="niSummary"></p></div><button class="ni-close" data-ni-close>×</button></header><div class="ni-toolbar"><button class="ni-add" id="niAdd">＋ Добавить</button><div class="ni-search-wrap"><span>⌕</span><input id="niSearch" placeholder="Найти"></div></div><div class="ni-tabs" id="niTabs"><button data-filter="all" class="active">Все</button><button data-filter="today">Сегодня</button><button data-filter="overdue">Просрочено</button><button data-filter="important">Важные</button><button data-filter="done">Выполнено</button></div><div id="niList"></div></div></div>`;document.body.append(modal);const editor=document.createElement('div');editor.id='niEditor';editor.className='ni-editor';editor.innerHTML=`<div class="ni-backdrop" data-ni-editor-close></div><div class="ni-editor-sheet"><div class="ni-handle"></div><header class="ni-sheet-head"><div><span class="ni-eyebrow">НОВАЯ ЗАПИСЬ</span><h2 id="niEditorTitle">Добавить</h2></div><button class="ni-close" data-ni-editor-close>×</button></header><div class="ni-type-picker"><button data-type="task" class="selected">☑ Задача</button><button data-type="reminder">🔔 Напоминание</button><button data-type="note">📝 Заметка</button></div><label>Что нужно сделать?<input id="niTitle" maxlength="120" placeholder="Например: позвонить клиенту"></label><label>Подробности<textarea id="niText" rows="4" placeholder="Комментарий, адрес, детали…"></textarea></label><div class="ni-grid"><label>Срок<input id="niDate" type="date"></label><label>Время<input id="niTime" type="time"></label></div><div class="ni-grid"><label>Приоритет<select id="niPriority"><option value="normal">Обычный</option><option value="important">Важная</option><option value="urgent">🔥 Срочно</option></select></label><label>Для кого<select id="niAssignee"><option value="all">Обоим</option><option value="anatoly">Анатолию</option><option value="alexander">Александру</option></select></label></div><div class="ni-editor-actions"><button class="ni-secondary" data-ni-editor-close>Отмена</button><button class="ni-primary" id="niSave">Сохранить</button></div><button class="ni-delete" id="niDelete">Удалить навсегда</button></div></div>`;document.body.append(editor);bind();render()}
function openModal(){document.querySelector('#notesModal')?.classList.add('open');render()}
function openEditor(id=null){editingId=id;const n=id?notes.find(x=>x.id===id):null;document.querySelector('#niEditor')?.classList.add('open');$('#niEditorTitle').textContent=n?'Редактировать':'Добавить';$('#niTitle').value=n?.title||'';$('#niText').value=n?.text||'';$('#niDate').value=n?.dueDate||'';$('#niTime').value=n?.dueTime||'';$('#niPriority').value=n?.priority||'normal';$('#niAssignee').value=n?.assignee||'all';$('#niDelete').style.display=n?'block':'none';document.querySelectorAll('.ni-type-picker button').forEach(b=>b.classList.toggle('selected',b.dataset.type===(n?.type||'task')))}
function closeAll(){document.querySelectorAll('.ni-modal.open,.ni-editor.open').forEach(x=>x.classList.remove('open'))}
async function write(mutator){if(!user)throw Error('Нет авторизации');const ref=doc(db,...NOTES_DOC);await runTransaction(db,async tx=>{const snap=await tx.get(ref);const current=(Array.isArray(snap.data()?.data?.notes)?snap.data().data.notes:[]).map(normalize);const next=mutator(current);tx.set(ref,{data:{notes:next},version:2,updatedAt:serverTimestamp(),updatedBy:user.uid},{merge:true})})}
async function toggle(id){await write(a=>a.map(n=>n.id===id?{...n,completed:!n.completed}:n))}
async function save(){const title=$('niTitle').value.trim();if(!title)return $('niTitle').focus();const type=document.querySelector('.ni-type-picker .selected')?.dataset.type||'task';const payload={id:editingId||uid(),type,title,text:$('niText').value.trim(),dueDate:$('niDate').value,dueTime:$('niTime').value,priority:$('niPriority').value,assignee:$('niAssignee').value,completed:false,archived:false};await write(a=>editingId?a.map(n=>n.id===editingId?{...n,...payload,completed:n.completed,archived:n.archived}:n):[...a,payload]);closeAll()}
async function remove(){if(!editingId)return;if(!confirm('Удалить навсегда?'))return;await write(a=>a.filter(n=>n.id!==editingId));closeAll()}
function render(){const c=counts(),p=visible().filter(n=>!n.completed).slice(0,3),inbox=$('#notesInbox');if(inbox)inbox.innerHTML=`<div class="ni-preview-head"><div><span class="ni-eyebrow">РАБОЧИЙ INBOX</span><h2>Входящие <b>${c.active}</b></h2><p>${c.today?c.today+' сегодня · ':''}${c.overdue?c.overdue+' просрочено · ':''}${c.important?c.important+' важных':''}</p></div><button id="niPreviewAdd">＋</button></div>${p.length?`<div class="ni-preview-list">${p.map(n=>card(n,true)).join('')}</div>`:`<div class="ni-empty"><strong>Всё спокойно</strong><span>Нет активных задач</span></div>`}<button class="ni-open-all" id="niOpenAll">Открыть все входящие <span>→</span></button>`;const list=$('#niList');if(list)list.innerHTML=visible().length?visible().map(card).join(''):`<div class="ni-empty large"><strong>Здесь пока пусто</strong><span>Добавь задачу, напоминание или заметку</span></div>`;const s=$('#niSummary');if(s)s.textContent=`${c.active} активных · ${c.today} сегодня · ${c.overdue} просрочено`;document.querySelectorAll('#niTabs button').forEach(b=>b.classList.toggle('active',b.dataset.filter===filter))}
function bind(){document.addEventListener('click',async e=>{if(e.target.closest('[data-ni-close]')||e.target.closest('[data-ni-editor-close]'))return closeAll();const a=e.target.closest('[data-note-action]');if(a){const id=a.closest('[data-note-id]')?.dataset.noteId;if(a.dataset.noteAction==='toggle')await toggle(id);else openEditor(id);return}const tab=e.target.closest('#niTabs button');if(tab){filter=tab.dataset.filter;return render()}if(e.target.closest('#niOpenAll'))return openModal();if(e.target.closest('#niPreviewAdd')||e.target.closest('#niAdd'))return openEditor();if(e.target.closest('#niSave'))return save();if(e.target.closest('#niDelete'))return remove();const type=e.target.closest('.ni-type-picker button');if(type){document.querySelectorAll('.ni-type-picker button').forEach(b=>b.classList.remove('selected'));type.classList.add('selected')}});document.addEventListener('input',e=>{if(e.target.id==='niSearch'){query=e.target.value;render()}})}
function start(){initFirebase();onAuthStateChanged(auth,u=>{user=u||null;if(unsub){unsub();unsub=null}if(!u)return;mount();unsub=onSnapshot(doc(db,...NOTES_DOC),snap=>{notes=(Array.isArray(snap.data()?.data?.notes)?snap.data().data.notes:[]).map(normalize);render()},err=>console.error('Notes realtime',err))})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
