const NOTES_V2_PATH = ['appData','notesV2'];
const NOTES_V2_VERSION = 1;

(() => {
  const STYLE = `
    #notesV2Root{margin-top:24px}
    .n2-card{background:#fff;border:1px solid #d9ddd4;border-radius:22px;padding:18px;box-shadow:0 8px 30px rgba(20,30,20,.04)}
    .n2-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:14px}
    .n2-head h2{margin:0;font-size:22px}.n2-count{font-size:12px;color:#73796f}
    .n2-add{border:0;background:#5f6b4f;color:#fff;border-radius:12px;padding:10px 14px;font-weight:700}
    .n2-search{width:100%;box-sizing:border-box;border:1px solid #d8ddd4;background:#f7f7f3;border-radius:12px;padding:12px 14px;font-size:15px;margin-bottom:10px}
    .n2-filters{display:flex;gap:7px;overflow:auto;padding-bottom:3px;margin-bottom:12px}
    .n2-filter{white-space:nowrap;border:1px solid #d8ddd4;background:#fff;border-radius:999px;padding:8px 11px;font-size:12px;color:#5e645b}
    .n2-filter.active{background:#5f6b4f;color:#fff;border-color:#5f6b4f}
    .n2-list{display:grid;gap:9px}.n2-empty{padding:18px 6px;color:#7a8077;text-align:center;font-size:14px}
    .n2-note{border:1px solid #e0e3dd;border-radius:16px;padding:13px;background:#fbfbf8}.n2-note.pinned{border-color:#a9b29c}.n2-note.done{opacity:.62}
    .n2-top{display:flex;justify-content:space-between;gap:10px}.n2-title{font-weight:800;font-size:16px;line-height:1.2}.n2-meta{display:flex;gap:6px;flex-wrap:wrap;margin-top:7px}
    .n2-chip{font-size:10px;border-radius:999px;padding:4px 7px;background:#eef0e9;color:#62695b}.n2-chip.important{background:#f1ddd6;color:#87463a}.n2-chip.due{background:#e7ece3;color:#4f5d45}
    .n2-body{white-space:pre-wrap;color:#565c55;font-size:13px;line-height:1.45;margin-top:9px;display:-webkit-box;-webkit-line-clamp:4;-webkit-box-orient:vertical;overflow:hidden}
    .n2-actions{display:flex;gap:6px;flex-wrap:wrap;margin-top:11px}.n2-action{border:1px solid #d8ddd4;background:#fff;border-radius:9px;padding:7px 9px;font-size:11px}.n2-action.primary{background:#5f6b4f;color:#fff;border-color:#5f6b4f}
    .n2-modal{position:fixed;inset:0;z-index:10000;display:none;background:rgba(17,22,17,.42);align-items:flex-end}.n2-modal.open{display:flex}
    .n2-sheet{width:100%;max-height:92vh;overflow:auto;background:#f7f7f3;border-radius:24px 24px 0 0;padding:18px 18px calc(26px + env(safe-area-inset-bottom));box-sizing:border-box}
    .n2-sheet-head{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:14px}.n2-sheet-head h3{margin:0;font-size:21px}.n2-close{border:0;background:#e5e8e1;border-radius:50%;width:36px;height:36px;font-size:22px}
    .n2-form{display:grid;gap:12px}.n2-form label{display:grid;gap:6px;font-size:12px;color:#70766d}.n2-form input,.n2-form textarea,.n2-form select{font:inherit;font-size:15px;border:1px solid #d5dad1;background:#fff;border-radius:12px;padding:12px;box-sizing:border-box;width:100%}.n2-form textarea{min-height:130px;resize:vertical}
    .n2-row{display:grid;grid-template-columns:1fr 1fr;gap:10px}.n2-check{display:flex!important;align-items:center;grid-template-columns:auto 1fr;gap:8px!important;padding-top:24px}.n2-check input{width:auto}
    .n2-save{border:0;background:#5f6b4f;color:#fff;border-radius:13px;padding:14px;font-weight:800;font-size:15px}.n2-danger{border:1px solid #d6aaa1;background:#fff;color:#8b463b;border-radius:13px;padding:12px;font-weight:700}
    @media(min-width:700px){.n2-sheet{max-width:620px;margin:auto;border-radius:24px;margin-bottom:24px}.n2-modal{align-items:center}}
  `;

  const $ = (s, r=document) => r.querySelector(s);
  const esc = v => String(v ?? '').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const uid = () => crypto.randomUUID?.() || `${Date.now()}-${Math.random()}`;
  const dateText = d => d ? new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'2-digit'}).format(new Date(`${d}T12:00:00`)) : '';
  let db=null, auth=null, unsub=null, notes=[], filter='active', query='', editingId=null, ready=false;

  function injectStyle(){if($('#notesV2Style'))return;const s=document.createElement('style');s.id='notesV2Style';s.textContent=STYLE;document.head.appendChild(s)}
  function ensureUI(){
    if($('#notesV2Root')) return;
    const todayScreen=$('#todayScreen');
    if(!todayScreen) return;
    const upcoming=$('#upcoming')?.parentElement;
    const root=document.createElement('section');root.id='notesV2Root';root.className='n2-card';
    root.innerHTML=`<div class="n2-head"><div><h2>Заметки</h2><div class="n2-count" id="n2Count">0 активных</div></div><button class="n2-add" id="n2Add">＋ Заметка</button></div><input id="n2Search" class="n2-search" type="search" placeholder="Поиск по заметкам…"><div class="n2-filters"><button class="n2-filter" data-n2-filter="active">Активные</button><button class="n2-filter" data-n2-filter="all">Все</button><button class="n2-filter" data-n2-filter="important">Важные</button><button class="n2-filter" data-n2-filter="archive">Архив</button></div><div class="n2-list" id="n2List"></div>`;
    if(upcoming) upcoming.after(root); else todayScreen.append(root);
    const modal=document.createElement('div');modal.id='n2Modal';modal.className='n2-modal';modal.innerHTML=`<div class="n2-sheet"><div class="n2-sheet-head"><h3 id="n2ModalTitle">Новая заметка</h3><button class="n2-close" id="n2Close" type="button">×</button></div><form class="n2-form" id="n2Form"><label>Заголовок<input id="n2Title" maxlength="120" placeholder="Например: уточнить у клиента размер доборов"></label><label>Текст<textarea id="n2Body" maxlength="4000" placeholder="Что нужно помнить или сделать…"></textarea></label><div class="n2-row"><label>Тип<select id="n2Type"><option>Работа</option><option>Клиент</option><option>Объект</option><option>Покупка</option><option>Личное</option><option>Другое</option></select></label><label>Срок<input id="n2Due" type="date"></label></div><div class="n2-row"><label>Приоритет<select id="n2Priority"><option value="normal">Обычный</option><option value="high">Важно</option></select></label><label>Время<input id="n2DueTime" type="time"></label></div><label>Клиент / объект<input id="n2Link" maxlength="160" placeholder="Имя клиента, адрес или объект"></label><label class="n2-check"><input id="n2Pinned" type="checkbox"> Закрепить сверху</label><button class="n2-save" type="submit">Сохранить заметку</button><button class="n2-danger" id="n2Archive" type="button">В архив</button></form></div>`;document.body.append(modal);
    $('#n2Add').onclick=()=>openEditor();$('#todayNoteBtn').onclick=()=>openEditor();$('#n2Close').onclick=closeEditor;modal.addEventListener('click',e=>{if(e.target===modal)closeEditor()});$('#n2Search').oninput=e=>{query=e.target.value.trim().toLowerCase();renderList()};$('#n2Form').onsubmit=saveEditor;$('#n2Archive').onclick=archiveEditing;
    $$('.n2-filter').forEach(b=>b.onclick=()=>{filter=b.dataset.n2Filter;$$('.n2-filter').forEach(x=>x.classList.toggle('active',x===b));renderList()});
    const first=$('.n2-filter[data-n2-filter="active"]');first?.classList.add('active');
  }
  const $$ = (s,r=document)=>[...r.querySelectorAll(s)];
  function visible(){let a=notes.filter(n=>filter==='archive'?n.archived:filter==='important'?(n.priority==='high'&&!n.archived):filter==='all'?!n.archived:(!n.archived&&!n.done));if(query)a=a.filter(n=>`${n.title} ${n.body} ${n.type} ${n.link}`.toLowerCase().includes(query));return a.sort((a,b)=>(Number(b.pinned)-Number(a.pinned))||(Number(b.priority==='high')-Number(a.priority==='high'))||((b.updatedAt||0)-(a.updatedAt||0)))}
  function renderList(){ensureUI();const list=$('#n2List');if(!list)return;const a=visible();const active=notes.filter(n=>!n.archived&&!n.done).length;$('#n2Count').textContent=`${active} активных · ${notes.length} всего`;list.innerHTML=a.length?a.map(noteCard).join(''):`<div class="n2-empty">${filter==='archive'?'Архив пуст.':filter==='important'?'Важных заметок пока нет.':'Здесь пока пусто. Добавь первую заметку.'}</div>`;$$('.n2-action',list).forEach(b=>b.onclick=()=>noteAction(b.dataset.action,b.dataset.id));}
  function noteCard(n){const chips=[`<span class="n2-chip">${esc(n.type||'Работа')}</span>`,n.priority==='high'?'<span class="n2-chip important">Важно</span>':'',n.pinned?'<span class="n2-chip">📌 Закреплена</span>':'',n.dueDate?`<span class="n2-chip due">До ${dateText(n.dueDate)}${n.dueTime?' · '+esc(n.dueTime):''}</span>`:''].join('');return`<article class="n2-note ${n.pinned?'pinned':''} ${n.done?'done':''}><div class="n2-top"><div class="n2-title">${n.done?'✓ ':''}${esc(n.title||'Без заголовка')}</div></div><div class="n2-meta">${chips}</div>${n.link?`<div class="n2-body"><b>${esc(n.link)}</b></div>`:''}${n.body?`<div class="n2-body">${esc(n.body)}</div>`:''}<div class="n2-actions"><button class="n2-action primary" data-action="edit" data-id="${esc(n.id)}">Открыть</button><button class="n2-action" data-action="done" data-id="${esc(n.id)}">${n.done?'Вернуть':'Готово'}</button><button class="n2-action" data-action="pin" data-id="${esc(n.id)}">${n.pinned?'Открепить':'Закрепить'}</button><button class="n2-action" data-action="archive" data-id="${esc(n.id)}">${n.archived?'Вернуть':'Архив'}</button></div></article>`}
  function openEditor(id){editingId=id||null;const n=id?notes.find(x=>x.id===id):null;$('#n2ModalTitle').textContent=n?'Редактировать заметку':'Новая заметка';$('#n2Title').value=n?.title||'';$('#n2Body').value=n?.body||'';$('#n2Type').value=n?.type||'Работа';$('#n2Due').value=n?.dueDate||'';$('#n2DueTime').value=n?.dueTime||'';$('#n2Priority').value=n?.priority||'normal';$('#n2Link').value=n?.link||'';$('#n2Pinned').checked=!!n?.pinned;$('#n2Archive').style.display=n?'block':'none';$('#n2Modal').classList.add('open');setTimeout(()=>$('#n2Title')?.focus(),30)}
  function closeEditor(){$('#n2Modal')?.classList.remove('open');editingId=null}
  async function saveEditor(e){e.preventDefault();if(!db||!auth?.currentUser)return toastSafe('Нет подключения к общей базе.','error');const title=$('#n2Title').value.trim(),body=$('#n2Body').value.trim();if(!title&&!body)return toastSafe('Добавь заголовок или текст.','error');const now=Date.now();const next={id:editingId||uid(),title,body,type:$('#n2Type').value,dueDate:$('#n2Due').value,dueTime:$('#n2DueTime').value,priority:$('#n2Priority').value,link:$('#n2Link').value.trim(),pinned:$('#n2Pinned').checked,done:false,archived:false,createdAt:editingId?(notes.find(n=>n.id===editingId)?.createdAt||now):now,updatedAt:now,updatedBy:auth.currentUser.uid};try{await writeNotes(cur=>{const arr=cur.notes||[];const i=arr.findIndex(n=>n.id===next.id);if(i>=0){next.done=arr[i].done;next.archived=arr[i].archived;arr[i]=next}else arr.push(next);return{notes:arr}});closeEditor();toastSafe('Заметка сохранена.','ok')}catch(err){console.error(err);toastSafe(`Не удалось сохранить: ${err.message||err}`,'error')}}
  async function writeNotes(mutator){const ref=db.doc(NOTES_V2_PATH.join('/'));await db.runTransaction(async tx=>{const snap=await tx.get(ref);const cur=snap.exists?snap.data()?.data||{notes:[]}: {notes:[]};const next=mutator(JSON.parse(JSON.stringify(cur)));tx.set(ref,{data:{notes:Array.isArray(next.notes)?next.notes:[]},version:NOTES_V2_VERSION,updatedAt:firebase.firestore.FieldValue.serverTimestamp(),updatedBy:auth.currentUser.uid},{merge:true})})}
  async function noteAction(action,id){const n=notes.find(x=>x.id===id);if(!n)return;if(action==='edit')return openEditor(id);try{await writeNotes(cur=>{const arr=cur.notes||[],x=arr.find(v=>v.id===id);if(!x)return cur;if(action==='done')x.done=!x.done;if(action==='pin')x.pinned=!x.pinned;if(action==='archive')x.archived=!x.archived;x.updatedAt=Date.now();return{notes:arr}});toastSafe('Готово.','ok')}catch(err){console.error(err);toastSafe(`Ошибка: ${err.message||err}`,'error')}}
  async function archiveEditing(){if(!editingId)return;await noteAction('archive',editingId);closeEditor()}
  function toastSafe(text,kind='normal'){if(typeof window.toast==='function')return window.toast(text,kind);let el=$('#n2Toast');if(!el){el=document.createElement('div');el.id='n2Toast';el.style='position:fixed;left:18px;right:18px;bottom:90px;z-index:11000;padding:13px;border-radius:13px;background:#7b4038;color:#fff;text-align:center';document.body.append(el)}el.textContent=text;clearTimeout(el._t);el._t=setTimeout(()=>el.remove(),3000)}
  function bindFirebase(){if(!window.firebase)return setTimeout(bindFirebase,300);try{const app=firebase.apps.find(a=>a.name==='montaji-aa-production')||firebase.app();auth=firebase.auth(app);db=firebase.firestore(app);auth.onAuthStateChanged(async u=>{if(unsub){unsub();unsub=null}if(!u){ready=false;notes=[];renderList();return}ready=true;const ref=db.doc(NOTES_V2_PATH.join('/'));unsub=ref.onSnapshot(snap=>{const d=snap.exists?snap.data()?.data||{}:{};notes=Array.isArray(d.notes)?d.notes:[];renderList()},err=>{console.error('notesV2 snapshot',err);toastSafe('Заметки: нет доступа к базе.','error')})} )}catch(e){console.error(e);setTimeout(bindFirebase,1000)}}
  function start(){injectStyle();ensureUI();renderList();bindFirebase();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
