import { getApps } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js';
import { getAuth, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js';
import { getFirestore, doc, onSnapshot, setDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';
import { firebaseConfig } from './firebase-config.js';

const ROOT_ID='notesV2Root', NOTES_REF=['appData','notes'];
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const fmtDate=d=>d?new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short'}).format(new Date(`${d}T12:00:00`)):'';
let db,auth,user=null,notes=[],unsubscribe=null,filter='all',open=false,observer=null,reminderTimers=new Map();

async function init(){
  const app=getApps().find(a=>a.name==='montaji-aa-production');
  if(!app) throw new Error('Firebase app is not ready');
  db=getFirestore(app); auth=getAuth(app);
  onAuthStateChanged(auth,u=>{user=u;if(u)subscribe();else{unsubscribe?.();unsubscribe=null;notes=[];renderList();}});
}
function subscribe(){unsubscribe?.();unsubscribe=onSnapshot(doc(db,...NOTES_REF),snap=>{const d=snap.exists()?snap.data()?.data||{}:{};notes=Array.isArray(d.notes)?d.notes.map(normalize):[];renderList();updateBadge();},()=>{});}
function normalize(n){return {id:n.id||uid(),type:n.type||'note',title:n.title||'Заметка',text:n.text||'',priority:n.priority||'normal',assignee:n.assignee||'all',dueDate:n.dueDate||'',dueTime:n.dueTime||'',completed:n.completed===true,archived:n.archived===true,updatedAt:n.updatedAt||''}}
async function save(next){if(!user)return;await setDoc(doc(db,...NOTES_REF),{data:{notes:next},version:2,updatedAt:serverTimestamp(),updatedBy:user.uid},{merge:true})}
function active(){return notes.filter(n=>!n.archived&&!n.completed)}
function visible(){let a=notes.filter(n=>!n.archived);if(filter==='today')a=a.filter(n=>n.dueDate===today());if(filter==='important')a=a.filter(n=>n.priority!=='normal');if(filter==='overdue')a=a.filter(n=>n.dueDate&&n.dueDate<today()&&!n.completed);if(filter==='done')a=notes.filter(n=>n.completed);return a.sort((a,b)=>{const ad=a.dueDate||'9999',bd=b.dueDate||'9999';return ad.localeCompare(bd)||Number(b.priority!=='normal')-Number(a.priority!=='normal')})}
function priorityLabel(p){return p==='urgent'?'СРОЧНО':p==='important'?'ВАЖНО':''}
function card(n){const overdue=n.dueDate&&n.dueDate<today()&&!n.completed;const when=n.dueDate?`${fmtDate(n.dueDate)}${n.dueTime?' · '+n.dueTime:''}`:'';return `<article class="n2-card ${n.priority} ${n.completed?'done':''} ${overdue?'overdue':''}" data-id="${esc(n.id)}"><button class="n2-check" data-complete="1" aria-label="${n.completed?'Вернуть':'Выполнить'}">${n.completed?'✓':''}</button><div class="n2-main"><div class="n2-line"><span class="n2-type">${n.type==='reminder'?'🔔':n.type==='task'?'☑':'📝'}</span><h3>${esc(n.title)}</h3>${priorityLabel(n.priority)?`<span class="n2-priority">${priorityLabel(n.priority)}</span>`:''}</div>${n.text?`<p>${esc(n.text)}</p>`:''}<div class="n2-meta">${when?`<span class="${overdue?'red':''}">${overdue?'Просрочено · ':''}${esc(when)}</span>`:''}<span>${n.assignee==='tolya'?'Анатолий':n.assignee==='sasha'?'Александр':'Обоим'}</span></div></div><button class="n2-more" data-edit="1">•••</button></article>`}
function renderList(){const root=document.getElementById(ROOT_ID);if(!root)return;const list=root.querySelector('.n2-list');if(!list)return;const a=visible();list.innerHTML=a.length?a.map(card).join(''):`<div class="n2-empty"><div>✦</div><strong>${filter==='done'?'Готово.':'Пусто.'}</strong><span>${filter==='done'?'Завершённых задач пока нет.':'Ничего не требует внимания.'}</span></div>`;root.querySelector('.n2-count').textContent=`${active().length} активных`;
  root.querySelectorAll('[data-complete]').forEach(b=>b.onclick=async e=>{e.stopPropagation();const id=b.closest('[data-id]').dataset.id;await save(notes.map(n=>n.id===id?{...n,completed:!n.completed,archived:false,updatedAt:new Date().toISOString()}:n));});
  root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=e=>{e.stopPropagation();openEditor(notes.find(n=>n.id===b.closest('[data-id]').dataset.id));});
}
function scheduleReminders(){for(const t of reminderTimers.values())clearTimeout(t);reminderTimers.clear();if(!('Notification' in window))return;notes.filter(n=>n.type==='reminder'&&!n.completed&&!n.archived&&n.dueDate&&n.dueTime).forEach(n=>{const at=new Date(`${n.dueDate}T${n.dueTime}:00`).getTime(),delay=at-Date.now();if(delay>0&&delay<2147483647){const t=setTimeout(()=>{if(Notification.permission==='granted')new Notification('Монтажи АА',{body:`${n.title}${n.assignee&&n.assignee!=='all'?' · '+(n.assignee==='tolya'?'Анатолий':'Александр'):''}`,tag:n.id});},delay);reminderTimers.set(n.id,t)}})}
function updateBadge(){scheduleReminders();const old=document.getElementById('activeNotes');if(old){old.innerHTML=`<button class="n2-launch" id="n2Launch"><span class="n2-launch-icon">✓</span><span><b>${active().length?active().length+' активных':'Нет активных задач'}</b><small>${notes.filter(n=>n.dueDate===today()&&!n.completed&&!n.archived).length} сегодня · ${notes.filter(n=>n.priority==='urgent'&&!n.completed&&!n.archived).length} срочных</small></span><i>›</i></button>`;document.getElementById('n2Launch').onclick=openHub;}}
function hub(){if(document.getElementById(ROOT_ID))return;const r=document.createElement('div');r.id=ROOT_ID;r.innerHTML=`<div class="n2-backdrop"></div><section class="n2-sheet"><header class="n2-head"><div><span class="n2-eyebrow">РАБОЧИЙ INBOX</span><h2>Задачи и заметки</h2><span class="n2-count"></span></div><button class="n2-close">×</button></header><div class="n2-summary"><div><b>${active().filter(n=>n.dueDate===today()).length}</b><span>сегодня</span></div><div><b>${active().filter(n=>n.priority!=='normal').length}</b><span>важных</span></div><div><b>${active().filter(n=>n.dueDate&&n.dueDate<today()).length}</b><span>просрочено</span></div></div><div class="n2-filters"><button data-filter="all">Все</button><button data-filter="today">Сегодня</button><button data-filter="important">Важные</button><button data-filter="overdue">Просрочено</button><button data-filter="done">Готово</button></div><div class="n2-list"></div><button class="n2-add" id="n2Add"><span>＋</span> Добавить</button></section>`;document.body.append(r);r.querySelector('.n2-backdrop').onclick=closeHub;r.querySelector('.n2-close').onclick=closeHub;r.querySelector('#n2Add').onclick=()=>openEditor();r.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;r.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderList();});r.querySelector('[data-filter="all"]').classList.add('active');renderList();}
function openHub(){hub();open=true;document.getElementById(ROOT_ID)?.classList.add('open');}
function closeHub(){document.getElementById(ROOT_ID)?.remove();open=false;}
function openEditor(n=null){const m=document.createElement('div');m.className='n2-editor';m.innerHTML=`<div class="n2-editor-backdrop"></div><section class="n2-editor-sheet"><header class="n2-head"><div><span class="n2-eyebrow">${n?'ИЗМЕНЕНИЕ':'НОВАЯ ЗАПИСЬ'}</span><h2>${n?'Редактировать':'Добавить'}</h2></div><button class="n2-close">×</button></header><div class="n2-type-tabs"><button data-t="note">📝 Заметка</button><button data-t="task">☑ Задача</button><button data-t="reminder">🔔 Напоминание</button></div><form><label>Что нужно запомнить?<input id="n2Title" required value="${esc(n?.title||'')}"></label><label>Подробности<textarea id="n2Text" rows="4" placeholder="Контекст, адрес, что проверить…">${esc(n?.text||'')}</textarea></label><div class="n2-form-grid"><label>Приоритет<select id="n2Priority"><option value="normal">Обычный</option><option value="important">Важная</option><option value="urgent">🔥 Срочно</option></select></label><label>Для кого<select id="n2Assignee"><option value="all">Обоим</option><option value="tolya">Анатолий</option><option value="sasha">Александр</option></select></label></div><div class="n2-due"><label>Дата<input id="n2Date" type="date" value="${esc(n?.dueDate||'')}"></label><label>Время<input id="n2Time" type="time" value="${esc(n?.dueTime||'')}"></label></div><button class="n2-save" type="submit">${n?'Сохранить изменения':'Создать'}</button></form></section></div>`;document.body.append(m);let type=n?.type||'note';const setType=t=>{type=t;m.querySelectorAll('[data-t]').forEach(x=>x.classList.toggle('active',x.dataset.t===t));m.querySelector('#n2Date').required=t!=='note';if(t==='reminder'&&!m.querySelector('#n2Date').value)m.querySelector('#n2Date').value=today();};setType(type);if(n){m.querySelector('#n2Priority').value=n.priority||'normal';m.querySelector('#n2Assignee').value=n.assignee||'all';}m.querySelectorAll('[data-t]').forEach(b=>b.onclick=()=>setType(b.dataset.t));m.querySelector('.n2-close').onclick=()=>m.remove();m.querySelector('.n2-editor-backdrop').onclick=()=>m.remove();m.querySelector('form').onsubmit=async e=>{e.preventDefault();const item={id:n?.id||uid(),type,title:m.querySelector('#n2Title').value.trim(),text:m.querySelector('#n2Text').value.trim(),priority:m.querySelector('#n2Priority').value,assignee:m.querySelector('#n2Assignee').value,dueDate:m.querySelector('#n2Date').value,dueTime:m.querySelector('#n2Time').value,completed:n?.completed===true,archived:n?.archived===true,updatedAt:new Date().toISOString()};if(!item.title)return;if(item.type==='reminder'&&item.dueDate&&item.dueTime&&'Notification' in window&&Notification.permission==='default'){try{await Notification.requestPermission()}catch(_){}}await save([...notes.filter(x=>x.id!==item.id),item]);m.remove();renderList();};}
function patchToday(){const b=document.getElementById('todayNoteBtn');if(b&&!b.dataset.n2){b.dataset.n2='1';b.onclick=e=>{e.preventDefault();e.stopImmediatePropagation();openEditor();}}updateBadge();}
function watch(){patchToday();const old=document.getElementById('activeNotes')?.closest('.inline-card');if(old&&!observer){observer=new MutationObserver(()=>{if(document.getElementById('activeNotes'))updateBadge();});observer.observe(old,{childList:true,subtree:true});}updateBadge();setTimeout(watch,1200);}
window.addEventListener('notes-v2:open',openHub);
init().then(watch).catch(console.error);
