import { getApps, getApp, initializeApp } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js';
import { getAuth, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js';
import { getFirestore, doc, onSnapshot, runTransaction, serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';
import { firebaseConfig } from './firebase-config.js';

const NOTES_DOC=['appData','notes'];
const $=id=>document.getElementById(id);
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const fmt=d=>d?new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short'}).format(new Date(`${d}T12:00:00`)).replace('.',''):'';
const norm=n=>({id:n?.id||uid(),type:['task','reminder','note'].includes(n?.type)?n.type:'note',title:String(n?.title||''),text:String(n?.text||n?.body||''),dueDate:String(n?.dueDate||n?.date||''),dueTime:String(n?.dueTime||n?.time||''),priority:['normal','important','urgent'].includes(n?.priority)?n.priority:'normal',assignee:['all','anatoly','alexander'].includes(n?.assignee)?n.assignee:'all',completed:n?.completed===true||n?.status==='done',archived:n?.archived===true});
let auth,db,user=null,notes=[],unsub=null,filter='all',q='',editId=null;
function legacy(){const x=$('activeNotes');if(x)return x.closest('.inline-card')||x;return [...document.querySelectorAll('.inline-card,section')].find(e=>{const t=(e.textContent||'').replace(/\s+/g,' ').trim();return t.startsWith('Заметки')&&t.includes('Общие для обоих телефонов')})}
function hideLegacy(){const x=legacy();if(x){x.style.setProperty('display','none','important');x.setAttribute('aria-hidden','true')}}
function counts(){const a=notes.filter(n=>!n.archived&&!n.completed),t=today();return{active:a.length,today:a.filter(n=>n.dueDate===t).length,overdue:a.filter(n=>n.dueDate&&n.dueDate<t).length,important:a.filter(n=>n.priority!=='normal').length}}
function list(){let a=notes.filter(n=>!n.archived);if(filter==='today')a=a.filter(n=>!n.completed&&n.dueDate===today());if(filter==='overdue')a=a.filter(n=>!n.completed&&n.dueDate&&n.dueDate<today());if(filter==='important')a=a.filter(n=>!n.completed&&n.priority!=='normal');if(filter==='done')a=a.filter(n=>n.completed);if(q)a=a.filter(n=>(n.title+' '+n.text).toLowerCase().includes(q.toLowerCase()));return a.sort((a,b)=>(a.completed?30:0)-(b.completed?30:0)||(a.dueDate||'9999').localeCompare(b.dueDate||'9999'))}
function card(n,full=true){const overdue=!n.completed&&n.dueDate&&n.dueDate<today(),p=n.priority==='urgent'?'urgent':n.priority==='important'?'important':'';return `<article class="ni-card ${p} ${n.completed?'is-done':''}" data-note-id="${esc(n.id)}"><button class="ni-check" data-note="toggle">${n.completed?'✓':''}</button><div class="ni-card-main"><div class="ni-type-row"><span class="ni-type">${n.type==='task'?'ЗАДАЧА':n.type==='reminder'?'НАПОМИНАНИЕ':'ЗАМЕТКА'}</span>${p?`<span class="ni-priority">${n.priority==='urgent'?'СРОЧНО':'ВАЖНО'}</span>`:''}</div><h3>${esc(n.title||'Без названия')}</h3>${n.text?`<p>${esc(n.text)}</p>`:''}<div class="ni-meta">${n.dueDate?`<span class="${overdue?'overdue':''}">${overdue?'Просрочено · ':''}${fmt(n.dueDate)}${n.dueTime?' · '+esc(n.dueTime):''}</span>`:''}${full?`<span>${n.assignee==='anatoly'?'Анатолий':n.assignee==='alexander'?'Александр':'Оба'}</span>`:''}</div></div><button class="ni-more" data-note="edit">•••</button></article>`}
function ensureUI(){hideLegacy();if($('notesInbox'))return;const anchor=legacy()||document.querySelector('.main')?.lastElementChild;const inbox=document.createElement('section');inbox.id='notesInbox';inbox.className='ni-preview';if(anchor?.parentNode)anchor.parentNode.insertBefore(inbox,anchor);else document.querySelector('.main')?.append(inbox);const modal=document.createElement('div');modal.id='notesModal';modal.className='ni-modal';modal.innerHTML=`<div class="ni-backdrop" data-close></div><div class="ni-sheet"><div class="ni-handle"></div><header class="ni-sheet-head"><div><span class="ni-eyebrow">РАБОЧИЙ INBOX</span><h2>Входящие</h2><p id="niSummary"></p></div><button class="ni-close" data-close>×</button></header><div class="ni-toolbar"><button class="ni-add" data-add>＋ Добавить</button><div class="ni-search-wrap"><span>⌕</span><input id="niSearch" placeholder="Найти"></div></div><div class="ni-tabs" id="niTabs"><button class="active" data-filter="all">Все</button><button data-filter="today">Сегодня</button><button data-filter="overdue">Просрочено</button><button data-filter="important">Важные</button><button data-filter="done">Выполнено</button></div><div id="niList"></div></div></div>`;document.body.append(modal);const ed=document.createElement('div');ed.id='niEditor';ed.className='ni-editor';ed.innerHTML=`<div class="ni-backdrop" data-close-editor></div><div class="ni-editor-sheet"><div class="ni-handle"></div><header class="ni-sheet-head"><div><span class="ni-eyebrow">НОВАЯ ЗАПИСЬ</span><h2 id="niEditorTitle">Добавить</h2></div><button class="ni-close" data-close-editor>×</button></header><div class="ni-type-picker"><button data-type="task" class="selected">☑ Задача</button><button data-type="reminder">🔔 Напоминание</button><button data-type="note">📝 Заметка</button></div><label>Что нужно сделать?<input id="niTitle" maxlength="120" placeholder="Например: позвонить клиенту"></label><label>Подробности<textarea id="niText" rows="4" placeholder="Комментарий, адрес, детали…"></textarea></label><div class="ni-grid"><label>Срок<input id="niDate" type="date"></label><label>Время<input id="niTime" type="time"></label></div><div class="ni-grid"><label>Приоритет<select id="niPriority"><option value="normal">Обычный</option><option value="important">Важная</option><option value="urgent">🔥 Срочно</option></select></label><label>Для кого<select id="niAssignee"><option value="all">Обоим</option><option value="anatoly">Анатолию</option><option value="alexander">Александру</option></select></label></div><div class="ni-editor-actions"><button class="ni-secondary" data-close-editor>Отмена</button><button class="ni-primary" data-save>Сохранить</button></div><button class="ni-delete" data-delete>Удалить навсегда</button></div></div>`;document.body.append(ed);bind();render()}
function openInbox(){ensureUI();$('notesModal').classList.add('open');render()}
function openEditor(id=null){ensureUI();editId=id;const n=id?notes.find(x=>x.id===id):null;$('niEditor').classList.add('open');$('niEditorTitle').textContent=n?'Редактировать':'Добавить';$('niTitle').value=n?.title||'';$('niText').value=n?.text||'';$('niDate').value=n?.dueDate||'';$('niTime').value=n?.dueTime||'';$('niPriority').value=n?.priority||'normal';$('niAssignee').value=n?.assignee||'all';document.querySelectorAll('.ni-type-picker button').forEach(b=>b.classList.toggle('selected',b.dataset.type===(n?.type||'task')));document.querySelector('[data-delete]').style.display=n?'block':'none'}
function close(){document.querySelectorAll('.ni-modal.open,.ni-editor.open').forEach(x=>x.classList.remove('open'))}
async function write(fn){if(!user)throw Error('Нет авторизации');const ref=doc(db,...NOTES_DOC);await runTransaction(db,async tx=>{const s=await tx.get(ref),cur=(Array.isArray(s.data()?.data?.notes)?s.data().data.notes:[]).map(norm);tx.set(ref,{data:{notes:fn(cur)},version:2,updatedAt:serverTimestamp(),updatedBy:user.uid},{merge:true})})}
async function save(){const title=$('niTitle').value.trim();if(!title)return $('niTitle').focus();const type=document.querySelector('.ni-type-picker .selected')?.dataset.type||'task';const p={id:editId||uid(),type,title,text:$('niText').value.trim(),dueDate:$('niDate').value,dueTime:$('niTime').value,priority:$('niPriority').value,assignee:$('niAssignee').value,completed:false,archived:false};await write(a=>editId?a.map(n=>n.id===editId?{...n,...p,completed:n.completed,archived:n.archived}:n):[...a,p]);close()}
async function toggle(id){await write(a=>a.map(n=>n.id===id?{...n,completed:!n.completed}:n))}
async function remove(){if(!editId)return;if(!confirm('Удалить навсегда?'))return;await write(a=>a.filter(n=>n.id!==editId));close()}
function render(){hideLegacy();const c=counts(),v=list(),preview=v.filter(n=>!n.completed).slice(0,3),inbox=$('notesInbox');if(inbox)inbox.innerHTML=`<div class="ni-preview-head"><div><span class="ni-eyebrow">РАБОЧИЙ INBOX</span><h2>Входящие <b>${c.active}</b></h2><p>${c.today?c.today+' сегодня · ':''}${c.overdue?c.overdue+' просрочено · ':''}${c.important?c.important+' важных':''}</p></div><button data-preview-add>＋</button></div>${preview.length?`<div class="ni-preview-list">${preview.map(n=>card(n,false)).join('')}</div>`:`<div class="ni-empty"><strong>Всё спокойно</strong><span>Нет активных задач</span></div>`}<button class="ni-open-all" data-open-all>Открыть все входящие <span>→</span></button>`;if($('niList'))$('niList').innerHTML=v.length?v.map(n=>card(n)).join(''):`<div class="ni-empty large"><strong>Здесь пока пусто</strong><span>Добавь задачу, напоминание или заметку</span></div>`;if($('niSummary'))$('niSummary').textContent=`${c.active} активных · ${c.today} сегодня · ${c.overdue} просрочено`;document.querySelectorAll('#niTabs button').forEach(b=>b.classList.toggle('active',b.dataset.filter===filter))}
function bind(){document.addEventListener('click',async e=>{if(e.target.closest('[data-close]')||e.target.closest('[data-close-editor]'))return close();if(e.target.closest('[data-open-all]'))return openInbox();if(e.target.closest('[data-preview-add]')||e.target.closest('[data-add]'))return openEditor();if(e.target.closest('[data-save]'))return save();if(e.target.closest('[data-delete]'))return remove();const tab=e.target.closest('#niTabs button');if(tab){filter=tab.dataset.filter;return render()}const type=e.target.closest('.ni-type-picker button');if(type){document.querySelectorAll('.ni-type-picker button').forEach(b=>b.classList.remove('selected'));type.classList.add('selected');return}const action=e.target.closest('[data-note]');if(action){const id=action.closest('[data-note-id]')?.dataset.noteId;if(action.dataset.note==='toggle')await toggle(id);else openEditor(id)}});document.addEventListener('input',e=>{if(e.target.id==='niSearch'){q=e.target.value;render()}})}
function start(){const apps=getApps();const base=apps.find(a=>a.name==='montaji-aa-production')||apps[0]||initializeApp(firebaseConfig,'montaji-aa-production-notes');auth=getAuth(base);db=getFirestore(base);const mountNow=()=>{if(auth.currentUser){user=auth.currentUser;ensureUI();if(!unsub)unsub=onSnapshot(doc(db,...NOTES_DOC),s=>{notes=(Array.isArray(s.data()?.data?.notes)?s.data().data.notes:[]).map(norm);render()})}else ensureUI()};onAuthStateChanged(auth,u=>{user=u;if(unsub){unsub();unsub=null}if(u){ensureUI();unsub=onSnapshot(doc(db,...NOTES_DOC),s=>{notes=(Array.isArray(s.data()?.data?.notes)?s.data().data.notes:[]).map(norm);render()})}else render()});setTimeout(mountNow,700);setTimeout(hideLegacy,1500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();