(() => {
  const FIREBASE_VERSION='10.14.1';
  const DOC=['appData','shared'];
  const NOTES_DOC=['appData','notes'];
  const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
  const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
  const money=n=>new Intl.NumberFormat('ru-RU').format(Math.round(Number(n)||0))+' ₽';
  const dateKey=d=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`};
  const today=()=>dateKey(new Date());
  const fmt=d=>new Intl.DateTimeFormat('ru-RU',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date(`${d}T12:00:00`));
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  let F,db,auth,user=null,ready=false,state={jobs:[],expenses:[],notes:[]},unsub=null;
  const styles=`<style id="v9-style">
  .v9-card{background:var(--card,#fff);border:1px solid rgba(30,45,34,.08);border-radius:22px;padding:16px;margin:0 0 14px;box-shadow:0 10px 30px rgba(20,35,25,.06)}body.dark .v9-card{background:#18201a;border-color:rgba(255,255,255,.08)}
  .v9-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:12px}.v9-head h2{margin:0;font-size:18px}.v9-head span{font-size:12px;opacity:.58}.v9-btn{border:0;border-radius:13px;padding:9px 12px;font:inherit;cursor:pointer;background:#edf2ec;color:inherit}.v9-btn.primary{background:#27392a;color:#fff}.v9-btn.danger{background:#f7e9e7;color:#8b3026}.v9-actions{display:flex;gap:8px;flex-wrap:wrap}
  .v9-expense{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px 0;border-top:1px solid rgba(30,45,34,.08)}.v9-expense:first-child{border-top:0}.v9-expense b{font-size:15px}.v9-expense small{display:block;opacity:.55;margin-top:3px}.v9-expense strong{white-space:nowrap}.v9-total{display:flex;justify-content:space-between;margin-top:12px;padding-top:12px;border-top:1px solid rgba(30,45,34,.1);font-weight:700}
  .v9-note{padding:12px;border-radius:16px;background:rgba(111,126,84,.09);margin-top:9px}.v9-note.arch{opacity:.68}.v9-note-top{display:flex;justify-content:space-between;gap:10px}.v9-note p{margin:7px 0 0;white-space:pre-wrap;line-height:1.4}.v9-note small{opacity:.55}.v9-empty{opacity:.52;padding:8px 0}.v9-modal{position:fixed;inset:0;z-index:10000;display:flex;align-items:flex-end;justify-content:center;background:rgba(5,10,6,.48);padding:16px}.v9-sheet{width:min(560px,100%);max-height:92vh;overflow:auto;background:var(--card,#fff);border-radius:28px;padding:20px;box-shadow:0 30px 80px rgba(0,0,0,.28)}body.dark .v9-sheet{background:#172019}.v9-sheet h2{margin:0 0 16px}.v9-field{display:block;margin:10px 0}.v9-field span{display:block;font-size:12px;opacity:.62;margin-bottom:6px}.v9-field input,.v9-field textarea,.v9-field select{box-sizing:border-box;width:100%;border:1px solid rgba(30,45,34,.14);border-radius:13px;padding:11px 12px;background:transparent;color:inherit;font:inherit}.v9-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.v9-archive{margin-top:12px}.v9-archive summary{cursor:pointer;font-weight:700}.v9-day-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:12px 0}.v9-stat{padding:11px;border-radius:15px;background:rgba(111,126,84,.09)}.v9-stat small{display:block;opacity:.55}.v9-stat b{display:block;margin-top:4px}.v9-archive-list{margin-top:10px}.v9-archive-item{padding:11px 0;border-top:1px solid rgba(30,45,34,.08)}.v9-archive-item:first-child{border-top:0}.v9-badge{display:inline-block;padding:4px 8px;border-radius:999px;background:rgba(111,126,84,.12);font-size:11px;margin-left:6px}
  @media(max-width:700px){.v9-day-summary{grid-template-columns:1fr 1fr 1fr}.v9-modal{padding:8px}.v9-sheet{border-radius:24px 24px 0 0}.v9-grid{grid-template-columns:1fr}}
  </style>`;
  function injectStyle(){if(!document.getElementById('v9-style'))document.head.insertAdjacentHTML('beforeend',styles)}
  function insertHome(){
    const list=$('#todayList');if(!list||$('#v9TodayExpenses'))return;
    const exp=document.createElement('section');exp.id='v9TodayExpenses';exp.className='v9-card';exp.innerHTML='<div class="v9-head"><h2>Расходы сегодня</h2><button class="v9-btn" id="v9AddExpense">＋ Добавить</button></div><div id="v9ExpenseList"></div>';
    const upcoming=$('#upcoming')?.parentElement;list.parentElement.insertBefore(exp,upcoming||null);$('#v9AddExpense').onclick=()=>openExpense(today());
    const notes=document.createElement('section');notes.id='v9Notes';notes.className='v9-card';notes.innerHTML='<div class="v9-head"><div><h2>Заметки</h2><span>Всегда под рукой</span></div><button class="v9-btn" id="v9AddNote">＋ Заметка</button></div><div id="v9ActiveNotes"></div><details class="v9-archive"><summary>Архив заметок</summary><div id="v9ArchivedNotes"></div></details>';
    if(upcoming)upcoming.parentElement.insertBefore(notes,upcoming);else document.querySelector('.main')?.append(notes);$('#v9AddNote').onclick=()=>openNote();
  }
  function renderHome(){insertHome();const day=today(),ex=state.expenses.filter(e=>e.date===day),host=$('#v9ExpenseList');if(host){host.innerHTML=ex.length?ex.map(e=>`<div class="v9-expense"><div><b>${esc(e.category||'Прочее')}</b><small>${esc(e.comment||'Без комментария')}</small></div><strong>− ${money(e.amount)}</strong></div>`).join(''):'<div class="v9-empty">Сегодня расходов ещё нет.</div>';if(ex.length)host.insertAdjacentHTML('beforeend',`<div class="v9-total"><span>Итого</span><span>− ${money(ex.reduce((s,e)=>s+Number(e.amount||0),0))}</span></div>`)}
    const notes=state.notes.filter(n=>n.archived!==true).sort((a,b)=>(b.updatedAt||'').localeCompare(a.updatedAt||'')),arch=state.notes.filter(n=>n.archived===true).sort((a,b)=>(b.updatedAt||'').localeCompare(a.updatedAt||''));const ah=$('#v9ActiveNotes'),ar=$('#v9ArchivedNotes');
    const card=n=>`<div class="v9-note ${n.archived?'arch':''}"><div class="v9-note-top"><div><b>${esc(n.title||'Заметка')}</b>${n.archived?'<span class="v9-badge">архив</span>':''}<small>${n.updatedAt?` · ${esc(n.updatedAt.slice(0,10))}`:''}</small></div><div class="v9-actions"><button class="v9-btn" data-note-edit="${esc(n.id)}">Изм.</button>${n.archived?`<button class="v9-btn" data-note-restore="${esc(n.id)}">Вернуть</button>`:`<button class="v9-btn" data-note-archive="${esc(n.id)}">Архив</button>`}</div></div><p>${esc(n.text||'')}</p></div>`;
    if(ah)ah.innerHTML=notes.length?notes.map(card).join(''):'<div class="v9-empty">Активных заметок нет.</div>';if(ar)ar.innerHTML=arch.length?arch.map(card).join(''):'<div class="v9-empty">Архив пуст.</div>';
    $$('[data-note-edit]').forEach(b=>b.onclick=()=>openNote(state.notes.find(n=>n.id===b.dataset.noteEdit)));$$('[data-note-archive]').forEach(b=>b.onclick=()=>setNoteState(b.dataset.noteArchive,true));$$('[data-note-restore]').forEach(b=>b.onclick=()=>setNoteState(b.dataset.noteRestore,false));
  }
  async function save(mut){if(!ready||!user)throw Error('Нет соединения с общей базой');const ref=F.doc(db,...DOC);await F.runTransaction(db,async tx=>{const s=await tx.get(ref),cur=s.exists()?s.data()?.data||{}:{},next=await mut(JSON.parse(JSON.stringify(cur)));tx.set(ref,{data:next,version:9,updatedAt:F.serverTimestamp(),updatedBy:user.uid},{merge:true})})}
  async function noteSave(mut){if(!ready||!user)throw Error('Нет соединения с общей базой');const ref=F.doc(db,...NOTES_DOC);await F.runTransaction(db,async tx=>{const s=await tx.get(ref),cur=s.exists()?s.data()?.data||{}:{},next=await mut(JSON.parse(JSON.stringify(cur)));tx.set(ref,{data:next,version:9,updatedAt:F.serverTimestamp(),updatedBy:user.uid},{merge:true})})}
  async function setNoteState(id,arch){try{await noteSave(cur=>({...cur,notes:(Array.isArray(cur.notes)?cur.notes:[]).map(n=>n.id===id?{...n,archived:arch,updatedAt:new Date().toISOString()}:n)}))}catch(e){alert(e.message)}}
  function modal(html){const m=document.createElement('div');m.className='v9-modal';m.innerHTML=`<div class="v9-sheet">${html}</div>`;document.body.append(m);m.addEventListener('click',e=>{if(e.target===m)m.remove()});return m}
  function openNote(n=null){const m=modal(`<div class="v9-head"><h2>${n?'Изменить заметку':'Новая заметка'}</h2><button class="v9-btn" data-x>×</button></div><form id="v9NoteForm"><label class="v9-field"><span>Заголовок</span><input id="v9NoteTitle" required value="${esc(n?.title||'')}"></label><label class="v9-field"><span>Текст</span><textarea id="v9NoteText" rows="5" required>${esc(n?.text||'')}</textarea></label><div class="v9-actions"><button class="v9-btn primary">Сохранить</button>${n?'<button type="button" class="v9-btn danger" id="v9DeleteNote">Удалить</button>':''}</div></form>`);m.querySelector('[data-x]').onclick=()=>m.remove();m.querySelector('#v9NoteForm').onsubmit=async e=>{e.preventDefault();const item={id:n?.id||uid(),title:$('#v9NoteTitle').value.trim(),text:$('#v9NoteText').value.trim(),archived:n?.archived===true,updatedAt:new Date().toISOString()};if(!item.title||!item.text)return;try{await noteSave(cur=>({...cur,notes:[...(Array.isArray(cur.notes)?cur.notes:[]).filter(x=>x.id!==item.id),item]}));m.remove()}catch(err){alert(err.message)}};m.querySelector('#v9DeleteNote')?.addEventListener('click',async()=>{try{await noteSave(cur=>({...cur,notes:(cur.notes||[]).filter(x=>x.id!==n.id)}));m.remove()}catch(err){alert(err.message)}})}
  function openExpense(d){const m=modal(`<div class="v9-head"><h2>Расход · ${esc(fmt(d))}</h2><button class="v9-btn" data-x>×</button></div><form id="v9ExpenseForm"><div class="v9-grid"><label class="v9-field"><span>Дата</span><input id="v9ExpDate" type="date" required value="${esc(d)}"></label><label class="v9-field"><span>Сумма, ₽</span><input id="v9ExpAmount" type="number" min="0.01" step="0.01" required></label></div><label class="v9-field"><span>Категория</span><select id="v9ExpCat"><option>Топливо</option><option>Аренда</option><option>Парковка</option><option>Материалы</option><option>Инструмент</option><option>Прочее</option></select></label><label class="v9-field"><span>Комментарий</span><textarea id="v9ExpComment" rows="3" placeholder="Что оплатили?"></textarea></label><div class="v9-actions"><button class="v9-btn primary">Сохранить расход</button></div></form></div>`);m.querySelector('[data-x]').onclick=()=>m.remove();m.querySelector('#v9ExpenseForm').onsubmit=async e=>{e.preventDefault();const amount=Number($('#v9ExpAmount').value);if(!(amount>0))return;const item={id:uid(),date:$('#v9ExpDate').value,amount,category:$('#v9ExpCat').value,comment:$('#v9ExpComment').value.trim()};try{await save(cur=>({...cur,expenses:[...(cur.expenses||[]),item]}));m.remove()}catch(err){alert(err.message)}}}
  function archiveForDate(d){const jobs=state.jobs.filter(j=>j.date===d&&j.status!=='Отменён'),expenses=state.expenses.filter(e=>e.date===d),income=jobs.filter(j=>j.status==='Выполнен').reduce((s,j)=>s+Number(j.price||0),0),exp=expenses.reduce((s,e)=>s+Number(e.amount||0),0);return{jobs,expenses,income,exp,net:income-exp}}
  function showArchive(d){const x=archiveForDate(d),m=modal(`<div class="v9-head"><div><span style="opacity:.55">Архив дня</span><h2>${esc(fmt(d))}</h2></div><button class="v9-btn" data-x>×</button></div><div class="v9-day-summary"><div class="v9-stat"><small>Доход</small><b>${money(x.income)}</b></div><div class="v9-stat"><small>Расход</small><b>− ${money(x.exp)}</b></div><div class="v9-stat"><small>Чистыми</small><b>${money(x.net)}</b></div></div><div class="v9-actions"><button class="v9-btn primary" id="v9ArcExp">＋ Расход</button></div><div class="v9-archive-list"><h3>Монтажи и выезды</h3>${x.jobs.length?x.jobs.map(j=>`<div class="v9-archive-item"><b>${esc(j.client||'Без клиента')}</b><span class="v9-badge">${esc(j.type||'Выезд')}</span><div>${money(j.price||0)} · ${esc(j.status||'')}</div></div>`).join(''):'<div class="v9-empty">Записей нет.</div>'}<h3>Расходы</h3>${x.expenses.length?x.expenses.map(e=>`<div class="v9-archive-item"><b>${esc(e.category||'Прочее')}</b><div>− ${money(e.amount)} · ${esc(e.comment||'')}</div></div>`).join(''):'<div class="v9-empty">Расходов нет.</div>'}</div>`);m.querySelector('[data-x]').onclick=()=>m.remove();m.querySelector('#v9ArcExp').onclick=()=>{m.remove();openExpense(d)}}
  function observeCalendar(){const mo=new MutationObserver(()=>{const cal=$('#calendar');if(!cal||cal.dataset.v9bound)return;cal.dataset.v9bound='1';cal.addEventListener('click',e=>{const b=e.target.closest('.day[data-date]');if(!b)return;setTimeout(()=>{const sheet=[...document.querySelectorAll('.modal.open .sheet')].pop();if(!sheet||sheet.dataset.v9archive)return;sheet.dataset.v9archive='1';const d=b.dataset.date,p=archiveForDate(d),panel=document.createElement('div');panel.className='v9-card';panel.innerHTML=`<div class="v9-head"><h2>Итоги дня</h2><button class="v9-btn" id="v9ArchiveOpen">Открыть весь день</button></div><div class="v9-day-summary"><div class="v9-stat"><small>Доход</small><b>${money(p.income)}</b></div><div class="v9-stat"><small>Расход</small><b>− ${money(p.exp)}</b></div><div class="v9-stat"><small>Чистыми</small><b>${money(p.net)}</b></div></div>`;sheet.append(panel);panel.querySelector('#v9ArchiveOpen').onclick=()=>showArchive(d)},100)})});mo.observe(document.body,{childList:true,subtree:true})}
  async function boot(){injectStyle();const [appMod,authMod,fs]=await Promise.all([import(`https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-app.js`),import(`https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-auth.js`),import(`https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-firestore.js`)]);const cfg=await import('./firebase-config.js');const apps=appMod.getApps();const app=apps.find(a=>a.name==='montaji-aa-v5')||appMod.initializeApp(cfg.firebaseConfig,'montaji-aa-v9');auth=authMod.getAuth(app);db=fs.getFirestore(app);authMod.onAuthStateChanged(auth,u=>{user=u;if(!u)return;const ref=F.doc(db,...DOC),nref=F.doc(db,...NOTES_DOC);if(unsub)unsub();let shared={},notes={};const paint=()=>{state={jobs:Array.isArray(shared.jobs)?shared.jobs:[],expenses:Array.isArray(shared.expenses)?shared.expenses:[],notes:Array.isArray(notes.notes)?notes.notes:[]};ready=true;renderHome()};const us=F.onSnapshot(ref,s=>{shared=s.exists()?s.data()?.data||{}:{};paint()});const un=F.onSnapshot(nref,s=>{notes=s.exists()?s.data()?.data||{}:{};paint()});unsub=()=>{us();un()};insertHome();observeCalendar()})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,700));else setTimeout(boot,700);
})();
