import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const index=fs.readFileSync('index.html','utf8');
const app=fs.readFileSync('app.js','utf8');
const css=fs.readFileSync('styles.css','utf8');
const rules=fs.readFileSync('firestore.rules','utf8');

test('single production app module and cache version',()=>{assert.match(index,/app\.js\?v=5-final-20260812/);assert.equal((index.match(/<script[^>]+type=["']module["']/g)||[]).length,1)});
test('no browser database/cache is used',()=>{assert.equal(app.includes('localStorage'),false);assert.equal(app.includes('sessionStorage'),false);assert.match(app,/state=emptyState\(\)/)});
test('Firestore architecture is server-first, transactional and realtime',()=>{assert.match(app,/getDocFromServer/);assert.match(app,/onSnapshot/);assert.match(app,/runTransaction/);assert.match(app,/serverTimestamp/);assert.match(app,/DOC_PATH = \['appData', 'shared'\]/)});
test('Firebase auth uses verified email/password',()=>{assert.match(app,/signInWithEmailAndPassword/);assert.match(app,/createUserWithEmailAndPassword/);assert.match(app,/sendEmailVerification/);assert.match(rules,/email_verified == true/);assert.match(rules,/sign_in_provider != 'anonymous'/)});
test('map routing is Russian-first',()=>{assert.match(app,/yandex\.ru\/maps/);assert.match(app,/2gis\.ru\/search/);assert.equal(app.includes('google.com/maps'),false)});
test('finance has day, week, month and all-time views plus expenses',()=>{assert.match(app,/totals\('day'\)/);assert.match(app,/totals\('week'\)/);assert.match(app,/totals\('month'\)/);assert.match(app,/totals\('all'\)/);assert.match(index,/moneyHighlights/);assert.match(index,/expenseArchive/)});
test('income is based on completed work only',()=>{assert.match(app,/isDone\(j\)/);assert.match(app,/activityDate\(j\)/);assert.match(app,/type==='Доп\. доход'\?'Выполнен'/)});
test('exact expense amounts including 180 are accepted',()=>{assert.match(index,/id="eAmount" type="number" min="0\.01" step="0\.01"/);assert.match(app,/const amount=num\(\$\('#eAmount'\)\.value\)/)});
test('concurrent edits use Firestore transactions',()=>{assert.match(app,/F\.runTransaction\(db/);assert.match(app,/tx\.get\(ref\)/);assert.match(app,/tx\.set\(ref/)});
test('smart operational insights exist',()=>{assert.match(app,/просроченных выездов/);assert.match(app,/полностью загружен/);assert.match(app,/выполненных работ ещё не оплачено/)});
test('Excel-compatible export and JSON disaster backup exist',()=>{assert.match(app,/exportExcel/);assert.match(app,/text\/csv;charset=utf-8/);assert.match(app,/exportJson/);assert.match(app,/restoreJson/)});
test('modern responsive light/dark visual system exists',()=>{assert.match(css,/linear-gradient/);assert.match(css,/body\.dark/);assert.match(css,/backdrop-filter/);assert.match(css,/@media\(max-width:700px\)/)});
test('legacy modules are not wired into production',()=>{for(const x of ['firebase-sync.js','archive.js','app-v4.js','app-v3.js'])assert.equal(index.includes(x),false)});
