import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const index=fs.readFileSync('index.html','utf8');
const app=fs.readFileSync('app.js','utf8');
const v9=fs.readFileSync('v9.js','utf8');
const css=fs.readFileSync('styles.css','utf8');
const rules=fs.readFileSync('firestore.rules','utf8');

test('production wiring is single-entry and v9 is cache-busted',()=>{assert.match(index,/app\.js\?v=9-core-20260818/);assert.match(index,/v9\.js\?v=20260818-1/);assert.equal((index.match(/<script[^>]+type=["']module["']/g)||[]).length,1);assert.doesNotMatch(index,/enhancement-v8\.js/)});
test('existing app remains server-first and transactional',()=>{assert.match(app,/FIREBASE_VERSION = '10\.14\.1'/);assert.match(app,/DOC_PATH = \['appData', 'shared'\]/);assert.match(app,/getDocFromServer/);assert.match(app,/onSnapshot/);assert.match(app,/F\.runTransaction\(db/);assert.match(app,/serverTimestamp/);assert.doesNotMatch(app,/localStorage|sessionStorage/)});
test('authentication and security gates remain intact',()=>{assert.match(app,/signInWithEmailAndPassword/);assert.match(app,/createUserWithEmailAndPassword/);assert.match(app,/sendEmailVerification/);assert.match(rules,/email_verified == true/);assert.match(rules,/sign_in_provider != 'anonymous'/)});
test('existing finance and navigation surfaces remain present',()=>{assert.match(index,/todayIncome/);assert.match(index,/todayExpense/);assert.match(index,/moneyHighlights/);assert.match(index,/expenseArchive/);assert.match(index,/scheduleScreen/);assert.match(index,/calendar/);assert.match(index,/clientsScreen/);assert.match(index,/moreScreen/)});
test('Russian-first map routing remains intact',()=>{assert.match(app,/yandex\.ru\/maps/);assert.match(app,/2gis\.ru\/search/);assert.doesNotMatch(app,/google\.com\/maps/)});
test('responsive visual system remains intact',()=>{assert.match(css,/linear-gradient/);assert.match(css,/body\.dark/);assert.match(css,/backdrop-filter/);assert.match(css,/@media\(max-width:700px\)/)});
test('v9 keeps shared jobs and expenses in the existing document',()=>{assert.match(v9,/const DOC=\['appData','shared'\]/);assert.match(v9,/state=\{jobs:\[\],expenses:\[\],notes:\[\]\}/);assert.match(v9,/expenses:\[\.\.\.\(cur\.expenses\|\|\[\]\),item\]/);assert.match(v9,/F\.runTransaction\(db/)});
test('v9 keeps notes isolated from the legacy shared schema',()=>{assert.match(v9,/const NOTES_DOC=\['appData','notes'\]/);assert.match(v9,/noteSave/);assert.match(v9,/Архив заметок/);assert.match(v9,/data-note-archive/);assert.match(v9,/data-note-restore/)});
test('v9 home exposes daily expenses and note management',()=>{assert.match(v9,/Расходы сегодня/);assert.match(v9,/Добавить расход/);assert.match(v9,/Новая заметка/);assert.match(v9,/Изменить заметку/);assert.match(v9,/Удалить/)});
test('v9 calendar produces a complete day archive',()=>{assert.match(v9,/observeCalendar/);assert.match(v9,/Архив дня/);assert.match(v9,/Открыть весь день/);assert.match(v9,/Монтажи и выезды/);assert.match(v9,/Расходы/);assert.match(v9,/net:income-exp/)});
test('v9 expense form supports arbitrary positive decimal amounts and dates',()=>{assert.match(v9,/type="number" min="0\.01" step="0\.01"/);assert.match(v9,/id="v9ExpDate" type="date"/);assert.match(v9,/const amount=Number\(\$\('#v9ExpAmount'\)\.value\)/)});
test('v9 mutations preserve unrelated fields and use transactions',()=>{assert.match(v9,/const cur=s\.exists\(\)\?s\.data\(\)\?\.data\|\|\{\}:\{\}/);assert.match(v9,/\{\.\.\.cur,expenses:/);assert.match(v9,/\{\.\.\.cur,notes:/);assert.match(v9,/updatedBy:user\.uid/)});
