const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
export const buildMoreModel=({user=null,dataStatus='idle',cacheStatus='none',stores=[],notes=[]})=>({email:user?.email||'',dataStatus,cacheStatus,stores:Array.isArray(stores)?stores:[],notes:Array.isArray(notes)?notes.filter(note=>!note?.archived).length:0});
export const renderMore=({root,model,actions={}})=>{
 if(!root)return;const cacheText=model.cacheStatus==='cached'?'Локальный снимок загружен':'Локального снимка нет';
 root.innerHTML='<section class="more-screen"><header class="screen-heading"><span>Пространство</span><h1>Ещё</h1><p>Заметки, справочники и данные приложения</p></header><section class="settings-section"><button type="button" class="settings-row" data-action="notes"><span><strong>Заметки</strong><small>Важное для работы</small></span><b>'+model.notes+' ›</b></button><button type="button" class="settings-row" data-action="stores"><span><strong>Магазины</strong><small>Адреса и контакты</small></span><b>'+model.stores.length+' ›</b></button></section><details class="technical-section"><summary>Данные и синхронизация</summary><div class="technical-content"><p>Аккаунт: '+esc(model.email||'—')+'</p><p>База: '+esc(model.dataStatus)+'</p><p>'+cacheText+'</p><div class="more-actions"><button type="button" data-action="clear-cache">Очистить локальные данные / кэш</button><button type="button" data-action="export">Экспорт</button><button type="button" data-action="signout">Выйти</button></div></div></details></section>';
 root.querySelector('[data-action="notes"]')?.addEventListener('click',()=>actions.openNotes?.());
 root.querySelector('[data-action="stores"]')?.addEventListener('click',()=>actions.openStores?.());
 root.querySelector('[data-action="clear-cache"]')?.addEventListener('click',()=>actions.clearCache?.());root.querySelector('[data-action="export"]')?.addEventListener('click',()=>actions.export?.());root.querySelector('[data-action="signout"]')?.addEventListener('click',()=>actions.signOut?.());
};
