const U=(window.APP_CONFIG&&window.APP_CONFIG.supabaseUrl)||['https://','ijiekvurwnwrpvaxkdvn','.supabase.co'].join('');
const K=(window.APP_CONFIG&&window.APP_CONFIG.supabaseKey)||['eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9','eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqaWVrdnVyd253cnB2YXhrZHZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQyNjIyMDAsImV4cCI6MjA4OTgzODIwMH0','qOkchV3RDmkDfAK8IrH1PCynPYy8KBUM5C9oIT0UdWE'].join('.');
const sb=window.supabase.createClient(U,K);
const S=['Бронь','Подтверждён','Выполнен','Перенос','Отменён'],P=['Не оплачено','Частично','Оплачено'],SL=[{id:1,l:'1 слот',s:'11:00–12:00 приезд'},{id:2,l:'2 слот',s:'14:00–16:00 приезд'},{id:3,l:'3 слот',s:'без времени'},{id:4,l:'4 слот',s:'без времени'}];
const st={session:null,profile:null,stores:[],jobs:[],exp:{},m:new Date().getMonth(),y:new Date().getFullYear(),rm:new Date().getMonth()+1,ry:new Date().getFullYear(),d:f(new Date()),q:'',fl:{store:'all',status:'all',payment:'all',fill:'all'}};
const $=id=>document.getElementById(id);const E={a:$('authScreen'),app:$('appShell'),af:$('authForm'),ae:$('authEmail'),ap:$('authPassword'),am:$('authMessage'),su:$('signUpBtn'),lo:$('logoutBtn'),ue:$('userEmail'),ur:$('userRole'),mt:$('monthTitle'),cg:$('calendarGrid'),pm:$('prevMonthBtn'),nm:$('nextMonthBtn'),ab:$('addJobBtn'),of:$('openFiltersBtn'),si:$('searchInput'),rmo:$('reportMonth'),ryr:$('reportYear'),sg:$('statsGrid'),al:$('archiveList'),em:$('exportMonthBtn'),ey:$('exportYearBtn'),js:$('jobSheet'),jt:$('jobSheetTitle'),jf:$('jobForm'),jid:$('jobId'),jd:$('jobDate'),jslot:$('jobSlot'),jc:$('jobClient'),jph:$('jobPhone'),ja:$('jobAddress'),jst:$('jobStore'),jpr:$('jobPrice'),jss:$('jobStatus'),jps:$('jobPayment'),jco:$('jobComment'),jdel:$('deleteJobBtn'),ds:$('daySheet'),dt:$('daySheetTitle'),dei:$('dayExpenseInput'),dec:$('dayExpenseComment'),des:$('saveDayExpenseBtn'),dsl:$('daySlots'),dst:$('dayStats'),fs:$('filtersSheet'),fst:$('filterStore'),fss:$('filterStatus'),fps:$('filterPayment'),ff:$('filterFill'),fa:$('applyFiltersBtn'),fr:$('resetFiltersBtn')};
boot();
async function boot(){fill();bind();const {data}=await sb.auth.getSession();st.session=data.session;await sess();sb.auth.onAuthStateChange(async(_,s)=>{st.session=s;await sess();});}
function fill(){E.jslot.innerHTML=SL.map(x=>`<option value="${x.id}">${x.l} — ${x.s}</option>`).join('');E.jss.innerHTML=S.map(x=>`<option>${x}</option>`).join('');E.jps.innerHTML=P.map(x=>`<option>${x}</option>`).join('');E.rmo.innerHTML=Array.from({length:12},(_,i)=>`<option value="${i+1}">${cap(new Date(2025,i,1).toLocaleDateString('ru-RU',{month:'long'}))}</option>`).join('');}
function bind(){E.af.addEventListener('submit',signin);E.su.addEventListener('click',signup);E.lo.addEventListener('click',()=>sb.auth.signOut());E.pm.addEventListener('click',()=>shift(-1));E.nm.addEventListener('click',()=>shift(1));E.ab.addEventListener('click',()=>oj());E.jf.addEventListener('submit',saveJob);E.jdel.addEventListener('click',delJob);E.des.addEventListener('click',saveExp);E.si.addEventListener('input',e=>{st.q=e.target.value.trim().toLowerCase();rc();});E.rmo.addEventListener('change',e=>{st.rm=+e.target.value;rr();});E.ryr.addEventListener('change',e=>{st.ry=+e.target.value;rr();});E.em.addEventListener('click',()=>csv(false));E.ey.addEventListener('click',()=>csv(true));E.of.addEventListener('click',()=>os('filtersSheet'));E.fa.addEventListener('click',()=>{st.fl={store:E.fst.value,status:E.fss.value,payment:E.fps.value,fill:E.ff.value};cs('filtersSheet');rc();});E.fr.addEventListener('click',()=>{st.fl={store:'all',status:'all',payment:'all',fill:'all'};ff();rc();});document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>cs(b.dataset.close)));document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>sw(b.dataset.screen)));}
async function sess(){if(!st.session){st.profile=null;E.a.classList.remove('hidden');E.app.classList.add('hidden');return;}const ok=await lp();if(!ok)return;await ld();E.a.classList.add('hidden');E.app.classList.remove('hidden');E.ue.textContent=st.profile.email||'';E.ur.textContent=st.profile.role==='admin'?'Админ':'Просмотр';ra();}
async function lp(){const {data,error}=await sb.from('profiles').select('id,email,role').eq('id',st.session.user.id).maybeSingle();if(error||!data){msg('Доступ не разрешён для этого email.',1);await sb.auth.signOut();return false;}st.profile=data;return true;}
async function ld(){const [{data:stores},{data:jobs},{data:ex}]=await Promise.all([sb.from('stores').select('id,name,sort_order').eq('is_active',true).order('sort_order'),sb.from('jobs').select('id,job_date,slot,client_name,phone,address,mount_price,status,payment_status,comment,store_id,stores(name)').order('job_date').order('slot'),sb.from('day_expenses').select('day_date,amount,comment')]);st.stores=stores||[];st.jobs=(jobs||[]).map(j=>({id:j.id,date:j.job_date,slot:j.slot,client:j.client_name,phone:j.phone||'',address:j.address||'',price:+j.mount_price||0,status:j.status,payment:j.payment_status,comment:j.comment||'',store_id:j.store_id,store:j.stores?.name||''}));st.exp={};(ex||[]).forEach(x=>st.exp[x.day_date]={amount:+x.amount||0,comment:x.comment||''});const ys=yrs();st.ry=ys.includes(st.ry)?st.ry:ys[ys.length-1];}
async function signin(e){e.preventDefault();msg('Вход...');const {error}=await sb.auth.signInWithPassword({email:E.ae.value.trim(),password:E.ap.value});if(error)msg(error.message,1);else msg('');}
async function signup(){msg('Создание доступа...');const {error}=await sb.auth.signUp({email:E.ae.value.trim(),password:E.ap.value,options:{emailRedirectTo:'https://montaji.vercel.app/'}});if(error)msg(error.message,1);else msg('Пользователь создан. Теперь войди.');}
function msg(t,e){E.am.textContent=t||'';E.am.className='auth-message muted'+(e?' auth-message--error':' auth-message--success');}
function ra(){fs();ff();fy();rc();rr();ta();}
function ta(){const a=st.profile?.role==='admin';E.ab.classList.toggle('hidden',!a);E.des.classList.toggle('hidden',!a);}
function fs(){E.jst.innerHTML='<option value="">Не выбран</option>'+st.stores.map(s=>`<option value="${s.id}">${h(s.name)}</option>`).join('');}
function ff(){E.fst.innerHTML='<option value="all">Все</option>'+st.stores.map(s=>`<option value="${s.id}">${h(s.name)}</option>`).join('');E.fss.innerHTML='<option value="all">Все</option>'+S.map(x=>`<option>${x}</option>`).join('');E.fps.innerHTML='<option value="all">Все</option>'+P.map(x=>`<option>${x}</option>`).join('');E.fst.value=st.fl.store;E.fss.value=st.fl.status;E.fps.value=st.fl.payment;E.ff.value=st.fl.fill;}
function fy(){const y=yrs();E.ryr.innerHTML=y.map(x=>`<option value="${x}">${x}</option>`).join('');E.rmo.value=String(st.rm);E.ryr.value=String(st.ry);}
function yrs(){const y=new Set([new Date().getFullYear()]);st.jobs.forEach(j=>y.add(+j.date.slice(0,4)));Object.keys(st.exp).forEach(d=>y.add(+d.slice(0,4)));return [...y].sort((a,b)=>a-b);}
function shift(n){let m=st.m+n,y=st.y;if(m<0){m=11;y--}if(m>11){m=0;y++}st.m=m;st.y=y;rc();}
function rc(){E.mt.textContent=cap(new Date(st.y,st.m,1).toLocaleDateString('ru-RU',{month:'long',year:'numeric'}));const first=new Date(st.y,st.m,1),last=new Date(st.y,st.m+1,0);let wd=first.getDay();wd=wd===0?7:wd;const prev=wd-1,days=last.getDate(),pl=new Date(st.y,st.m,0).getDate();const c=[];for(let i=prev-1;i>=0;i--)c.push(dc(new Date(st.y,st.m-1,pl-i),1));for(let d=1;d<=days;d++)c.push(dc(new Date(st.y,st.m,d),0));const next=Math.ceil(c.length/7)*7-c.length;for(let d=1;d<=next;d++)c.push(dc(new Date(st.y,st.m+1,d),1));E.cg.innerHTML=c.join('');E.cg.querySelectorAll('.calendar-day').forEach(n=>n.addEventListener('click',()=>od(n.dataset.date)));}
function dc(date,muted){const key=f(date),jobs=gj(key).filter(mt),cnt=jobs.length;if(!mf(cnt))return '<div class="calendar-day hidden"></div>';const cls=cnt>=4?'full':cnt===3?'busy':cnt>0?'partial':'free',u=new Set(jobs.map(j=>j.slot)),ind=SL.map(s=>`<span class="slot-indicator ${u.has(s.id)?'slot-indicator--busy':''}"></span>`).join(''),ex=st.exp[key]?.amount||0;return `<button class="calendar-day ${muted?'calendar-day--muted':''} calendar-day--${cls}" data-date="${key}"><div class="calendar-day__top"><span class="calendar-day__num">${date.getDate()}</span><span class="calendar-day__count">${cnt}/4</span></div><div class="calendar-day__slots">${ind}</div><div class="calendar-day__expense">${ex?`Расх. ${m(ex)}`:'&nbsp;'}</div></button>`;}
function mt(j){if(st.q&&!([j.client,j.phone,j.address].join(' ').toLowerCase().includes(st.q)))return false;if(st.fl.store!=='all'&&j.store_id!==st.fl.store)return false;if(st.fl.status!=='all'&&j.status!==st.fl.status)return false;if(st.fl.payment!=='all'&&j.payment!==st.fl.payment)return false;return true;}
function mf(c){if(st.fl.fill==='free')return c===0;if(st.fl.fill==='partial')return c>0&&c<4;if(st.fl.fill==='full')return c===4;return true;}
function gj(d){return st.jobs.filter(j=>j.date===d).sort((a,b)=>a.slot-b.slot);}
function oj(date=st.d,id=''){if(st.profile?.role!=='admin')return;E.jf.reset();E.jid.value='';E.jd.value=date;E.jslot.value='1';E.jss.value='Бронь';E.jps.value='Не оплачено';E.jt.textContent='Новый монтаж';E.jdel.hidden=true;if(id){const j=st.jobs.find(x=>x.id===id);if(j){E.jid.value=j.id;E.jd.value=j.date;E.jslot.value=String(j.slot);E.jc.value=j.client;E.jph.value=j.phone;E.ja.value=j.address;E.jst.value=j.store_id||'';E.jpr.value=String(j.price||'');E.jss.value=j.status;E.jps.value=j.payment;E.jco.value=j.comment;E.jt.textContent='Редактировать монтаж';E.jdel.hidden=false;}}os('jobSheet');}
async function saveJob(e){e.preventDefault();if(st.profile?.role!=='admin')return;const p={job_date:E.jd.value,slot:+E.jslot.value,client_name:E.jc.value.trim(),phone:E.jph.value.trim(),address:E.ja.value.trim(),store_id:E.jst.value||null,mount_price:+(E.jpr.value||0),status:E.jss.value,payment_status:E.jps.value,comment:E.jco.value.trim(),updated_by:st.profile.id};let error;if(E.jid.value){({error}=await sb.from('jobs').update(p).eq('id',E.jid.value));}else{p.created_by=st.profile.id;({error}=await sb.from('jobs').insert(p));}if(error){alert(error.message);return;}cs('jobSheet');await ld();ra();od(p.job_date);}
async function delJob(){if(st.profile?.role!=='admin'||!E.jid.value)return;if(!confirm('Удалить запись?'))return;const {error}=await sb.from('jobs').delete().eq('id',E.jid.value);if(error){alert(error.message);return;}cs('jobSheet');await ld();ra();}
function od(date){st.d=date;E.dt.textContent=cap(new Date(date+'T00:00:00').toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric',weekday:'long'}));const ex=st.exp[date]||{amount:'',comment:''};E.dei.value=ex.amount??'';E.dec.value=ex.comment??'';const jobs=gj(date);E.dsl.innerHTML=SL.map(s=>sbk(date,s,jobs.find(j=>j.slot===s.id))).join('');E.dst.innerHTML=dst(date,jobs);E.dsl.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>oj(date,b.dataset.edit)));E.dsl.querySelectorAll('[data-add]').forEach(b=>b.addEventListener('click',()=>{oj(date);E.jslot.value=b.dataset.add;}));os('daySheet');}
function sbk(date,slot,job){if(!job)return `<section class="slot-block"><div class="slot-block__head"><h3>${slot.l} <span class="muted">· ${slot.s}</span></h3>${st.profile?.role==='admin'?`<button class="ghost-btn" data-add="${slot.id}">Добавить</button>`:''}</div><div class="slot-empty">Свободно</div></section>`;const a=[];if(job.phone)a.push(`<a class="action-link" href="tel:${job.phone.replace(/[^\d+]/g,'')}">Позвонить</a>`);if(job.address)a.push(`<a class="action-link" href="https://maps.google.com/?q=${encodeURIComponent(job.address)}" target="_blank" rel="noopener">Карта</a>`);if(st.profile?.role==='admin')a.push(`<button class="action-link" type="button" data-edit="${job.id}">Изменить</button>`);return `<section class="slot-block"><div class="slot-block__head"><h3>${slot.l} <span class="muted">· ${slot.s}</span></h3></div><article class="job-card"><div class="job-card__top"><div><h4 class="job-card__client">${h(job.client)}</h4><div class="job-card__meta">${slot.s}</div></div><span class="pill" data-status="${h(job.status)}">${h(job.status)}</span></div><div class="job-card__details">${[job.phone?`📞 ${h(job.phone)}`:'',job.address?`📍 ${h(job.address)}`:'',job.store?`🏪 ${h(job.store)}`:'',`💰 ${m(job.price)} · ${h(job.payment)}`,job.comment?`📝 ${h(job.comment)}`:''].filter(Boolean).map(x=>`<div>${x}</div>`).join('')}</div><div class="job-card__actions">${a.join('')}</div></article></section>`;}
function dst(date,jobs){const r=jobs.reduce((s,j)=>s+j.price,0),e=+(st.exp[date]?.amount||0),n=r-e;return [['Монтажей',jobs.length],['Выручка',m(r)],['Расходка',m(e)],['Чистыми',m(n)]].map(([l,v])=>`<div class="mini-stat"><div class="mini-stat__label">${l}</div><div class="mini-stat__value">${v}</div></div>`).join('');}
async function saveExp(){if(st.profile?.role!=='admin')return;const d=st.d,p={day_date:d,amount:+(E.dei.value||0),comment:E.dec.value.trim(),updated_by:st.profile.id};const ex=st.exp[d];let error;if(ex){({error}=await sb.from('day_expenses').update(p).eq('day_date',d));}else{p.created_by=st.profile.id;({error}=await sb.from('day_expenses').insert(p));}if(error){alert(error.message);return;}await ld();ra();od(d);}
function rr(){fy();const mth=st.rm,yr=st.ry,mj=st.jobs.filter(j=>+j.date.slice(0,4)===yr&&+j.date.slice(5,7)===mth),me=Object.entries(st.exp).filter(([d])=>+d.slice(0,4)===yr&&+d.slice(5,7)===mth).reduce((s,[,v])=>s+(+v.amount||0),0),mr=mj.reduce((s,j)=>s+j.price,0),yj=st.jobs.filter(j=>+j.date.slice(0,4)===yr),ye=Object.entries(st.exp).filter(([d])=>+d.slice(0,4)===yr).reduce((s,[,v])=>s+(+v.amount||0),0),yrv=yj.reduce((s,j)=>s+j.price,0);E.sg.innerHTML=[['Монтажей за месяц',mj.length],['Выручка за месяц',m(mr)],['Расходка за месяц',m(me)],['Чистыми за месяц',m(mr-me)],['Монтажей за год',yj.length],['Выручка за год',m(yrv)],['Расходка за год',m(ye)],['Чистыми за год',m(yrv-ye)]].map(([l,v])=>`<div class="stat-card"><div class="stat-card__label">${l}</div><div class="stat-card__value">${v}</div></div>`).join('');E.al.innerHTML=yrs().slice().reverse().map(y=>{const jobs=st.jobs.filter(j=>+j.date.slice(0,4)===y),r=jobs.reduce((s,j)=>s+j.price,0),e=Object.entries(st.exp).filter(([d])=>+d.slice(0,4)===y).reduce((s,[,v])=>s+(+v.amount||0),0);return `<div class="archive-item"><div><div><strong>${y}</strong></div><div class="archive-item__stats">${jobs.length} монтажей · выручка ${m(r)} · чистыми ${m(r-e)}</div></div><button class="ghost-btn" data-year="${y}">CSV</button></div>`;}).join('');E.al.querySelectorAll('[data-year]').forEach(b=>b.addEventListener('click',()=>csv(true,+b.dataset.year)));}
function csv(yOnly=false,year=st.ry){const rows=(yOnly?st.jobs.filter(j=>+j.date.slice(0,4)===year):st.jobs.filter(j=>+j.date.slice(0,4)===st.ry&&+j.date.slice(5,7)===st.rm)).sort((a,b)=>a.date.localeCompare(b.date)||a.slot-b.slot).map(j=>({Дата:j.date,Слот:j.slot,Клиент:j.client,Телефон:j.phone,Адрес:j.address,Магазин:j.store,Цена:j.price,Статус:j.status,Оплата:j.payment,Комментарий:j.comment,Расходка_дня:st.exp[j.date]?.amount||0}));const H=rows.length?Object.keys(rows[0]):['Пусто'],csv=[H.join(';'),...rows.map(r=>H.map(k=>`"${String(r[k]??'').replaceAll('"','""')}"`).join(';'))].join('\r\n'),b=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8;'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=yOnly?`montazhi-${year}.csv`:`montazhi-${st.ry}-${String(st.rm).padStart(2,'0')}.csv`;document.body.appendChild(a);a.click();a.remove();}
function sw(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('screen--active'));document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('nav-item--active'));$(id).classList.add('screen--active');document.querySelector(`.nav-item[data-screen="${id}"]`).classList.add('nav-item--active');}
function os(id){$(id).classList.add('is-open')}function cs(id){$(id).classList.remove('is-open')}function f(d){return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)}function m(v){return new Intl.NumberFormat('ru-RU').format(+v||0)+' ₽'}function cap(v){return v?v[0].toUpperCase()+v.slice(1):v}function h(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}}