const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const value=(job,key)=>esc(job?.[key]??'');
const types=['Монтаж','Замер','Рекламация','Доставка','Сервис','Доп. доход'];
const statuses=['Запланирован','Выполнен','Отменён','Перенос'];

export const createJobForm=({job={},onSubmit=()=>{},onCancel=()=>{}})=>{
 const form=document.createElement('form'); form.className='job-form';
 form.innerHTML='<label>Тип<select name="type">'+types.map(x=>'<option'+(x===job.type?' selected':'')+'>'+x+'</option>').join('')+'</select></label><label>Дата<input name="date" type="date" value="'+value(job,'date')+'"></label><label>Слот<select name="slot">'+['1','2','3'].map(x=>'<option value="'+x+'"'+(String(job.slot||'1')===x?' selected':'')+'>'+x+'</option>').join('')+'</select></label><label>Клиент<input name="client" value="'+value(job,'client')+'" required></label><label>Телефон<input name="phone" inputmode="tel" value="'+value(job,'phone')+'"></label><label>Стоимость<input name="price" inputmode="decimal" value="'+value(job,'price')+'"></label><label>Адрес<input name="address" value="'+value(job,'address')+'"></label><label>Магазин / источник<input name="source" value="'+value(job,'source')+'"></label><div data-measure-fields hidden><label>Стоимость замера<input name="measurePrice" inputmode="decimal" value="'+value(job,'measurePrice')+'"></label><label><input name="measurePaid" type="checkbox"'+(job.measurePaid?' checked':'')+'> Замер оплачен</label><label>Зачёт замера<input name="measureCredit" inputmode="decimal" value="'+value(job,'measureCredit')+'"></label></div><label>Комментарий<textarea name="comment">'+value(job,'comment')+'</textarea></label><label>Статус<select name="status">'+statuses.map(x=>'<option'+(x===job.status?' selected':'')+'>'+x+'</option>').join('')+'</select></label><label class="job-form-completed">Дата выполнения<input name="completedDate" type="date" value="'+value(job,'completedDate')+'"></label><label class="job-form-paid"><input name="paid" type="checkbox"'+(job.paid!==false?' checked':'')+'> Оплачено</label><div class="job-form-actions"><button type="button" data-cancel>Отмена</button><button type="submit">Сохранить</button></div>';
 const sync=()=>{form.querySelector('[data-measure-fields]').hidden=form.elements.type.value!=='Замер'; form.elements.completedDate.disabled=form.elements.status.value!=='Выполнен'};
 form.elements.type.addEventListener('change',sync); form.elements.status.addEventListener('change',sync); sync();
 form.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(form);const n=k=>Number(String(fd.get(k)||'').replace(/\s/g,'').replace(',','.'))||0;const slot=Math.max(1,Number(fd.get('slot')||1));onSubmit({...job,type:String(fd.get('type')||'Монтаж'),date:String(fd.get('date')||''),slot:String(slot),client:String(fd.get('client')||'').trim(),phone:String(fd.get('phone')||'').trim(),price:n('price'),address:String(fd.get('address')||'').trim(),source:String(fd.get('source')||'').trim(),measurePrice:n('measurePrice'),measurePaid:form.elements.measurePaid?.checked===true,measureCredit:n('measureCredit'),comment:String(fd.get('comment')||'').trim(),status:String(fd.get('status')||'Запланирован'),completedDate:String(fd.get('completedDate')||''),paid:form.elements.paid.checked} );});
 form.querySelector('[data-cancel]').addEventListener('click',onCancel); return form;
};
