from pathlib import Path
import re
p=Path('app.js')
s=p.read_text()

def repl(name, body, nextname):
    global s
    pat=rf"function {name}\(.*?\nfunction {nextname}"
    m=re.search(pat,s,re.S)
    if not m:
        raise SystemExit(f'cannot find {name}->{nextname}')
    s=s[:m.start()]+body+'\nfunction '+nextname+s[m.end():]

repl('renderNotes', r'''function renderNotes(){const active=$('#activeNotes'),archive=$('#archivedNotes');if(!active||!archive)return;const a=notes.filter(n=>n.archived!==true),ar=notes.filter(n=>n.archived===true);active.innerHTML=a.length?a.map(noteCard).join(''):'<div class="muted">Активных заметок нет</div>';archive.innerHTML=ar.length?ar.map(noteCard).join(''):'<div class="muted">Архив пуст</div>';bindNotes();}''', 'noteCard')
repl('noteCard', r'''function noteCard(n){const job=n.linkedJobId?state.jobs.find(j=>j.id===n.linkedJobId):null,done=n.done===true,due=n.dueDate?fmtShort(n.dueDate):'';return`<article class="note-card ${n.archived?'archived':''} ${done?'note-done':''}"><div class="note-top"><label class="note-check"><input type="checkbox" data-note-done="${esc(n.id)}" ${done?'checked':''}><span></span></label><div class="note-title-wrap"><b>${esc(n.title||'Заметка')}</b>${job?`<small>↳ ${esc(job.client||'Без клиента')}</small>`:''}</div><div><button class="mini-btn" data-note-edit="${esc(n.id)}">Изм.</button>${n.archived?`<button class="mini-btn" data-note-restore="${esc(n.id)}">Вернуть</button>`:`<button class="mini-btn" data-note-archive="${esc(n.id)}">Архив</button>`}</div></div><p>${esc(n.text||'')}</p>${job?`<div class="note-context">${job.address?`📍 ${esc(job.address)}`:''}${job.phone?` · ${esc(job.phone)}`:''}</div>`:''}<div class="note-meta">${n.authorName?`<span>${esc(n.authorName)}</span>`:''}${due?`<span>до ${due}</span>`:''}</div></article>`;}''', 'bindNotes')
repl('bindNotes', r'''function bindNotes(){$$('.mini-btn').forEach(b=>{b.onclick=()=>{const id=b.dataset.noteEdit||b.dataset.noteArchive||b.dataset.noteRestore,n=notes.find(x=>x.id===id);if(!n)return;if(b.dataset.noteEdit)openNote(n);else setNoteState(id,!!b.dataset.noteArchive)}});$$('[data-note-done]').forEach(b=>{b.onchange=()=>setNoteDone(b.dataset.noteDone,b.checked)});}''', 'openNote')
repl('openNote', r'''function openNote(n=null){const jobs=state.jobs.filter(j=>!isCancelled(j)).sort((a,b)=>activityDate(b).localeCompare(activityDate(a)));const m=document.createElement('div');m.className='modal open';m.innerHTML=`<div class="backdrop"></div><div class="sheet"><div class="sheet-head"><div><div class="eyebrow">Общие заметки</div><h2>${n?'Изменить заметку':'Новая заметка'}</h2></div><button class="circle-btn" data-close>×</button></div><form id="noteForm"><label>Заголовок<input id="nTitle" required value="${esc(n?.title||'')}"></label><label>Текст<textarea id="nText" rows="5" required placeholder="Можно продиктовать голосом">${esc(n?.text||'')}</textarea></label><div class="form-row"><label>К выезду<select id="nJob"><option value="">Без привязки</option>${jobs.map(j=>`<option value="${esc(j.id)}" ${j.id===n?.linkedJobId?'selected':''}>${esc(j.date)} · ${esc(j.client||j.type)}${j.address?' · '+esc(j.address):''}</option>`).join('')}</select></label><label>Срок<input id="nDue" type="date" value="${esc(n?.dueDate||'')}"></label></div><button class="primary wide" type="submit">Сохранить</button></form></div>`;document.body.append(m);m.querySelector('.backdrop').onclick=()=>m.remove();m.querySelector('[data-close]').onclick=()=>m.remove();$('#noteForm',m).onsubmit=async e=>{e.preventDefault();const jobId=$('#nJob',m).value||'',authorName=user?.displayName||user?.email||'Пользователь',item={id:n?.id||uid(),title:$('#nTitle',m).value.trim(),text:$('#nText',m).value.trim(),archived:n?.archived===true,done:n?.done===true,linkedJobId:jobId,dueDate:$('#nDue',m).value||'',authorUid:n?.authorUid||user?.uid||'',authorName:n?.authorName||authorName,createdAt:n?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(!item.title||!item.text)return;try{await saveNotes(cur=>({...cur,notes:[...(cur.notes||[]).filter(x=>x.id!==item.id),item]}));m.remove();toast('Заметка сохранена','success')}catch(err){toast('Не удалось сохранить заметку','error')}};}''', 'setNoteState')
needle='function setNoteState(id,archived)'
insert=r'''async function setNoteDone(id,done){try{await saveNotes(cur=>({...cur,notes:(cur.notes||[]).map(n=>n.id===id?{...n,done,updatedAt:new Date().toISOString()}:n)}));toast(done?'Готово ✓':'Вернули в работу','success')}catch(e){toast('Не удалось изменить заметку','error')}}
'''
s=s.replace(needle,insert+needle,1)
old="async function loadServer(){if(!user||!online){serverReady=false;state=emptyState();notes=[];render();status('Нет интернета · данные не загружены','offline');return false;}status('Подключаем общую базу…');try{const [sharedSnap,notesSnap]=await Promise.all([F.getDocFromServer(F.doc(db,...SHARED_DOC)),F.getDocFromServer(F.doc(db,...NOTES_DOC))]);state=sharedSnap.exists()?normalize(sharedSnap.data().data):emptyState();notes=currentNotesData(notesSnap);serverReady=true;render();status('● Общая база · синхронизировано','online');return true;}catch(err){console.error(err);serverReady=false;state=emptyState();notes=[];render();status('База недоступна','offline');toast('Не удалось получить данные с сервера.','error');return false;}}"
new="async function loadServer(){if(!user||!online){serverReady=false;state=emptyState();notes=[];render();status('Нет интернета · данные не загружены','offline');return false;}status('Подключаем общую базу…');try{const sharedSnap=await F.getDocFromServer(F.doc(db,...SHARED_DOC));state=sharedSnap.exists()?normalize(sharedSnap.data().data):emptyState();serverReady=true;notes=[];render();status('● Общая база · синхронизировано','online');}catch(err){console.error(err);serverReady=false;state=emptyState();notes=[];render();status('База недоступна','offline');toast('Не удалось получить данные с сервера.','error');return false;}try{const notesSnap=await F.getDocFromServer(F.doc(db,...NOTES_DOC));notes=currentNotesData(notesSnap);}catch(err){console.warn('Notes load skipped',err);notes=[];}renderNotes();return true;}"
if old not in s: raise SystemExit('loadServer exact text not found')
s=s.replace(old,new,1)
p.write_text(s)
