import {icon} from '../ui/icons.js';
import {partnerFixture} from './partner-fixture.js';
import {WINDOWS,createRequest,nextAction,requestInstallation,visibleOrders} from './partner-domain.js';

const state={screen:'home',orders:structuredClone(partnerFixture.orders),selected:null,filter:'all',prefill:{},analyticsMetric:'requests',analyticsPeriod:'month'};
const root=document.querySelector('#partner-app');
const money=value=>new Intl.NumberFormat('ru-RU').format(value)+' ₽';
const logo=`<span class="partner-mark" aria-hidden="true"><svg viewBox="0 0 36 36"><path d="M8 30V6h19v24M8 6l12 5v19L8 30"/><path d="m13 17 3-3m-1 6 4-4"/><circle cx="17.5" cy="23" r="1"/></svg></span>`;
const names={home:'Главная',calendar:'Календарь',orders:'Заказы',clients:'Клиенты',more:'Ещё'};
const navIcons={home:'home',calendar:'calendar',orders:'briefcase',clients:'user',more:'more'};

function shell(content){
  const salon=partnerFixture.organization.salons.find(x=>x.id===partnerFixture.currentUser.salonId);
  return `<main class="partner-shell"><header class="partner-top">${logo}<div><b>MONTRA</b><span>ПАРТНЁР</span></div><button class="salon-switch" data-action="team">${partnerFixture.organization.name}<small>${salon.name}</small>${icon('chevron')}</button></header><div class="partner-content">${content}</div></main>
  <nav class="partner-dock" aria-label="Основная навигация">${Object.keys(names).map(key=>`<button data-screen="${key}" ${state.screen===key?'aria-current="page"':''}>${icon(navIcons[key])}<span>${names[key]}</span></button>`).join('')}</nav>`;
}

function actionCard(order){const action=nextAction(order);return `<button class="attention-card" data-order="${order.id}"><span class="attention-icon">${icon(action.owner==='store'?'spark':'clock')}</span><span><small>${action.owner==='store'?'Нужно ваше решение':'В работе у монтажника'}</small><b>${action.label}</b><em>${order.client} · ${order.address}</em></span>${icon('chevron')}</button>`}
function stats(){const own=visibleOrders(state.orders,'lavetra');const revenue=own.reduce((sum,x)=>sum+(x.sum||0),0);return `<section class="partner-stats"><button type="button" data-analytics="requests"><small>Заявки</small><b>${own.length}</b><span>в этом месяце</span></button><button type="button" data-analytics="revenue"><small>Принесли</small><b>${money(revenue)}</b><span>магазином</span></button><button type="button" data-analytics="installations"><small>Монтажи</small><b>${own.filter(x=>x.kind==='installation').length}</b><span>2 запланировано</span></button></section>`}
function orderCard(order){const action=nextAction(order);return `<button class="order-card" data-order="${order.id}"><span class="order-kind">${order.kind==='measure'?icon('measure'):icon('tools')}</span><span class="order-copy"><small>${order.id} · ${order.kind==='measure'?'Замер':'Монтаж'}</small><b>${order.client}</b><em>${order.address}</em><span class="action-pill ${action.owner}">${action.label}</span></span><span class="order-side">${order.sum?money(order.sum):icon('chevron')}</span></button>`}

function home(){const actions=state.orders.filter(x=>nextAction(x).owner==='store');const upcoming=state.orders.filter(x=>x.stage==='scheduled').slice(0,2);return shell(`
  <section class="welcome"><div><small>Добрый день, ${partnerFixture.currentUser.name.split(' ')[0]}</small><h1>${partnerFixture.organization.name}</h1><p>Общий кабинет двух салонов</p></div><button class="avatar" data-action="team">АВ</button></section>
  <section class="partner-hero"><div class="hero-shade"></div><span class="hero-kicker">Общий результат</span><h2>${money(state.orders.reduce((s,x)=>s+(x.sum||0),0))}</h2><p>Монтажей и замеров из ваших салонов</p><button data-screen="calendar">Выбрать дату ${icon('arrow')}</button></section>
  <div class="section-row"><h2>Требует внимания <span>${actions.length}</span></h2></div>${actions.map(actionCard).join('')||'<p class="quiet">Всё согласовано</p>'}
  ${stats()}<div class="section-row"><h2>Ближайшие работы</h2><button data-screen="orders">Все заказы</button></div>${upcoming.map(orderCard).join('')}
  <button class="new-request" data-action="new">${icon('plus')}<span><b>Новая заявка</b><small>Замер или монтаж</small></span>${icon('chevron')}</button>`)}

function calendar(){return shell(`<section class="screen-title"><small>Загрузка монтажников</small><h1>Выберите удобный день</h1><p>Мы показываем только доступность. Данные других магазинов скрыты.</p></section><div class="calendar-key"><i></i> свободно <i class="medium"></i> по запросу</div><section class="date-rail">${partnerFixture.availability.map((d,i)=>`<button class="date-chip ${i===0?'active':''}" data-date-index="${i}"><small>${d.day}</small><b>${d.date.split(' ')[0]}</b><span>${d.date.split(' ')[1]}</span></button>`).join('')}</section><div id="window-list">${windowsFor(0)}</div><aside class="privacy-note">${icon('check')}<span><b>Приватность соблюдена</b><small>Вы видите загрузку дня, но не чужих клиентов и заказы.</small></span></aside>`)}
function windowsFor(index){const day=partnerFixture.availability[index];return `<section class="window-panel"><div class="section-row"><h2>${day.date}</h2><span>4 варианта</span></div>${WINDOWS.map(w=>{const status=day.windows[w.id],disabled=status==='Занято';return `<button class="window-row" data-window="${w.id}" data-date="${day.date}" ${disabled?'disabled':''}><span class="window-time">${icon(w.id==='call'?'phone':'clock')}</span><span><b>${w.label}</b><small>${w.time}</small></span><em class="${disabled?'busy':''}">${status}</em>${!disabled?icon('chevron'):''}</button>`}).join('')}</section>`}

function orders(){const filters=[['all','Все'],['store','Ждут вас'],['installer','У монтажника'],['done','Готово']];let list=visibleOrders(state.orders,'lavetra');if(state.filter!=='all')list=list.filter(x=>state.filter==='done'?['completed','measured'].includes(x.stage):nextAction(x).owner===state.filter);return shell(`<section class="screen-title"><small>Lavetra · оба салона</small><h1>Заказы</h1><p>${list.length} записей в выбранном разделе</p></section><div class="filter-rail">${filters.map(([id,label])=>`<button data-filter="${id}" class="${state.filter===id?'active':''}">${label}</button>`).join('')}</div><section class="order-list">${list.map(orderCard).join('')||'<div class="empty-state"><h3>Здесь пока пусто</h3><p>Новые заявки появятся в этом разделе автоматически.</p></div>'}</section><button class="floating-add" data-action="new">${icon('plus')}</button>`)}

function analytics(){const own=visibleOrders(state.orders,'lavetra');const definitions={requests:{title:'Заявки',hint:'Все заявки магазина',value:String(own.length),matches:()=>true},revenue:{title:'Принесли',hint:'Работы, из которых сложилась сумма',value:money(own.reduce((sum,x)=>sum+(x.sum||0),0)),matches:order=>Number(order.sum||0)>0},installations:{title:'Монтажи',hint:'Запланированные и выполненные монтажи',value:String(own.filter(x=>x.kind==='installation').length),matches:order=>order.kind==='installation'}};const metric=definitions[state.analyticsMetric]||definitions.requests;const periods=[['month','Месяц'],['quarter','3 месяца'],['year','Год'],['all','Всё время']];const history=own.filter(metric.matches);return shell(`<section class="screen-title analytics-title"><button type="button" class="analytics-back" data-screen="home">← Главная</button><small>Статистика магазина</small><h1>${metric.title}</h1><p>${metric.hint}</p></section><section class="analytics-summary"><small>${periods.find(x=>x[0]===state.analyticsPeriod)?.[1]||'Месяц'}</small><b>${metric.value}</b></section><div class="filter-rail analytics-periods">${periods.map(([id,label])=>`<button type="button" data-period="${id}" class="${state.analyticsPeriod===id?'active':''}">${label}</button>`).join('')}</div><div class="section-row"><h2>История <span>${history.length}</span></h2></div><section class="order-list">${history.map(orderCard).join('')||'<div class="empty-state"><h3>Пока пусто</h3><p>Здесь появятся записи по выбранному показателю.</p></div>'}</section>`)}

function clients(){const clients=[...new Map(state.orders.map(x=>[x.phone,x])).values()];return shell(`<section class="screen-title"><small>Только клиенты Lavetra</small><h1>Клиенты</h1><p>Контакты собраны из заявок обоих салонов.</p></section><label class="partner-search">${icon('search')}<input id="client-search" placeholder="Имя, телефон или адрес"></label><section class="client-list">${clients.map(x=>`<button class="client-card" data-order="${x.id}"><span>${x.client.split(' ').map(s=>s[0]).join('').slice(0,2)}</span><span><b>${x.client}</b><small>${x.phone}</small><em>${x.address}</em></span>${icon('chevron')}</button>`).join('')}</section>`)}
function more(){return shell(`<section class="screen-title"><small>Организация</small><h1>Команда Lavetra</h1><p>2 салона · 4 менеджера</p></section><section class="team-card"><div class="team-summary"><span>${logo}</span><div><b>Lavetra</b><small>Партнёр с сентября 2026</small></div></div>${partnerFixture.team.map(x=>`<article><span class="mini-avatar">${x.name.split(' ').map(s=>s[0]).join('')}</span><span><b>${x.name}</b><small>${x.salon} · ${x.orders} заявок</small></span><strong>${money(x.revenue)}</strong></article>`).join('')}</section><aside class="demo-note"><b>Демо-режим</b><p>Данные этого прототипа не записываются в общую базу Montaji.</p></aside>`)}

function render(){root.innerHTML=state.screen==='home'?home():state.screen==='calendar'?calendar():state.screen==='orders'?orders():state.screen==='clients'?clients():state.screen==='analytics'?analytics():more();}
function openSheet(html){document.body.insertAdjacentHTML('beforeend',`<div class="sheet-layer"><button class="sheet-scrim" data-close aria-label="Закрыть"></button><section class="partner-sheet"><div class="sheet-handle"></div>${html}</section></div>`);document.body.classList.add('sheet-open')}
function closeSheet(){document.querySelector('.sheet-layer')?.remove();document.body.classList.remove('sheet-open')}

function newRequest(){const p=state.prefill;openSheet(`<header class="sheet-head"><div><small>Новая заявка</small><h2 data-request-title>Запросить замер</h2></div><button data-close>${icon('close')}</button></header><form id="request-form" class="partner-form"><div class="kind-switch"><label><input type="radio" name="kind" value="measure" checked><span>${icon('measure')}Замер</span></label><label><input type="radio" name="kind" value="installation"><span>${icon('tools')}Монтаж</span></label></div><label>Клиент<input name="client" required placeholder="Имя клиента"></label><label>Телефон<input name="phone" required inputmode="tel" placeholder="+7 900 000-00-00"></label><label>Адрес<input name="address" required placeholder="Улица, дом, квартира"></label><fieldset class="schedule-choice"><legend>Когда провести замер?</legend><label><input type="radio" name="schedulingMode" value="preferred" checked><span><b>Есть пожелание по дате</b><small>Указать удобную дату и период</small></span></label><label><input type="radio" name="schedulingMode" value="client_call"><span><b>Согласовать с клиентом</b><small>Монтажник сам договорится о дате и времени</small></span></label></fieldset><div class="form-grid" data-preferred-time><label>Дата<input name="desiredDate" value="${p.date||''}" placeholder="25 сент."></label><label>Время<select name="windowId">${WINDOWS.map(w=>`<option value="${w.id}" ${p.window===w.id?'selected':''}>${w.label}</option>`).join('')}</select></label></div><label><span data-request-comment-label>Комментарий менеджера</span><textarea name="comment" rows="3" placeholder="Срочность, пожелания клиента, модель двери, когда связаться"></textarea></label><label class="file-field">${icon('plus')}<span><b>Добавить фото проёма</b><small>JPG или HEIC</small></span><input type="file" accept="image/*"></label><button class="submit-request" type="submit"><span data-request-submit>Отправить заявку на замер</span> ${icon('arrow')}</button></form>`)}
function orderDetails(id){const order=state.orders.find(x=>x.id===id);state.selected=id;const action=nextAction(order);openSheet(`<header class="sheet-head"><div><small>${order.id} · ${order.kind==='measure'?'Замер':'Монтаж'}</small><h2>${order.client}</h2></div><button data-close>${icon('close')}</button></header><div class="detail-body"><div class="detail-action ${action.owner}"><small>Следующий шаг</small><b>${action.label}</b></div><dl><div><dt>${icon('phone')} Телефон</dt><dd><a href="tel:${order.phone}">${order.phone}</a></dd></div><div><dt>${icon('pin')} Адрес</dt><dd>${order.address}</dd></div><div><dt>${icon('calendar')} ${order.schedulingMode==='client_call'?'Время замера':'Желаемое время'}</dt><dd>${order.proposal||(order.schedulingMode==='client_call'?'Согласовать с клиентом':`${order.desiredDate||'Дата не указана'} · ${WINDOWS.find(x=>x.id===order.windowId)?.time||''}`)}</dd></div></dl>${order.measurement?measurement(order):''}${order.stage==='store_action'?`<button class="submit-request" data-confirm="${order.id}">${icon('check')} Подтвердить время</button>`:''}<section class="timeline"><h3>История</h3>${order.timeline.map(x=>`<div><i></i><span><b>${x.label}</b><small>${x.at}</small></span></div>`).join('')}</section></div>`)}
function measurement(order){const m=order.measurement||{};const works=m.additionalWorks||[];const width=m.openingWidth??m.width;const height=m.openingHeight??m.height;const doorSize=m.doorSize||(width&&height?`${width} × ${height} мм`:'Размер двери не указан');const handing=m.handing||m.opening||'';return `<section class="measurement"><div class="section-row"><h3>Результат замера</h3><span>Опубликован</span></div><div class="measurement-grid"><article class="wide"><small>Рекомендуемая дверь</small><b>${doorSize}</b></article>${handing?`<article class="wide"><small>Открывание</small><b>${handing}</b></article>`:''}</div>${m.installationPrice?`<p><strong>Монтаж:</strong> ${money(m.installationPrice)}</p>`:''}${works.map(w=>`<p><strong>${w.title}:</strong> ${money(w.price)}</p>`).join('')}${m.total?`<p><strong>Работы итого:</strong> ${money(m.total)}</p>`:''}${m.installerComment||m.note?`<p>${m.installerComment||m.note}</p>`:''}${!order.installationRequested?`<button class="submit-request" data-install="${order.id}">Запросить монтаж ${icon('arrow')}</button>`:''}</section>`}

root.addEventListener('click',e=>{const metric=e.target.closest('[data-analytics]')?.dataset.analytics;if(metric){state.analyticsMetric=metric;state.screen='analytics';render();return}const period=e.target.closest('[data-period]')?.dataset.period;if(period){state.analyticsPeriod=period;render();return}const screen=e.target.closest('[data-screen]')?.dataset.screen;if(screen){state.screen=screen;render();return}const order=e.target.closest('[data-order]')?.dataset.order;if(order){orderDetails(order);return}const filter=e.target.closest('[data-filter]')?.dataset.filter;if(filter){state.filter=filter;render();return}const date=e.target.closest('[data-date-index]');if(date){document.querySelectorAll('.date-chip').forEach(x=>x.classList.remove('active'));date.classList.add('active');document.querySelector('#window-list').innerHTML=windowsFor(+date.dataset.dateIndex);return}const window=e.target.closest('[data-window]');if(window){state.prefill={date:window.dataset.date,window:window.dataset.window};newRequest();return}if(e.target.closest('[data-action="new"]'))newRequest();if(e.target.closest('[data-action="team"]')){state.screen='more';render()}});
document.addEventListener('click',e=>{if(e.target.closest('[data-close]'))closeSheet();const confirm=e.target.closest('[data-confirm]')?.dataset.confirm;if(confirm){state.orders=state.orders.map(x=>x.id===confirm?{...x,stage:'scheduled',timeline:[...x.timeline,{label:'Магазин подтвердил время',at:'только что'}]}:x);closeSheet();render()}const install=e.target.closest('[data-install]')?.dataset.install;if(install){state.orders=state.orders.map(x=>x.id===install?requestInstallation(x):x);closeSheet();render()}});
document.addEventListener('submit',e=>{if(e.target.id!=='request-form')return;e.preventDefault();const values=Object.fromEntries(new FormData(e.target));state.orders.unshift(createRequest(values,{organizationId:'lavetra',salonId:partnerFixture.currentUser.salonId,managerId:partnerFixture.currentUser.id}));state.prefill={};closeSheet();state.screen='orders';render()});
document.addEventListener('change',e=>{if(!e.target.matches('#request-form input[name="schedulingMode"]'))return;const form=e.target.closest('#request-form');const preferred=form?.querySelector('[data-preferred-time]');if(preferred)preferred.hidden=e.target.value==='client_call'});
document.addEventListener('change',e=>{if(!e.target.matches('#request-form input[name="kind"]'))return;const installation=e.target.value==='installation';const layer=e.target.closest('.sheet-layer');const title=layer?.querySelector('[data-request-title]');const submit=layer?.querySelector('[data-request-submit]');if(title)title.textContent=installation?'Запросить монтаж':'Запросить замер';if(submit)submit.textContent=installation?'Отправить заявку на монтаж':'Отправить заявку на замер';const commentLabel=layer?.querySelector('[data-request-comment-label]');if(commentLabel)commentLabel.textContent='Комментарий менеджера'});
document.addEventListener('input',e=>{if(e.target.id!=='client-search')return;const q=e.target.value.toLowerCase();document.querySelectorAll('.client-card').forEach(card=>card.hidden=!card.textContent.toLowerCase().includes(q))});
render();
